#!/usr/bin/env python
from __future__ import print_function

import imas,os,argparse

# This script imports an equilibrium IDS, rigidly shifts it vertically, and then adds it to the output IDS

# Management of input arguments
parser = argparse.ArgumentParser(description=\
	 '---- To copy an IDS from a data-entry to another one ----')
parser.add_argument('-si','--shot_input',help='Input shot number', required=True,type=int)
parser.add_argument('-ri','--run_input',help='Input run number', required=True,type=int)
parser.add_argument('-so','--shot_output',help='Output shot number', required=True,type=int)
parser.add_argument('-ro','--run_output',help='Output run number', required=True,type=int)
parser.add_argument('-u','--user_or_path',help='User or path name of the DB where the data-entry is located', required=False)
parser.add_argument('-d','--database',help='Database name of the DB where the data-entry is located', required=False)
parser.add_argument('-s','--shift',help='Upward shift of equilibriumi (m)', required=True)

args = vars(parser.parse_args())

# idscp -si 131035 -ri 124 -so 123001 -ro 1 -s -0.01 -u bonninx -d iter

shot_in  = args["shot_input"]
run_in   = args["run_input"]
shot_out = args["shot_output"]
run_out  = args["run_output"]
ids      = "equilibrium"
z_shift  = float(args["shift"])

# User or path name
if args['user_or_path'] != None:
    user_or_path = args["user_or_path"]
else:
    user_or_path = os.getenv('USER')

# Database name
if args['database'] != None:
    database = args['database']
else:
    database = 'iter'

version = os.getenv('IMAS_VERSION')[0]

# OPEN INPUT
input = imas.ids(shot_in,run_in,0,0)
input.open_env(user_or_path,database,version)
if hasattr(eval('input.'+ids),'idx'):
  idx_in = eval('input.'+ids+'.idx')
else:
  idx_in = eval('input.'+ids+'._idx')

# GET IDS FROM INPUT
eval('input.'+ids+'.get()');

# OPEN OUTPUT
output = imas.ids(shot_out,run_out,0,0)
output.open_env(user_or_path,database,version)
if hasattr(eval('output.'+ids),'idx'):
   idx_out = eval('output.'+ids+'.idx')
else:
   idx_out = eval('output.'+ids+'._idx')

# COPY IDS FROM INPUT TO OUTPUT
exec('output.'+ids+' = input.'+ids)
eval('output.'+ids+'.setExpIdx(idx_out)')

# SHIFT EQUILIBRIUM INPUT IDS
print ('Shifting equilibrium by '+str(z_shift)+' m')
for itime in range(len(input.equilibrium.time_slice)):
   for iz in range(len(input.equilibrium.time_slice[itime].boundary.outline.z)):
      output.equilibrium.time_slice[itime].boundary.outline.z[iz] = input.equilibrium.time_slice[itime].boundary.outline.z[iz] + z_shift
   for iz in range(len(input.equilibrium.time_slice[itime].boundary.lcfs.z)):
      output.equilibrium.time_slice[itime].boundary.lcfs.z[iz] = input.equilibrium.time_slice[itime].boundary.lcfs.z[iz] + z_shift
   output.equilibrium.time_slice[itime].boundary.geometric_axis.z = input.equilibrium.time_slice[itime].boundary.geometric_axis.z + z_shift
   for ixpt in range(len(input.equilibrium.time_slice[itime].boundary.x_point)):
      output.equilibrium.time_slice[itime].boundary.x_point[ixpt].z = input.equilibrium.time_slice[itime].boundary.x_point[ixpt].z + z_shift
   for istr in range(len(input.equilibrium.time_slice[itime].boundary.strike_point)):
      output.equilibrium.time_slice[itime].boundary.strike_point[istr].z = input.equilibrium.time_slice[itime].boundary.strike_point[istr].z + z_shift
   output.equilibrium.time_slice[itime].boundary.active_limiter_point.z = input.equilibrium.time_slice[itime].boundary.active_limiter_point.z + z_shift
   for iz in range(len(input.equilibrium.time_slice[itime].boundary_separatrix.outline.z)):
      output.equilibrium.time_slice[itime].boundary_separatrix.outline.z[iz] = input.equilibrium.time_slice[itime].boundary_separatrix.outline.z[iz] + z_shift
   output.equilibrium.time_slice[itime].boundary_separatrix.geometric_axis.z = input.equilibrium.time_slice[itime].boundary_separatrix.geometric_axis.z + z_shift
   for ixpt in range(len(input.equilibrium.time_slice[itime].boundary_separatrix.x_point)):
      output.equilibrium.time_slice[itime].boundary.x_point[ixpt].z = input.equilibrium.time_slice[itime].boundary.x_point[ixpt].z + z_shift
   for istr in range(len(input.equilibrium.time_slice[itime].boundary.strike_point)):
      output.equilibrium.time_slice[itime].boundary.strike_point[istr].z = input.equilibrium.time_slice[itime].boundary.strike_point[istr].z + z_shift
   output.equilibrium.time_slice[itime].boundary.active_limiter_point.z = input.equilibrium.time_slice[itime].boundary.active_limiter_point.z + z_shift
   for iq in range(len(input.equilibrium.time_slice[itime].constraints.q)):
      output.equilibrium.time_slice[itime].constraints.q[iq].position.z = input.equilibrium.time_slice[itime].constraints.q[iq].position.z + z_shift
   for ixpt in range(len(input.equilibrium.time_slice[itime].constraints.x_point)):
      output.equilibrium.time_slice[itime].constraints.x_point[ixpt].position_measured.z = input.equilibrium.time_slice[itime].constraints.x_point[ixpt].position_measured.z + z_shift
      output.equilibrium.time_slice[itime].constraints.x_point[ixpt].position_reconstructed.z = input.equilibrium.time_slice[itime].constraints.x_point[ixpt].position_reconstructed.z + z_shift
   for istr in range(len(input.equilibrium.time_slice[itime].constraints.strike_point)):
      output.equilibrium.time_slice[itime].constraints.strike_point[istr].position_measured.z = input.equilibrium.time_slice[itime].constraints.strike_point[istr].position_measured.z + z_shift
      output.equilibrium.time_slice[itime].constraints.strike_point[istr].position_reconstructed.z = input.equilibrium.time_slice[itime].constraints.strike_point[istr].position_reconstructed.z + z_shift
   output.equilibrium.time_slice[itime].global_quantities.magnetic_axis.z = input.equilibrium.time_slice[itime].global_quantities.magnetic_axis.z + z_shift
   for iz in range(len(input.equilibrium.time_slice[itime].profiles_1d.geometric_axis.z)):
      output.equilibrium.time_slice[itime].profiles_1d.geometric_axis.z[iz] = input.equilibrium.time_slice[itime].profiles_1d.geometric_axis.z[iz] + z_shift
   for i2d in range(len(input.equilibrium.time_slice[itime].profiles_2d)):
      if input.equilibrium.time_slice[itime].profiles_2d[i2d].grid_type == 1:
         for iz in range(len(input.equilibrium.time_slice[itime].profiles_2d[i2d].grid.dim2)):
            output.equilibrium.time_slice[itime].profiles_2d[i2d].grid.dim2[iz] = input.equilibrium.time_slice[itime].profiles_2d[i2d].grid.dim2[iz] + z_shift
      for i1 in range(len(input.equilibrium.time_slice[itime].profiles_2d[i2d].z)):
         for i2 in range(len(input.equilibrium.time_slice[itime].profiles_2d[i2d].z[i1])):
            output.equilibrium.time_slice[itime].profiles_2d[i2d].z[i1][i2] = input.equilibrium.time_slice[itime].profiles_2d[i2d].z[i1][i2] + z_shift
   for iggd in range(len(input.equilibrium.time_slice[itime].ggd)):
      for iz in range(len(input.equilibrium.time_slice[itime].ggd[iggd].z)):
         for i in range(len(input.equilibrium.time_slice[itime].ggd[iggd].z[iz].values)):
            output.equilibrium.time_slice[itime].ggd[iggd].z[iz].values[i] = input.equilibrium.time_slice[itime].ggd[iggd].z[iz].values[i] + z_shift
   if input.equilibrium.time_slice[itime].coordinate_system.grid_type == 1:
      for iz in range(len(input.equilibrium.time_slice[itime].coordinate_system.grid.dim2)):
         output.equilibrium.time_slice[itime].coordinate_system.grid.dim2[iz] = input.equilibrium.time_slice[itime].coordinate_system.grid.dim2[iz] + z_shift
   for i1 in range(len(input.equilibrium.time_slice[itime].coordinate_system.z)):
      for i2 in range(len(input.equilibrium.time_slice[itime].coordinate_system.z[i1])):
         output.equilibrium.time_slice[itime].coordinate_system.z[i1][i2] = input.equilibrium.time_slice[itime].coordinate_system.z[i1][i2] + z_shift

output.equilibrium.ids_properties.comment = input.equilibrium.ids_properties.comment+' (shifted vertically by '+str(z_shift)+' m)'

# PUT IDS INTO OUTPUT
eval('output.'+ids+'.put()')

# CLOSE FILES
input.close()
output.close()

