#!/usr/bin/env python
from os import getenv
from sys import exit
from sys import stdout
import argparse
import yaml
import imas
import idschk
from idschk import *


# ----------------------------------------------------------------------


def main():
    """
    Command Interface of IDS Data Validation Tool w.r.t. DD (IDSDef.xml)
    """

    # Open the database
    try:
        db = IMASData(
            args.user_or_path,
            args.database,
            getenv("IMAS_VERSION")[0],
            args.shot,
            args.run,
        ).open()
    except:
        exit(
            "can not open user_or_path={}, database={}, shot={}, run={}".format(
                args.user_or_path, args.database, args.shot, args.run
            )
        )

    # Initialization for yaml Dumper
    yaml.Dumper.ignore_aliases = lambda *args: True

    # COCOS Initialization
    index = {"COCOS": idschk.IDS_COCOS, "ipsign": args.ipsign, "b0sign": args.b0sign}
    cocos = COCOS(index=index).get()

    # Validate COCOS in IDS/equilibrium
    if args.cocos:
        try:
            cocos2 = compute_COCOS(db.equilibrium, cocos_check=cocos)
        except Exception as e:
            exit("cannot compute COCOS: {}".format(e))

        if cocos2["COCOS"] == cocos["COCOS"]:
            print("COCOS: {}".format(cocos2["COCOS"]))
        else:
            yaml.dump(
                {"COCOS Indication": cocos2},
                stdout,
                indent=4,
                default_flow_style=False,
                sort_keys=False,
            )

    # IDS Validation
    if args.schema_file:

        # Load IMAS-DD File
        root = load_XML(idschk.FILE_IDSDef)

        # Schema Initialization
        schema = load_YAML(args.schema_file)

        for idsname in schema.keys():
            if (args.idslist is None) or (idsname in args.idslist):
                dd0 = [dd for dd in root if dd.get("name") == idsname][0]
                maxoc = int(dd0.get("maxoccur"))
                #
                for occ in range(maxoc):
                    try:
                        ids = eval("db." + idsname)
                        idstime = ids.partialGet("time", occ)
                        # IDS get()/getSlice()
                        if (args.check_all) or (idstime is None):
                            ids.get(occ)
                        else:
                            time_slice, itime = find_time(idstime, args.time)
                            ids.getSlice(time_slice, 1, occ)
                    except Exception as e:
                        exit("cannot retrieve IDS: {}".format(e))

                    flag, dump = ids_validator(ids, schema, dd=dd0, occ=occ)


# ----------------------------------------------------------------------


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="IDS Data Validation Tool")
    parser.add_argument(
        "-u",
        "--user_or_path",
        dest="user_or_path",
        help="User or path name of DB where the data-entry is located",
        required=False,
        default="public",
    )
    parser.add_argument(
        "-d",
        "--database",
        dest="database",
        help="DB name where the data-entry is located",
        required=False,
        default="iter",
    )
    parser.add_argument(
        "-s", "--shot", dest="shot", help="Shot number", required=True, type=int
    )
    parser.add_argument(
        "-r", "--run", dest="run", help="Run number", required=True, type=int
    )
    parser.add_argument(
        "-l",
        "--list",
        dest="idslist",
        help="IDS names to be checked",
        required=False,
        nargs="*",
    )
    parser.add_argument(
        "-p",
        "--properties",
        action="store_true",
        dest="prop",
        help="Report only ids_properties",
        required=False,
    )
    parser.add_argument(
        "-a",
        "--check_all",
        action="store_true",
        dest="check_all",
        help="Check all elements in IDSs, otherwise check one time-slice (default)",
        required=False,
    )

    parser.add_argument(
        "-t", "--time", help="Time (default=middle)", type=float, default=-99.0
    )
    parser.add_argument(
        "-f",
        "--schema_file",
        dest="schema_file",
        help="File name of validation schema",
        required=False,
        default=None,
    )
    parser.add_argument(
        "--ipsign",
        dest="ipsign",
        help="sign(Ip), default=-1",
        required=False,
        type=int,
        default=-1,
        choices=[-1, 1],
    )
    parser.add_argument(
        "--b0sign",
        dest="b0sign",
        help="sign(B0), default=-1",
        required=False,
        type=int,
        default=-1,
        choices=[-1, 1],
    )
    parser.add_argument(
        "--verbose",
        help="increase output verbosity",
        required=False,
        default=False,
        action="store_true",
    )
    parser.add_argument(
        "-c",
        "--cocos",
        help="Compute COCOS values from IDS/equilibrium",
        required=False,
        default=False,
        action="store_true",
    )
    idschk.args = args = parser.parse_args()
    main()
