#!/usr/bin/env python
from __future__ import print_function

import imas,os,argparse

# Management of input arguments
parser = argparse.ArgumentParser(description=\
	 '---- To copy an IDS from a data-entry to another one ----')
parser.add_argument('-si','--shot_input',help='Input shot number', required=True,type=int)
parser.add_argument('-ri','--run_input',help='Input run number', required=True,type=int)
parser.add_argument('-so','--shot_output',help='Output shot number', required=True,type=int)
parser.add_argument('-ro','--run_output',help='Output run number', required=True,type=int)
parser.add_argument('-u','--user_or_path',help='User or path name of the DB where the data-entry is located', required=False)
parser.add_argument('-d','--database',help='Database name of the DB where the data-entry is located', required=False)
parser.add_argument('-ids','--ids',help='IDS to copy', required=True)

args = vars(parser.parse_args())

# idscp -si 7897 -ri 32 -so 7897 -ro 31 -u schneim -d iter -ids equilibrium

shot_in  = args["shot_input"]
run_in   = args["run_input"]
shot_out = args["shot_output"]
run_out  = args["run_output"]
ids      = args["ids"]

# User or path name
if args['user_or_path'] != None:
    user_or_path = args["user_or_path"]
else:
    user_or_path = os.getenv('USER')

# Database name
if args['database'] != None:
    database = args['database']
else:
    database = 'iter'

version = os.getenv('IMAS_VERSION')[0]

# OPEN INPUT
input = imas.ids(shot_in,run_in,0,0)
input.open_env(user_or_path,database,version)
if hasattr(eval('input.'+ids),'idx'):
  idx_in = eval('input.'+ids+'.idx')
else:
  idx_in = eval('input.'+ids+'._idx')

# GET IDS FROM INPUT
eval('input.'+ids+'.get()');

# OPEN OUTPUT
output = imas.ids(shot_out,run_out,0,0)
output.open_env(user_or_path,database,version)
if hasattr(eval('output.'+ids),'idx'):
   idx_out = eval('output.'+ids+'.idx')
else:
   idx_out = eval('output.'+ids+'._idx')

# COPY IDS FROM INPUT TO OUTPUT
exec('output.'+ids+' = input.'+ids)
eval('output.'+ids+'.setExpIdx(idx_out)')

# PUT IDS INTO OUTPUT
eval('output.'+ids+'.put()')

# CLOSE FILES
input.close()
output.close()

