#!/usr/bin/env python

import argparse, pyual
import init_mendeleiev as mend
from os import system
from sys import exit

# ----------------------------------------------------------------------

# Management of input arguments
parser = argparse.ArgumentParser(description=\
	 '---- List ids content for yaml files aimed at describing a scenario ----')
parser.add_argument('-u','--user',help='username of the DB where the datafile is located', required=True)
parser.add_argument('-t','--tokamakname',help='tokamak name of the DB where the datafile is located', required=True)
parser.add_argument('-s','--shot',help='shot number', required=True,type=int)
parser.add_argument('-r','--run',help='run number',required=True,type=int)
args = vars(parser.parse_args())
shot = args["shot"]
run  = args["run"]
user = args["user"]
tokamakname = args["tokamakname"]

# Open the database and read the necessary IDSs
cli = pyual.Client(shot,run,user=user)

# Read necessary IDSs from database
try:
    equilibrium = cli.get('equilibrium')
except:
    print "The equilibrium IDS is absent from the input datafile"
    print "----> Aborted."
    exit()
try:
    core_profiles = cli.get('core_profiles')
except:
    print "The core_profiles IDS is absent from the input datafile"
    print "----> Aborted."
    exit()

# Mendeleiev table
table_mendeleiev = mend.create_table_mendeleiev()

# Fill the variables necessary to complete the yaml description file
try:
    magnetic_field = equilibrium.time_slice[0].global_quantities.magnetic_axis.b_tor
except:
    print "equilibrium.time_slice[0].global_quantities.magnetic_axis.b_tor could not be read"
    print "----> Aborted."
    exit()

try:
    plasma_current = equilibrium.time_slice[0].global_quantities.ip*1.e-6
except:
    print "equilibrium.time_slice[0].global_quantities.ip could not be read"
    print "----> Aborted."
    exit()

try:
    a = int(core_profiles.profiles_1d[0].ion[0].element[0].a)
except:
    print "core_profiles.profiles_1d[0].ion[0].element[0].a could not be read"
    print "----> Aborted."
    exit()

try:
    z = int(core_profiles.profiles_1d[0].ion[0].element[0].z_n)
except:
    print "core_profiles.profiles_1d[0].ion[0].element[0].z_n could not be read"
    print "----> Aborted."
    exit()

try:
    line_averaged_density = core_profiles.profiles_1d[0].electrons.density[0]
except:
    print "core_profiles.profiles_1d[0].electrons.density[0] could not be read"
    print "----> Aborted."
    exit()

main_species = table_mendeleiev[z][a].name

workflow = "???? (example: METIS)"
type = "???? (example: predictive)"

# Set up the name of the yaml file
strsize = len(str(shot))+len(str(run))
if strsize < 8:
    add0 = ""
    for i in range(8-strsize):
        if len(add0) < 3:
            add0 = add0+"0"
filename = "ids_"+str(shot)+add0+str(run)+".yaml"

# Go for it: fill the yaml file
f = open(filename, 'w')
f.write("""# ---------------------------------------------------------------\n""")
f.write("""# Shot number, run numbers, type, code, machine attributes\n""")
f.write("""# Type: interpretative, predictive, experiment\n""")
f.write("""# Code: code name in case of simulation, 0 in case of experiment\n""")
f.write("""# Machine: tokamak name\n""")
f.write("""# ---------------------------------------------------------------\n""")
f.write("""characteristics:\n""")
f.write("""    shot: %i\n""" % shot)
f.write("""    run: %i\n""" % run)
f.write("""    type: %s\n""" % type)
f.write("""    workflow: %s\n""" % workflow)
f.write("""    machine: %s\n""" % tokamakname)
f.write("""\n""")
f.write("""# --------------------------------------------------\n""")
f.write("""# Machine description or specific configuration\n""")
f.write("""# (scenario keys can be completed here if relevant)\n""")
f.write("""# Units are SI\n""")
f.write("""# --------------------------------------------------\n""")
f.write("""scenario_key_parameters:\n""")
f.write("""    magnetic_field: %.2f\n""" % magnetic_field)
f.write("""    main_species: %s\n""" % main_species)
f.write("""    plasma_current: %.2f \n""" % plasma_current)
f.write("""    line_averaged_density: %.2e\n""" % line_averaged_density)
f.write("""\n""")
f.write("""# --------------------\n""")
f.write("""# Content description\n""")
f.write("""# --------------------\n""")
f.write("""free_description: |\n""")
f.write("""    - Hydrogen plasma, H-mode\n""")
f.write("""    - Density:           ne = ??% nGW, peaking adjusted to fit with QuaLiKiz NN\n""")
f.write("""    - Auxiliary heating: ?? MW ECRH + ?? MW ICRH = ?? MW\n""")
f.write("""    - Confinement:       ITERL-96P(th) + ITERH-98P(y,2)\n""")
f.write("""    - Pedestal:          min [ITPA McDonald NF2007 , K(W_H-mode-W_L-mode)]\n""")
f.write("""    - L-H transition:    Martin 2008 + Behn PPCF 2015\n""")
f.write("""    - Impurities:        Zeff=?? in H, Zeff=?? in He, with Be and W impurities.\n""")
f.write("""\n""")
f.write("""# ---------------------------------------------------------------------------\n""")
f.write("""# List of filled IDSs with time quantities in seconds (start, end, step)\n""")
f.write("""# It should be the ouptut of the "create_ids_content" script, adapted from\n""")
f.write("""# listidss, see IMAS-1010 (note: the datafile has to be copied to a personal\n""")
f.write("""# database for the script to work, see the example below):\n""")
f.write("""#  create_ids_content -u schneim -t test -v 3 4321,1\n""")
f.write("""# ---------------------------------------------------------------------------\n""")
f.write("""idslist:\n""")
f.close()

# Complete the yaml file with the output of create_ids_content
system('./create_ids_content -u ' + str(user) + ' -t ' + str(tokamakname) \
          + ' -s ' + str(shot) + ' -r ' + str(run) + ' >> ' + filename)

print "----> " + filename + " created."

