#!/usr/bin/env python

import argparse

# ----------------------------------------------------------------------

# Management of input arguments
parser = argparse.ArgumentParser(description=\
	 '---- List ids content for yaml files aimed at describing a scenario ----')
parser.add_argument('-u','--user',help='username of the DB where the datafile is located', required=True)
parser.add_argument('-t','--tokamakname',help='tokamak name of the DB where the datafile is located', required=True)
parser.add_argument('-s','--shot',help='shot number', required=True,type=int)
parser.add_argument('-r','--run',help='run number',required=True,type=int)
args = vars(parser.parse_args())

shot = args["shot"]
run  = args["run"]
user = args["user"]
tokamakname = args["tokamakname"]

# Avoid too many arguments to be filled by the user (otherwise it is not user-friendly anymore)
dataversion = '3'
hdf5 = False
debug = False

try:
	import idstools.ids_tools as opendb
	db = opendb.ImasDb(shot,run,user,tokamakname,dataversion,True,False)
except:
	import sys
	print >> sys.stderr, "Unable to open database"
	print sys.exc_info()[0]
	sys.exit(1)
	
alltimes = db.all_times()

for idsname, times in alltimes:
	print("  "+idsname+":")
	print("     time_step_number: " + str(len(times)))
	print("     start_end_step:   [" + str(times[0]) + "  " \
	+  str(times[len(times)-1]) + "  " +  str((times[len(times)-1]-times[0])/len(times)) + "]")

