#!/usr/bin/env python

import argparse
from imas import ids

# ----------------------------------------------------------------------

# Management of input arguments
parser = argparse.ArgumentParser(description=\
	 '---- List ids content for yaml files aimed at describing a scenario ----')
parser.add_argument('-u','--user',help='username of the DB where the datafile is located', required=False)
parser.add_argument('-t','--machine',help='tokamak name of the DB where the datafile is located', required=False)
parser.add_argument('-s','--shot',help='shot number', required=True,type=int)
parser.add_argument('-r','--run',help='run number',required=True,type=int)
args = vars(parser.parse_args())

shot = args["shot"]
run  = args["run"]

# Username
if args['user'] != None:
	user = args["user"]
else:
	user = 'public'

# Tokamak name
if args['machine'] != None:
	machine = args["machine"]
else:
	machine = 'iterdb'

# Avoid too many arguments to be filled by the user (otherwise it is not user-friendly anymore)
dataversion = '3'
hdf5 = False
debug = False

try:
        import idstools.ids_tools as opendb
        db = opendb.ImasDb(shot,run,user,machine,dataversion,True,False)
except:
        import sys
        print("%s: %s"%(sys.exc_info()[0],sys.exc_info()[1]), file=sys.stderr)
        sys.exit("Unable to open database")

alltimes = db.all_times()
timed_idslist = []
for idsname, times in alltimes:
   timed_idslist.append(idsname)

# Open the file to check IDSs for which no time is defined
idss=ids(shot,run,0,0)
idss.open_env(user,machine,'3')

# Set up the list of existing IDSs in th DD
dd_idslist=[]
for element in idss.__dict__.keys():
   if hasattr(idss.__dict__.get(element),'ids_properties'):
      dd_idslist.append(element)

# List of IDSs actually filled in the file but non-timed
non_timed_idslist=[]
for element in dd_idslist:
   if not element in timed_idslist:
      if hasattr(eval('idss.'+element),'partialGet'):
         if eval('idss.'+element+'.partialGet(\'ids_properties/homogeneous_time\')') != -999999999:
            non_timed_idslist.append(element)
      else:
         eval('idss.'+element+'.get()')
         if eval('idss.'+element+'.ids_properties.homogeneous_time') != -999999999:
            non_timed_idslist.append(element)

for idsname, times in alltimes:
   if len(times) > 1:
      time_step  = (times[len(times)-1]-times[0])/(len(times)-1)
      start_time = times[0]
      end_time   = times[len(times)-1]
      print("  "+idsname+":")
      print("     time_step_number: " + str(len(times)))
      print("     start_end_step:   [" + str(start_time) + "  " +  str(end_time) + "  " +  str(time_step) + "]")
   else: # Only one time slice
      print("  "+idsname+":")
      print("     time_step_number: " + str(len(times)))
      print("     time:             [" + str(times[0]) + "]")

for idsname in non_timed_idslist:
   print("  "+idsname+":")
   print("     non-timed")

