#!/usr/bin/env python

import imas,os,argparse

# Management of input arguments
parser = argparse.ArgumentParser(description=\
	 '---- To copy an IDS from a datafile to another one ----')
parser.add_argument('-si','--shot_input',help='Input shot number', required=True,type=int)
parser.add_argument('-ri','--run_input',help='Input run number', required=True,type=int)
parser.add_argument('-so','--shot_output',help='Output shot number', required=True,type=int)
parser.add_argument('-ro','--run_output',help='Output run number', required=True,type=int)
parser.add_argument('-u','--user',help='username of the DB where the datafile is located', required=False)
parser.add_argument('-t','--machine',help='tokamak name of the DB where the datafile is located', required=False)
parser.add_argument('-ids','--ids',help='IDS to copy', required=True)

args = vars(parser.parse_args())

# putnow -si 7897 -ri 32 -so 7897 -ro 31 -u schneim -t iter -ids equilibrium

shot_in  = args["shot_input"]
run_in   = args["run_input"]
shot_out = args["shot_output"]
run_out  = args["run_output"]
ids      = args["ids"]

# Username
if args['user'] != None:
    user = args["user"]
else:
    user = os.getenv('USER')

# Tokamak name
if args['machine'] != None:
    machine = args["machine"]
else:
    machine = 'iter'

#shot_in  = 7897
#run_in   = 32
#shot_out = 7897
#run_out  = 31
#user = os.getenv('USER')
#tokamak = 'iter'
version = os.getenv('IMAS_VERSION')[0]

# OPEN INPUT
input = imas.ids(shot_in,run_in,0,0)
input.open_env(user,machine,'3')
idx_in = eval('input.'+ids+'.idx')

# GET IDS FROM INPUT
eval('input.'+ids+'.get()');

# OPEN OUTPUT
output = imas.ids(shot_out,run_out,0,0)
output.open_env(user,machine,'3')
idx_out = eval('output.'+ids+'.idx')

# COPY IDS FROM INPUT TO OUTPUT
exec('output.'+ids+' = input.'+ids)
eval('output.'+ids+'.setExpIdx(idx_out)')

# PUT IDS INTO OUTPUT
eval('output.'+ids+'.put()')

# CLOSE FILES
input.close()
output.close()

