#!/usr/bin/env python

import os, sys, glob, yaml, argparse
from operator import itemgetter
from stat import *

# ----------------------------------------------------------------------

class SmartFormatter(argparse.HelpFormatter):

    def _split_lines(self, text, width):
        if text.startswith('R|'):
            return text[2:].splitlines()  
        # this is the RawTextHelpFormatter._split_lines
        return argparse.HelpFormatter._split_lines(self, text, width)

# ----------------------------------------------------------------------

def rec(data={},path=os.getcwd(),extension='.yaml',choice=['shot','run','plasma_current','magnetic_field']):

  table = {}
  plus  = {}

  files = glob.glob(path + "/*")

  # Fill data dictionary with yaml input files describing simulations
  j = -1
  for i in range(len(files)):
    name = files[i]
    # Recursivity on sub-folders
    if os.path.isdir(files[i]):
      rec(data=data,path=files[i],extension=extension,choice=choice)
    # Work on all YAML files
    elif files[i].endswith(extension):
      try:
        j = j + 1
        if len(data) == 0:
            print "-----------------------------"
            print "Location of simulation files:"
            print "-----------------------------"
        file = open(files[i], 'r')
        print " " + files[i]
        data[j] = yaml.load(file)
        file.close()
      except yaml.YAMLError as exc:
        print(exc)

    # Sort data as a function of run numbers
    sorted_indices = sorted(data, key = lambda x: data[x]['characteristics']['run'])
    sdata = {}
    for i in range(len(data)):
      sdata[i] = data[sorted_indices[i]]

    # Names to be displayed
    disp_shot                  = 'Shot'
    disp_run                   = 'Run'
    disp_type                  = 'Type'
    disp_workflow              = 'Workflow'
    disp_machine               = 'Machine'
    disp_plasma_current        = 'Ip(MA)'
    disp_magnetic_field        = 'B0(T)'
    disp_main_species          = 'Species'
    disp_line_averaged_density = 'ne0(m-3)'
    disp_free_description      = 'Extra information'
    disp_idslist               = 'List of IDSs'
    disp_free_description      = 'Free description'
      
    # Identify optimized taubulation for each colum
    tab_shot                  = 0
    tab_run                   = 0
    tab_type                  = 0
    tab_workflow              = 0
    tab_machine               = 0
    tab_plasma_current        = 0
    tab_magnetic_field        = 0
    tab_main_species          = 0
    tab_line_averaged_density = 0
    tab_free_description      = 0
    tab_idslist               = 0
    for i in range(len(sdata)):
        tab_shot                  = max(max(len(str(sdata[i].get('characteristics').get('shot'))),tab_shot),len(disp_shot))
        tab_run                   = max(max(len(str(sdata[i].get('characteristics').get('run'))),tab_run),len(disp_run))
        tab_type                  = max(max(len(str(sdata[i].get('characteristics').get('type'))),tab_type),len(disp_type))
        tab_workflow              = max(max(len(str(sdata[i].get('characteristics').get('workflow'))),tab_workflow),len(disp_workflow))
        tab_machine               = max(max(len(str(sdata[i].get('characteristics').get('machine'))),tab_machine),len(disp_machine))
        tab_plasma_current        = max(max(len(str(sdata[i].get('scenario_key_parameters').get('plasma_current'))),tab_plasma_current),len(disp_plasma_current))
        tab_magnetic_field        = max(max(len(str(sdata[i].get('scenario_key_parameters').get('magnetic_field'))),tab_magnetic_field),len(disp_magnetic_field))
        tab_main_species          = max(max(len(str(sdata[i].get('scenario_key_parameters').get('main_species'))),tab_main_species),len(disp_main_species))
        tab_line_averaged_density = max(max(len(str(sdata[i].get('scenario_key_parameters').get('line_averaged_density'))),tab_line_averaged_density),len(disp_line_averaged_density))
        tab_free_description      = max(max(len(str(sdata[i].get('free_description'))),tab_free_description),len(disp_free_description))
        tab_idslist               = max(max(len(str(sdata[i].get('idslist'))),tab_idslist),len(disp_idslist))
    
    # Table heading
    table = {}
    table[1] = str(choice[0])
    for i in range(1,len(choice)):
      space_length = eval('tab_'+str(choice[i-1])) - len(eval('disp_'+str(choice[i-1])))+2
      table[1] = table[1] + " "*space_length + eval('disp_'+str(choice[i]))
    dimline = len(table[1])

    # Extra variables
    plus = {}
    for i in range(3):
      plus[i] = " "

    # Fill the table
    j = 2
    for i in range(len(sdata)):
      j = j+1

      shot                  = sdata[i].get('characteristics').get('shot')
      run                   = sdata[i].get('characteristics').get('run')
      type                  = sdata[i].get('characteristics').get('type')
      workflow              = sdata[i].get('characteristics').get('workflow')
      machine               = sdata[i].get('characteristics').get('machine')
      plasma_current        = sdata[i].get('scenario_key_parameters').get('plasma_current')
      magnetic_field        = sdata[i].get('scenario_key_parameters').get('magnetic_field')
      main_species          = sdata[i].get('scenario_key_parameters').get('main_species')
      line_averaged_density = sdata[i].get('scenario_key_parameters').get('line_averaged_density')
      free_description      = sdata[i].get('free_description')
      idslist               = sdata[i].get('idslist')
        
      # Compute the list of IDSs to be displayed
      idslist_nice = str()
      i=0
      for k,v in idslist.iteritems():
        i=i+1
        idslist_nice = idslist_nice + str(k) + " "
      idslist = idslist_nice

      # Content of the table
      table[j]=str(eval(choice[0]))
      for i in range(1,len(choice)):
        space_length = eval('tab_'+str(choice[i-1]))-len(str(eval(choice[i-1])))+2
        table[j] = table[j] + " "*space_length + str(eval(choice[i]))
        if len(table[j]) > dimline:
            dimline = len(table[j])
      plus[j] = free_description

    # Seperation lines
    for iline in 0,2,j+1:
        table[iline] = "-"*(dimline+1)

  return table, plus

# ----------------------------------------------------------------------

# Input arguments
parser = argparse.ArgumentParser(description='---- Script to list available scenarios in a specific folder ----',\
                                 formatter_class=SmartFormatter)
parser.add_argument('-f','--folder',help='folder where to search for scenarios (recursive)', required=False)
parser.add_argument('-c','--choice', help=\
                    "R|list of variables to display, e.g.: " "\"'shot','run','plasma_current','magnetic_field'\"\n"\
                    "... available among following variables:\n"\
                    "        'shot', 'run', 'type', 'workflow', 'machine',\n"\
                    "        'plasma_current', 'magnetic_field', 'main_species',\n" \
                    "        'line_averaged_density', 'idslist'", required=False)
args = vars(parser.parse_args())

# Folder
if args['folder'] != None:
  folder = args['folder']
else:
  folder = '/work/imas/shared/scenarios/'
  #folder = os.getcwd()

# Choice of variables to display
if args['choice'] != None:
    try:
        choice = eval(str(args['choice']))
    except:
        print "------------------------------------------------------------------"
        print "Wrong way to write your list of variables to display"
        print "You wrote "+str(args['choice'])
        print "Try e.g. this way: "+ """ scenario_summary -c "'shot','run','workflow'" """
        print "------------------------------------------------------------------"
        sys.exit(0)
else:
  choice = ['shot','run','plasma_current','magnetic_field','main_species','line_averaged_density']

# Default extension, search folder and choice of variables to display
data   = {}
ext    = ".yaml"

# Call the function
[table,plus] = rec(data=data,path=folder,extension=ext,choice=choice)

# Display the clean formatted table
for i in range(len(table)):
  print table[i]
  
# [/work/imas/shared/scenarios]$ scenario_summary -f /work/imas/shared/scenarios/metis/3/0/ -c "'shot','run'"
