#!/usr/bin/env python

import os, argparse, yaml

# Management of input arguments
parser = argparse.ArgumentParser(description=\
	 '---- Show full description file for a given simulation stored in ITER DB folder')
parser.add_argument('-s','--shot',help='shot number', required=True,type=int)
parser.add_argument('-r','--run',help='run number',required=True,type=int)
args = vars(parser.parse_args())
shot = args["shot"]
run  = args["run"]

# ------------------------------------------------------------------------------------------------------------

# Set up the name of the yaml file
strsize = len(str(shot))+len(str(run))
if strsize < 8:
    add0 = ""
    for i in range(8-strsize):
        if len(add0) < 3:
            add0 = add0+"0"
filename = "ids_"+str(shot)+add0+str(run)+".yaml"

folder = '/work/imas/shared/iterdb'

os.system('cat '+folder+'/3/0/'+filename)

