#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
import sys
import textwrap

import imas
import numpy as np

root_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(root_path)
from idstools.database import DBMaster
from idstools.utils.idshelper import getAvailableIdsAndTimes
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module")

TAB = " " * 3
SHOT_STR_LEN = 6
RUN_STR_LEN = 5
DATABASE_STR_LEN = 12
VERSION_STR_LEN = 6
IDSNAME_STR_LEN = 26
SLICENUM_STR_LEN = 4
RUNNUM_STR_LEN = 4
TIME_STR_LEN = 4


def extended(str, wlen):
    return f"{str:>{wlen}s}"


def printVector(vec, wlen):
    return " ".join([f"{str(x):>{wlen}s}" for x in vec])


def print_list(dbs, shotnum=None, compact=False, timestamp=False):
    for dbname, dvs in dbs:
        printed_database = False
        for dv, dbbackends in dvs:
            printed_dataversion = False
            for backend, dbs in dbbackends:
                printed_backend = False
                for shot, runs in sorted(dbs.items()):
                    if shotnum is not None:
                        # if a shotnum is given, only display databases with this shot number
                        if shot != shotnum:
                            continue

                    if not printed_database:
                        print(f"Database: {dbname}")
                        printed_database = True
                    if not printed_dataversion:
                        print(f"{TAB}Data version: {dv}")
                        printed_dataversion = True
                    if not printed_backend:
                        print(TAB * 2 + "UAL Backend: " + backend)
                        printed_backend = True
                    if compact:
                        print(
                            TAB * 3
                            + "Shot "
                            + extended(str(shot), SHOT_STR_LEN)
                            + ": "
                            + extended(str(len(sorted(runs))), RUNNUM_STR_LEN)
                            + " runs"
                        )

                    elif timestamp:
                        print(TAB * 3 + "Shot " + extended(str(shot), SHOT_STR_LEN))
                        runs.sort(reverse=True, key=lambda x: x[1])
                        for r in runs:
                            print(
                                TAB * 3
                                + " " * (5 + SHOT_STR_LEN)
                                + " Runs: "
                                + extended(str(r[1]), RUN_STR_LEN)
                                + " ("
                                + str(r[7])
                                + ")"
                            )
                    else:
                        print(
                            TAB * 3
                            + "Shot "
                            + extended(str(shot), SHOT_STR_LEN)
                            + " Runs: "
                            + printVector(sorted([r[1] for r in runs]), RUN_STR_LEN)
                        )


def printTimes(dbs, args, print_times=False, shotNumber=None, runNumber=None):
    for dbname, dvs in dbs:
        printed_database = False
        for dv, dbbackends in dvs:
            printed_dataversion = False
            for backend, dbs in dbbackends:
                printed_backend = False
                for shot, runs in sorted(dbs.items()):
                    # If a shotnum and/or runnum is given, only display these
                    if shotNumber is not None:
                        if shot != shotNumber:
                            continue

                    printed_shot = False
                    justruns = [r[1] for r in runs]
                    for run in justruns:
                        if runNumber is not None:
                            if run != runNumber:
                                continue

                        if not printed_database:
                            print(f"Database: {dbname}")
                            printed_database = True
                        if not printed_dataversion:
                            print(f"{TAB}Data version: {dv}")
                            printed_dataversion = True
                        if not printed_backend:
                            print(TAB * 2 + "UAL Backend: " + backend)
                            printed_backend = True
                        if not printed_shot:
                            print(TAB * 3 + "Shot " + extended(str(shot), SHOT_STR_LEN))
                            printed_shot = True

                        print(TAB * 4 + " Run: " + extended(str(run), RUN_STR_LEN))
                        idsObject = imas.ids(
                            shot,
                            run,
                        )
                        err, _ = idsObject.open_env(args.user, dbname, dv)
                        if err != 0:
                            logger.critical(
                                f"Shot {shot}, run {run} for user {args.user} and database {dbname} is not reachable ----> abort!",
                            )
                            sys.exit(err)

                        availableIdsAndTimes = getAvailableIdsAndTimes(idsObject)
                        for idsname, times in availableIdsAndTimes:
                            if len(times) == 1 and np.isnan(times[0]):
                                print(
                                    TAB * 5
                                    + extended(idsname, IDSNAME_STR_LEN)
                                    + ": "
                                    + extended("?", SLICENUM_STR_LEN)
                                    + " slices ( "
                                    + "heterogeneous IDS )"
                                )
                            elif len(times) == 1 and times[0] == np.NINF:
                                print(
                                    TAB * 5
                                    + extended(idsname, IDSNAME_STR_LEN)
                                    + ": "
                                    + extended("?", SLICENUM_STR_LEN)
                                    + " slices ( "
                                    + "time independent IDS )"
                                )
                            elif print_times:
                                print(
                                    TAB * 5
                                    + extended(idsname, IDSNAME_STR_LEN)
                                    + ": "
                                    + extended(str(len(times)), SLICENUM_STR_LEN)
                                    + " slices ("
                                    + printVector(times, TIME_STR_LEN)
                                    + ")"
                                )
                            else:
                                print(
                                    TAB * 5
                                    + extended(idsname, IDSNAME_STR_LEN)
                                    + ": "
                                    + extended(str(len(times)), SLICENUM_STR_LEN)
                                    + " slices ("
                                    + extended(str(times[0]), TIME_STR_LEN)
                                    + " - "
                                    + extended(str(times[-1]), TIME_STR_LEN)
                                    + ")"
                                )

                        idsObject.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="dblist",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=textwrap.dedent(
            """
                [Previously known as imasdbs]
                This program lists existing IMAS databases.

                Possible commands are:
                list <shot number>- list existing databases
                slices <shot number> <run number> - list existing databases, including number of timeslices and time range for time-dependent IDSs
                times <shot number> <run number> - list existing databases, including number of timeslices their time points for time-dependent IDSs
                databases - list existing databases (with data versions)
                dataversions - list existing dataversions (with databases)

                If the optional arguments shot number and run number are given, only databases with these numbers will be shown.

                If no command is given, the list command is performed.

                To see databases stored in the public imas database, use 'public' as the user name."""
        ),
    )
    subparsers = parser.add_subparsers(help="sub-commands help")

    subparserList = subparsers.add_parser("list", help="list databases")
    subparserList.set_defaults(cmd="list")
    subparserList.add_argument(
        "-c",
        "--compact",
        action="store_true",
        dest="compact",
        default=False,
        help="Compact/reduced output",
    )
    subparserList.add_argument(
        "-M",
        "--lastModifiedDate",
        action="store_true",
        dest="timestamp",
        default=False,
        help="Show (and sort per) date of last modification of the runs",
    )
    subparserList.add_argument("shot", nargs="?", help="Shot number", type=int)

    subparserSlices = subparsers.add_parser("slices", help="list slices")
    subparserSlices.set_defaults(cmd="slices")
    subparserSlices.add_argument("shot", nargs="?", help="Shot number", type=int)
    subparserSlices.add_argument("run", nargs="?", help="Run number", type=int)

    subparserTimes = subparsers.add_parser("times", help="list times")
    subparserTimes.set_defaults(cmd="times")
    subparserTimes.add_argument("shot", nargs="?", help="Shot number", type=int)
    subparserTimes.add_argument("run", nargs="?", help="Run number", type=int)

    subparserDatabases = subparsers.add_parser("databases", help="print databases")
    subparserDatabases.set_defaults(cmd="databases")

    subparserDataVersions = subparsers.add_parser(
        "dataversions", help="print data versions"
    )
    subparserDataVersions.set_defaults(cmd="dataversions")

    parser.add_argument(
        "-u",
        "--user",
        dest="user",
        default="public",  # os.getenv("USER"),
        help="Show databases of specified user \t\t(default=%(default)s)",
    )
    parser.add_argument(
        "-d",
        "--database",
        dest="database",
        default=None,
        help="Show only databases with specified name \t(default=%(default)s)",
    )
    parser.add_argument(
        "-v",
        "--version",
        dest="version",
        default=None,
        help="Show only databases for specified major data version \t(default=%(default)s)",
    )
    parser.add_argument(
        "--backend",
        dest="backend",
        default=None,
        help="Show databases written with given backend(s). \n\
    Comma-separated list of backends (Currently supported: mdsplus, hdf5). By default all backends are shown. \t(default=%(default)s)",
    )

    parser.add_argument("positionalArgs", nargs="?", default=os.getcwd())

    args = parser.parse_args()
    try:
        if args.cmd is None:
            parser.print_help()
            exit(1)
    except AttributeError:
        parser.print_help()
        exit(1)

    backends = args.backend.split(",") if args.backend else None
    dbs = DBMaster.getDatabaseFiles(args.user, args.database, args.version, backends)
    if args.cmd == "list":
        print_list(dbs, args.shot, args.compact, args.timestamp)

    if args.cmd == "slices":
        printTimes(
            dbs, args, print_times=False, shotNumber=args.shot, runNumber=args.run
        )

    if args.cmd == "times":
        printTimes(
            dbs, args, print_times=True, shotNumber=args.shot, runNumber=args.run
        )

    if args.cmd == "databases":
        databasesWithVersions = DBMaster.getDatabasesWithVersions(args.user)
        if args.version is not None:
            databasesWithVersions = filter(
                lambda x: (args.version in x[1]), databasesWithVersions
            )
        for databaseName, versions in databasesWithVersions:
            print(
                extended(databaseName, DATABASE_STR_LEN)
                + " "
                + printVector(versions, VERSION_STR_LEN)
            )

    if args.cmd == "dataversions":
        for version, databaseNames in DBMaster.getVersionsWithDatabases(args.user):
            print(
                f"{extended(version, VERSION_STR_LEN)} {printVector(databaseNames, DATABASE_STR_LEN)}"
            )
