#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os

import numpy as np
from rich.console import Console
from rich.markdown import Markdown
from rich.table import Table
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.utils.idshelper import getAvailableIdsAndTimes
from idstools.utils.idslogger import setupLogger

logger = setup_logger("module")

t_a_b = " " * 3
s_h_o_t__s_t_r__l_e_n = 6
r_u_n__s_t_r__l_e_n = 5
d_a_t_a_b_a_s_e__s_t_r__l_e_n = 12
v_e_r_s_i_o_n__s_t_r__l_e_n = 6
i_d_s_n_a_m_e__s_t_r__l_e_n = 26
s_l_i_c_e_n_u_m__s_t_r__l_e_n = 4
r_u_n_n_u_m__s_t_r__l_e_n = 4
t_i_m_e__s_t_r__l_e_n = 4


def extended(str, wlen):
    return f"{str:>{wlen}s}"


def print_vector(vec, wlen):
    return " ".join([f"{str(x):>{wlen}s}" for x in vec])


def print_list(dbs, pulsenum=None, compact=False, timestamp=False):
    for dbname, dvs in dbs:
        printed_database = False
        for dv, dbbackends in dvs:
            printed_dataversion = False
            for backend, dbs in dbbackends:
                printed_backend = False
                for pulse, runs in sorted(dbs.items()):
                    if pulsenum is not None:
                        # if a pulsenum is given, only display databases with this pulse number
                        if pulse != pulsenum:
                            continue

                    if not printed_database:
                        print(f"Database: {dbname}")
                        printed_database = True
                    if not printed_dataversion:
                        print(f"{t_a_b}Data version: {dv}")
                        printed_dataversion = True
                    if not printed_backend:
                        print(t_a_b * 2 + "Backend: " + backend)
                        printed_backend = True
                    if compact:
                        print(
                            t_a_b * 3
                            + "Pulse "
                            + extended(str(pulse), s_h_o_t__s_t_r__l_e_n)
                            + ": "
                            + extended(str(len(sorted(runs))), r_u_n_n_u_m__s_t_r__l_e_n)
                            + " runs"
                        )

                    elif timestamp:
                        print(t_a_b * 3 + "Pulse " + extended(str(pulse), s_h_o_t__s_t_r__l_e_n))
                        runs.sort(reverse=True, key=lambda x: x[1])
                        for r in runs:
                            print(
                                t_a_b * 3
                                + " " * (5 + s_h_o_t__s_t_r__l_e_n)
                                + " Runs: "
                                + extended(str(r[1]), r_u_n__s_t_r__l_e_n)
                                + " ("
                                + str(r[7])
                                + ")"
                            )
                    else:
                        print(
                            t_a_b * 3
                            + "Pulse "
                            + extended(str(pulse), s_h_o_t__s_t_r__l_e_n)
                            + " Runs: "
                            + print_vector(sorted([r[1] for r in runs]), r_u_n__s_t_r__l_e_n)
                        )


def print_urilist(dbs, pulsenum=None, compact=False, timestamp=False):
    urichoice = ["Sr. No.", "uri"]
    if timestamp:
        urichoice.append("timestamp")
    table = table()
    for column_name in urichoice:
        if column_name == "timestamp":
            table.add_column(column_name, justify="left", style="red")
        elif column_name == "uri":
            table.add_column(column_name, justify="left", style="yellow")
        else:
            table.add_column(column_name, justify="left", style="green")
    counter = 0
    for dbname, dvs in dbs:
        for dv, dbbackends in dvs:
            for backend, dbs in dbbackends:
                for pulse, runs in sorted(dbs.items()):
                    if pulsenum is not None:
                        # if a pulsenum is given, only display databases with this pulse number
                        if pulse != pulsenum:
                            continue

                    for r in sorted(runs, key=lambda x: x[1]):
                        x = []
                        x.append(str(counter))
                        counter = counter + 1
                        x.append(
                            f'"imas:{backend.lower()}?user={args.user};pulse={pulse};run={r[1]};database={dbname};version={dv}"'
                        )
                        if timestamp:
                            x.append(str(r[7]))
                        table.add_row(*x)
    console = console()
    console.print(table)


def print_times(dbs, args, print_times=False, pulse_number=None, run_number=None, showuri=False):

    for dbname, dvs in dbs:
        printed_database = False
        for dv, dbbackends in dvs:
            printed_dataversion = False
            for backend, dbs in dbbackends:
                printed_backend = False
                for pulse, runs in sorted(dbs.items()):
                    # If a pulsenum and/or runnum is given, only display these
                    if pulse_number is not None:
                        if pulse != pulse_number:
                            continue

                    printed_pulse = False
                    justruns = [r[1] for r in runs]
                    justruns.sort()
                    for run in justruns:
                        if run_number is not None:
                            if run != run_number:
                                continue

                        if not printed_database:
                            print(f"Database: {dbname}")
                            printed_database = True
                        if not printed_dataversion:
                            print(f"{t_a_b}Data version: {dv}")
                            printed_dataversion = True
                        if not printed_backend:
                            print(t_a_b * 2 + "Backend: " + backend)
                            printed_backend = True
                        if not printed_pulse:
                            print(t_a_b * 3 + "Pulse " + extended(str(pulse), s_h_o_t__s_t_r__l_e_n))
                            printed_pulse = True

                        connargs = argparse.namespace()
                        connargs.backend = backend.upper()
                        connargs.pulse = pulse
                        connargs.run = run
                        connargs.user = args.user
                        connargs.database = dbname
                        connargs.version = dv
                        connargs.uri = f"imas:{backend.lower()}?user={args.user};pulse={pulse};run={run};database={dbname};version={dv}"

                        connection = DBMaster.get_connection(connargs)
                        if showuri:
                            print(t_a_b * 4 + '"' + connargs.uri + '"')
                        else:
                            print(t_a_b * 4 + " Run: " + extended(str(run), r_u_n__s_t_r__l_e_n))
                        available_ids_and_times = get_available_ids_and_times(connection)
                        for idsname, times in available_ids_and_times:
                            if len(times) == 1 and np.isnan(times[0]):
                                print(
                                    t_a_b * 5
                                    + extended(idsname, i_d_s_n_a_m_e__s_t_r__l_e_n)
                                    + ": "
                                    + extended("?", s_l_i_c_e_n_u_m__s_t_r__l_e_n)
                                    + " slices ( "
                                    + "heterogeneous IDS )"
                                )
                            elif len(times) == 1 and times[0] == np.NINF:
                                print(
                                    t_a_b * 5
                                    + extended(idsname, i_d_s_n_a_m_e__s_t_r__l_e_n)
                                    + ": "
                                    + extended("?", s_l_i_c_e_n_u_m__s_t_r__l_e_n)
                                    + " slices ( "
                                    + "time independent IDS )"
                                )
                            elif print_times:
                                print(
                                    t_a_b * 5
                                    + extended(idsname, i_d_s_n_a_m_e__s_t_r__l_e_n)
                                    + ": "
                                    + extended(str(len(times)), s_l_i_c_e_n_u_m__s_t_r__l_e_n)
                                    + " slices ("
                                    + print_vector(times, t_i_m_e__s_t_r__l_e_n)
                                    + ")"
                                )
                            else:
                                print(
                                    t_a_b * 5
                                    + extended(idsname, i_d_s_n_a_m_e__s_t_r__l_e_n)
                                    + ": "
                                    + extended(str(len(times)), s_l_i_c_e_n_u_m__s_t_r__l_e_n)
                                    + " slices ("
                                    + extended(str(times[0]), t_i_m_e__s_t_r__l_e_n)
                                    + " - "
                                    + extended(str(times[-1]), t_i_m_e__s_t_r__l_e_n)
                                    + ")"
                                )
                        print("\n")

                        connection.close()


description = """
This program lists existing IMAS databases.

Possible commands are:

- ``list <pulse number>``: list existing databases
- ``slices <pulse number> <run number>``: list existing databases, including number of timeslices and time range for time-dependent IDSs
- ``times <pulse number> <run number>``: list existing databases, including number of timeslices their time points for time-dependent IDSs
- ``databases``: list existing databases (with data versions)
- ``dataversions``: list existing dataversions (with databases)

If the optional arguments pulse number and run number are given, only databases with these numbers will be shown. If no command is given, the list command is performed. To see databases stored in the public imas database, use 'public' as the user name.

[Previously known as imasdbs]"""
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="dblist",
        formatter_class=rich_help_formatter,
        description=markdown(description, style="argparse.text"),
    )
    subparsers = parser.add_subparsers(help="sub-commands help")

    subparser_list = subparsers.add_parser("list", help="list databases")
    subparser_list.set_defaults(cmd="list")
    subparser_list.add_argument(
        "-c",
        "--compact",
        action="store_true",
        dest="compact",
        default=False,
        help="Compact/reduced output",
    )
    subparser_list.add_argument(
        "-M",
        "--lastModifiedDate",
        action="store_true",
        dest="timestamp",
        default=False,
        help="Show (and sort per) date of last modification of the runs",
    )
    subparser_list.add_argument("pulse", nargs="?", help="Pulse number", type=int)

    subparser_slices = subparsers.add_parser("slices", help="list slices")
    subparser_slices.set_defaults(cmd="slices")
    subparser_slices.add_argument("pulse", nargs="?", help="Pulse number", type=int)
    subparser_slices.add_argument("run", nargs="?", help="Run number", type=int)

    subparser_times = subparsers.add_parser("times", help="list times")
    subparser_times.set_defaults(cmd="times")
    subparser_times.add_argument("pulse", nargs="?", help="Pulse number", type=int)
    subparser_times.add_argument("run", nargs="?", help="Run number", type=int)

    subparser_databases = subparsers.add_parser("databases", help="print databases")
    subparser_databases.set_defaults(cmd="databases")

    subparser_data_versions = subparsers.add_parser("dataversions", help="print data versions")
    subparser_data_versions.set_defaults(cmd="dataversions")

    parser.add_argument(
        "-u",
        "--user",
        dest="user",
        default="public",  # os.getenv("USER"),
        help="Show databases of specified user \t\t(default=%(default)s)",
    )
    parser.add_argument(
        "-d",
        "--database",
        dest="database",
        default=None,
        help="Show only databases with specified name \t(default=%(default)s)",
    )
    parser.add_argument(
        "-v",
        "--version",
        dest="version",
        default=None,
        help="Show only databases for specified major data version \t(default=%(default)s)",
    )
    parser.add_argument(
        "--backend",
        dest="backend",
        default=None,
        help="Show databases written with given backend(s). \n\
    Comma-separated list of backends (Currently supported: mdsplus, hdf5). By default all backends are shown. \t(default=%(default)s)",
    )
    parser.add_argument(
        "-showuri",
        "--showuri",
        action="store_true",
        help="Show uri",
    )
    parser.add_argument("positionalArgs", nargs="?", default=os.getcwd())

    args = parser.parse_args()
    # Default command if not provided
    if "cmd" not in args.__dict__:
        backends = args.backend.split(",") if args.backend else None
        dbs = DBMaster.get_database_files(args.user, args.database, args.version, backends)
        print_list(dbs)
        exit(0)

    backends = args.backend.split(",") if args.backend else None
    dbs = DBMaster.get_database_files(args.user, args.database, args.version, backends)
    if args.cmd == "list":

        if args.showuri:
            print_urilist(dbs, args.pulse, args.compact, args.timestamp)
        else:
            print_list(dbs, args.pulse, args.compact, args.timestamp)

    if args.cmd == "slices":
        print_times(
            dbs,
            args,
            print_times=False,
            pulse_number=args.pulse,
            run_number=args.run,
            showuri=args.showuri,
        )

    if args.cmd == "times":
        print_times(
            dbs,
            args,
            print_times=True,
            pulse_number=args.pulse,
            run_number=args.run,
            showuri=args.showuri,
        )

    if args.cmd == "databases":
        databases_with_versions = DBMaster.get_databases_with_versions(args.user)
        if args.version is not None:
            databases_with_versions = filter(lambda x: (args.version in x[1]), databases_with_versions)
        for database_name, versions in databases_with_versions:
            print(
                extended(database_name, d_a_t_a_b_a_s_e__s_t_r__l_e_n)
                + " "
                + print_vector(versions, v_e_r_s_i_o_n__s_t_r__l_e_n)
            )

    if args.cmd == "dataversions":
        for version, database_names in DBMaster.get_versions_with_databases(args.user):
            print(
                f"{extended(version, v_e_r_s_i_o_n__s_t_r__l_e_n)} {print_vector(database_names, d_a_t_a_b_a_s_e__s_t_r__l_e_n)}"
            )
