#!/usr/bin/env python3
# Return values of an IDS in all data entries of a database

import argparse
import os
import sys
from pathlib import Path

import pandas as pd
from imas import imasdef

root_path = os.path.dirname(os.path.dirname(__file__))
sys.path.append(root_path)
from idstools.utils.clihelper import getBackendID, imasParser
from idstools.database import DBMaster
from idstools.utils.idshelper import getQuantitiesFromPulses

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Extracts given quantities from all data entries of a given database",
        parents=[imasParser],
    )
    parser.add_argument(
        "idspath",
        type=str,  # nargs="*", #multiple paths not yet implemented
        help="IDS path (starting with IDS name) to the desired data to be collected, e.g equilibrium/time",
    )
    parser.add_argument(
        "--saveas",
        type=str,
        help="File in which to store the results of this query, in csv format",
    )
    parser.add_argument(
        "--status",
        type=str,
        help="Will list only data entries with specified status (if such metadata is available)",
    )
    parser.add_argument(
        "--list-count",
        type=int,
        help="number of entries user needs to display",
    )
    parser.add_argument("--verbose", action="store_true", help="Verbose mode")
    args = parser.parse_args()

    backend = getBackendID(args.backend)
    dbmaster = DBMaster()
    pulses = None
    if backend == imasdef.MDSPLUS_BACKEND:
        pulses = dbmaster.getMdsPlusPulses(
            args.user, args.database, args.version, status=args.status
        )
    elif backend == imasdef.HDF5_BACKEND:
        pulses = dbmaster.getHdf5Pulses(args.user, args.database, args.version)
    else:
        print(f"Functionality not yet implemented for backend {args.backend}")
        sys.exit()

    if args.verbose:
        print(pulses)

    if pulses is not None:
        df = getQuantitiesFromPulses(args.idspath, tuple(pulses), args.list_count, True)
        if args.saveas:
            if not Path(args.saveas).parent.exists():
                raise FileNotFoundError(
                    "The path provided does not exist or has no such database file or directory. Please check spelling."
                )
            df.to_csv(args.saveas, na_rep="None", index=True, header=True)
        else:
            print(df.to_markdown())
