#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
import sys
import copy

from rich_argparse import RichHelpFormatter
import imas
from rich.progress import track

from idstools.database import DBMaster
from idstools.utils.clihelper import getBackendID, imasParser
from idstools.utils.idshelper import getAvailableIdsAndOccurrences

if __name__ == "__main__":
    parser = argparse.argument_parser(
        description="Check if specified ids is exists in the scenario database and returns shot and pulse",
        parents=[imas_parser],
        formatter_class=rich_help_formatter,
    )
    parser.add_argument(
        "ids",
        type=str,
        default=None,
        help="Name of the comma separated IDSes to check if it is available in scenario",
    )
    parser.add_argument("--verbose", action="store_true", help="Verbose mode")
    parser.add_argument(
        "--status",
        type=str,
        help="Will list only data entries with specified status (if such metadata is available)",
    )
    parser.add_argument(
        "--list-count",
        type=int,
        default=0,
        help="Number of entries user needs to display",
    )
    args = parser.parse_args()
    idsesto_search = args.ids.split(",")
    backend = get_backend_i_d(args.backend)
    dbmaster = DBMaster()
    if args.verbose:
        print(f"Database located in {dbmaster.get_database_dir(args.database,args.user)}")

    pulses = None
    if backend == imas.imasdef.m_d_s_p_l_u_s__b_a_c_k_e_n_d:
        pulses = dbmaster.get_mds_plus_pulses(args.user, args.database, args.version, status=args.status)
    elif backend == imas.imasdef.h_d_f5__b_a_c_k_e_n_d:
        pulses = dbmaster.get_hdf5_pulses(args.user, args.database, args.version)
    else:
        print(f"Functionality not yet implemented for backend {args.backend}")
        sys.exit()

    list_count = args.list_count
    if list_count != 0:
        pulses = pulses[:list_count]

    if pulses is not None:
        for pulse in track(pulses, description="[green]Analyzing DB..."):
            connargs = argparse.namespace()
            connargs.backend = args.backend
            connargs.pulse = pulse[0]
            connargs.run = pulse[1]
            connargs.user = args.user
            connargs.database = args.database
            connargs.version = args.version
            connargs.uri = f"imas:{args.backend.lower()}?user={args.user};shot={pulse[0]};run={pulse[1]};database={args.database};version={args.version}"
            connection = DBMaster.get_connection(connargs)
            if connection is None:
                continue

            ids_list = get_available_ids_and_occurrences(connection)
            found_counter = 0
            for ids_to_search in idsesto_search:
                if any(ids_to_search in ids for ids in ids_list):
                    found_counter = found_counter + 1

            if found_counter == len(idsesto_search):
                print((pulse[0], pulse[1]))
