#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
import sys
import copy

from rich_argparse import RichHelpFormatter
import imas
from rich.progress import track

from idstools.database import DBMaster
from idstools.utils.clihelper import getBackendID, getIMASVersion, imasParser
from idstools.utils.idshelper import getAvailableIdsAndOccurrences

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Check if specified ids is exists in the scenario database and returns shot and pulse",
        parents=[imasParser],
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "ids",
        type=str,
        default=None,
        help="Name of the comma separated IDSes to check if it is available in scenario",
    )
    parser.add_argument("--verbose", action="store_true", help="Verbose mode")
    parser.add_argument(
        "--status",
        type=str,
        help="Will list only data entries with specified status (if such metadata is available)",
    )
    parser.add_argument(
        "--list-count",
        type=int,
        default=0,
        help="Number of entries user needs to display",
    )
    args = parser.parse_args()
    idsestoSearch=args.ids.split(",")
    backend = getBackendID(args.backend)
    dbmaster = DBMaster()
    if args.verbose:
        print(f"Database located in {dbmaster.getDatabaseDir(args.database,args.user)}")

    pulses = None
    if backend == imas.imasdef.MDSPLUS_BACKEND:
        pulses = dbmaster.getMdsPlusPulses(
            args.user, args.database, args.version, status=args.status
        )
    elif backend == imas.imasdef.HDF5_BACKEND:
        pulses = dbmaster.getHdf5Pulses(args.user, args.database, args.version)
    else:
        print(f"Functionality not yet implemented for backend {args.backend}")
        sys.exit()

    listCount = args.list_count
    if listCount != 0:
        pulses = pulses[:listCount]

    if pulses is not None:
        for pulse in track(pulses, description="[green]Analyzing DB..."):
            connargs = argparse.Namespace()
            connargs.backend = args.backend
            connargs.pulse = pulse[0]
            connargs.run = pulse[1]
            connargs.user = args.user
            connargs.database = args.database
            connargs.version = args.version
            if getIMASVersion() > 4:
                connargs.uri = f"imas:{args.backend.lower()}?user={args.user};shot={pulse[0]};run={pulse[1]};database={args.database};version={args.version}"
            connection = DBMaster.getConnection(connargs)
            if connection is None:
                continue

            ids_list = getAvailableIdsAndOccurrences(connection)
            foundCounter=0
            for idsToSearch in idsestoSearch:
                if any(idsToSearch in ids for ids in ids_list):
                    foundCounter=foundCounter+1
                    
            if foundCounter == len(idsestoSearch):
                print((pulse[0], pulse[1]))
