#!/usr/bin/env python

from idstools.machinedescription import MachineDescription
import imas, os, sys, argparse, matplotlib, yaml
import numpy as np

matplotlib.use("TKagg")
from matplotlib import gridspec
import matplotlib.pyplot as plt

# from idstools.cli import *
import logging
from idstools.compute.common import getNearestTime
from idstools.utils.clihelper import getBackendID, getDatabasePath, imasParser
from idstools.utils.idslogger import setupLogger

# Example of call:
# ./ecray -s [130012,130012] -r [24,23] -u schneim -d iter


def find_nearest(a, a0):
    "Element in nd array `a` closest to the scalar value `a0`"
    idx = abs(a - a0).argmin()
    return a.flat[idx], idx


# HELPER FUNCTIONS
def StrToList(string):
    if string[0] == "[":
        slist = string.split(",")
        slist[0] = slist[0][1:]
        slist[-1] = slist[-1][:-1]
        slist = [int(slist[i]) for i in range(len(slist))]
        return slist
    else:
        return [int(string)]


# ARGPARSE - MANAGEMENT OF INPUT ARGUMENTS
parser = argparse.ArgumentParser(
    description="---- Display EC wave ray-tracing results", parents=[imasParser]
)
parser.add_argument(
    "-s", "--shot", help="Shot number list, ex: [130012,130013]", required=True
)
parser.add_argument(
    "-r", "--run", help="Run number list, ex: [23,24]", required=True, type=str
)
parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=-99.0
)
# parser.add_argument('-w','--wall',help='Wall display flag', required=False,type=int,default=0)

args = parser.parse_args()

logger = setupLogger("module", stdout_level=logging.INFO)

shotString, runString = args.shot, args.run
shotList, runList = StrToList(shotString), StrToList(runString)
assert len(shotList) <= len(
    runList
), "There must be a run number corresponding to each shot"
if len(runList) > len(shotList):
    assert (
        len(shotList) == 1
    ), "Either give a shot for each run or give a single shot for every run"
    shot = len(runList) * shotList

# Search for adequate time slice for display
connection = imas.DBEntry(
    getBackendID(args.backend), args.database, shotList[0], runList[0], args.user
)
err, n = connection.open()
if err != 0:
    logger.critical(
        f"Shot {str(args.shot)}, run {str(args.run)} for user_or_path = {args.user} and database = {args.database} does not exist",
    )
    logger.critical(
        "----> Aborted.",
    )
    exit(0)

idsWaves = connection.get("waves")
# ntime = len(idsWaves.time)
timeArray = idsWaves.time
# if ntime > 1:
#     if args.time >= 0:
#         [tc, it] = find_nearest(timevec, args.time)
#     else:
#         it = int(ntime / 2)
#         tc = timevec[it]
#     print(
#         "   Time  = "
#         + "%.2f" % tc
#         + " s in range ["
#         + "%.2f" % timevec[0]
#         + ","
#         + "%.2f" % timevec[ntime - 1]
#         + "] s",
#         file=sys.stderr,
#     )
#     print("   Index = ", str(it), file=sys.stderr)
#     print(
#         "   Averaged resolution = ",
#         (timevec[ntime - 1] - timevec[0]) / (ntime - 1),
#         " s",
#         file=sys.stderr,
#     )
# else:
#     if len(timevec) > 0:
#         tc = timevec[0]
#     else:
#         tc = 0
#     it = 0
timeValue = 3
timeIndex = 0
time = timeValue
# Search for adequate time slice for display
timeArray = idsWaves.time
ntime = len(idsWaves.time)
timeIndex, timeValue = getNearestTime(timeArray, args.time)

machineDescription = MachineDescription()
wallMDDict = machineDescription.getMDSummary("wall")


# Get wall of the tokamak
for pulse, config in wallMDDict.items():
    if "wall and divertor" in config["config"]["description"]:
        mdShot, mdRun = pulse.split("/")
        try:
            mdConnection = imas.DBEntry(
                getBackendID(args.backend), "ITER_MD", int(mdShot), int(mdRun), "public"
            )
            err, n = mdConnection.open()
            if err != 0:
                logger.error(
                    f"Shot {mdShot}, run {mdRun} for user={args.user} and database=ITER_MD does not exists"
                )
                raise Exception(
                    f"Shot {mdShot}, run {mdRun}  for user={args.user} and database=ITER_MD does not exists"
                )

            wallIds = mdConnection.get("wall")
            mdConnection.close()
            break
        except:
            continue
if wallIds is None:
    logger.error("wall ids is not present")


# ------------------------------------------------

# Font/Colour definition
fontsize = 9
bndcolor = "chocolate"
shotcolors = ["b", "r", "c", "y", "m", "b"]
shotstyle = ["-", "--", "-.", ":", ".", ","]
colorcounter = 0
lpad = -1

# Top View Setup
#  % --- (X,Y) contour of the inner plasma surface
#  % --- (X,Y) of the outer plasma surface

width2 = 12
height2 = 3
width_height_2 = (width2, height2)
plt.figure(figsize=width_height_2)

plt.rcParams["axes.grid"] = True
plt.rcParams["lines.linewidth"] = 1
plt.rcParams["xtick.major.pad"] = "1"

nrow = 1
ncol = 3

ax_polview = plt.subplot2grid((nrow, ncol), (0, 0), rowspan=1)
ax_polview.set_title("Poloidal view (R,Z)", fontsize=fontsize)
ax_polview.set_xlabel("R [m]", fontsize=fontsize, labelpad=lpad)
ax_polview.set_ylabel("Z [m]", fontsize=fontsize, labelpad=lpad)

ax_topview = plt.subplot2grid((nrow, ncol), (0, 1), rowspan=1)
ax_topview.set_title("Top View (X,Y)", fontsize=fontsize)
ax_topview.set_xlabel("X [m]", fontsize=fontsize, labelpad=lpad)
ax_topview.set_ylabel("Y [m]", fontsize=fontsize, labelpad=lpad)

ax_powview = plt.subplot2grid((nrow, ncol), (0, 2), rowspan=1)
ax_powview.set_title("Power along the beams", fontsize=fontsize)
ax_powview.set_xlabel("Path length [m]", fontsize=fontsize, labelpad=lpad)
ax_powview.set_ylabel("P$_{electrons}$ [MW]", fontsize=fontsize, labelpad=lpad)

extra = 0
if extra == 1:
    ax_powparview = plt.subplot2grid((nrow, ncol), (2, 1), rowspan=2)
    ax_powparview.set_ylabel(
        "P$_\parallel$/P$_{max}$ [-]", fontsize=fontsize, labelpad=lpad
    )
    ax_powperpview = plt.subplot2grid((nrow, ncol), (4, 1), rowspan=2)
    ax_powperpview.set_xlabel("Path length [m]", fontsize=fontsize, labelpad=lpad)
    ax_powperpview.set_ylabel(
        "P$_\perp$/P$_{max}$ [-]", fontsize=fontsize, labelpad=lpad
    )

# Looping over shots and runs
global_label = ""
for i in range(len(shotList)):
    ishot = shotList[i]
    irun = runList[i]

    # Color management
    color = shotcolors[colorcounter % len(shotcolors)]
    style = shotstyle[colorcounter % len(shotcolors)]
    colorcounter += 1
    print("------------------------------------------------------------")

    # Reading in data from run in shot
    print(
        f"Open pulse: {ishot}/{irun} in DB {args.user}/{args.database}/{args.version}"
    )
    result = imas.DBEntry(
        getBackendID(args.backend), args.database, ishot, irun, args.user
    )
    status, _ = result.open()
    if status != 0:
        print(
            f"Pulse {ishot}/{irun} in DB {args.user}/{args.database}/{args.version} does not exist",
            file=sys.stderr,
        )
        print("----> Aborted.", file=sys.stderr)
        sys.exit(status)

    # Reading in waves ids and equilibrium ids
    idsWaves = result.get_slice("waves", time, 1)
    idsEquilibrium = result.get_slice("equilibrium", time, 1)

    # ------------------------------------------------

    ec_frequency = idsWaves.coherent_wave[0].global_quantities[0].frequency

    n_harm = [1, 2, 3, 4]

    # B-field at the resonance for three first harmonics
    B_res = [0] * len(n_harm)
    for i_harm in range(len(n_harm)):
        B_res[i_harm] = 2 * np.pi * ec_frequency * 9.1e-31 / 1.6e-19 / n_harm[i_harm]

    # Find (R,Z) rectangular grid of B-field
    ieq_rect = -99
    for ieq in range(len(idsEquilibrium.time_slice[timeIndex].profiles_2d)):
        if idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq].grid_type.index == 1:
            ieq_rect = ieq

    if ieq_rect < 0:
        print("------------------------------------------------")
        print("No rectangular R,Z grid found in equilibrium IDS")
        print("--> Abort.")
        print("------------------------------------------------")
        sys.exit()

    r = idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].grid.dim1
    z = idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].grid.dim2
    b_tot = np.sqrt(
        idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].b_field_r ** 2
        + idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].b_field_z ** 2
        + idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].b_field_tor ** 2
    )

    [nr, nz] = np.shape(b_tot)
    b_err = 10 / nr

    res_layer = {}
    for i_harm in range(len(n_harm)):
        res_layer[i_harm] = {}
        res_layer[i_harm]["r"] = []
        res_layer[i_harm]["z"] = []
        for iz in range(nz):
            [rloc, ir] = find_nearest(b_tot[:, iz], B_res[i_harm])
            if np.abs(b_tot[ir, iz] - B_res[i_harm]) < b_err:
                res_layer[i_harm]["r"].append(r[ir])
                res_layer[i_harm]["z"].append(z[iz])

    # ------------------------------------------------

    if len(idsWaves.code.name) > 0:
        print("Code name = ", idsWaves.code.name.upper())

    # Reading in 2d structures
    r2d = np.array(idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].r)
    z2d = np.array(idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].z)
    psi2d = np.array(idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].psi)
    if len(idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].phi) > 0:
        rho2d = np.sqrt(
            idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].phi
            / np.amax(idsEquilibrium.time_slice[timeIndex].profiles_2d[ieq_rect].phi)
        )
    else:
        rho2d = []

    # Poloidal view plot
    cntrpsi = ax_polview.contour(r2d, z2d, psi2d, 50, cmap="summer")
    if len(rho2d) > 0:
        cntrrho = ax_polview.contour(r2d, z2d, rho2d, 50, cmap="YlOrBr")
    # ax_polview.set_xlim(r2d.min(),r2d.max())
    ax_polview.set_xlim(3.4, r2d.max())
    ax_polview.set_ylim(z2d.min() * 0.7, z2d.max() * 0.7)
    ax_polview.set_aspect("equal", adjustable="box")
    for i_harm in range(len(n_harm)):
        if len(res_layer[i_harm]["r"]) > 1:
            print("Resonance at n = %i" % i_harm)
            ax_polview.plot(
                res_layer[i_harm]["r"], res_layer[i_harm]["z"], color="r", linewidth=2
            )

    # Top view plot
    r0 = idsEquilibrium.time_slice[timeIndex].boundary.geometric_axis.r
    amin = idsEquilibrium.time_slice[timeIndex].boundary.minor_radius
    phit = np.linspace(0, 2 * np.pi, 100)
    xpla = (r0 - amin) * np.cos(phit)
    ypla = (r0 - amin) * np.sin(phit)
    xplap = (r0 + amin) * np.cos(phit)
    yplap = (r0 + amin) * np.sin(phit)
    if colorcounter == 1:
        ax_topview.plot(xpla, ypla, color=bndcolor, label="Plasma Boundaries")
    else:
        ax_topview.plot(xpla, ypla, color=bndcolor)
    ax_topview.plot(xplap, yplap, color=bndcolor)
    ax_topview.set_xlim((-r0 - amin) * 1.1, (r0 + amin) * 1.1)
    ax_topview.set_aspect("equal")

    # Looping over beams and rays
    nbeam = len(idsWaves.coherent_wave)

    # Count number of active beams and their number of rays
    is_active = [0] * nbeam
    nray_array = [0] * nbeam
    for ibeam in range(nbeam):
        nray_array[ibeam] = len(idsWaves.coherent_wave[ibeam].beam_tracing[0].beam)
        for iray in range(nray_array[ibeam]):
            if (
                idsWaves.coherent_wave[ibeam].beam_tracing[0].beam[iray].power_initial
                > 0
            ):
                is_active[ibeam] = 1
    nbeam_active = sum(is_active)

    # We assume the same number of rays for each beam, to simplify (and this is usually the case)
    nray = max(nray_array)

    if nbeam_active > 1:
        print(
            "There are "
            + str(nbeam_active)
            + " active beam"
            + int(nbeam_active != 1) * "s and each beam has "
            + str(nray)
            + " ray"
            + int(nray != 1) * "s"
        )
    else:
        print(
            "There is "
            + str(nbeam_active)
            + " active beam and each beam has "
            + str(nray)
            + " ray"
            + int(nray != 1) * "s"
        )

    stdarrlen = max(
        max(
            [
                [
                    len(
                        idsWaves.coherent_wave[ibeam]
                        .beam_tracing[0]
                        .beam[iray]
                        .position.r
                    )
                    for iray in range(nray)
                ]
                for ibeam in range(nbeam)
            ]
        )
    )
    x = np.array(
        [
            [[0.0 for ix in range(stdarrlen)] for iray in range(nray)]
            for ibeam in range(nbeam)
        ]
    )
    y, z, r, phi = (
        np.ndarray.copy(x),
        np.ndarray.copy(x),
        np.ndarray.copy(x),
        np.ndarray.copy(x),
    )

    firstloop = True
    for ibeam in range(nbeam):
        if is_active[ibeam] == 1:
            iray = -1
            for irray in range(nray):
                iray = iray + 1
                if (
                    idsWaves.coherent_wave[ibeam]
                    .beam_tracing[0]
                    .beam[iray]
                    .power_initial
                    != 0
                ):
                    wavesr = (
                        idsWaves.coherent_wave[ibeam]
                        .beam_tracing[0]
                        .beam[iray]
                        .position.r
                    )
                    wavesphi = (
                        idsWaves.coherent_wave[ibeam]
                        .beam_tracing[0]
                        .beam[iray]
                        .position.phi
                    )
                    wavesz = (
                        idsWaves.coherent_wave[ibeam]
                        .beam_tracing[0]
                        .beam[iray]
                        .position.z
                    )

                    r[ibeam, iray, : len(wavesr)] = np.array(wavesr)
                    phi[ibeam, iray, : len(wavesphi)] = np.array(wavesphi)
                    z[ibeam, iray, : len(wavesz)] = np.array(wavesz)

                    x[ibeam, iray, :] = r[ibeam, iray, :] * np.cos(phi[ibeam, iray, :])
                    y[ibeam, iray, :] = r[ibeam, iray, :] * np.sin(phi[ibeam, iray, :])

                    wavespower = (
                        idsWaves.coherent_wave[ibeam]
                        .beam_tracing[0]
                        .beam[iray]
                        .electrons.power
                    )
                    wavespowerpar = (
                        idsWaves.coherent_wave[ibeam]
                        .beam_tracing[0]
                        .beam[iray]
                        .power_flow_norm.parallel
                    )
                    wavespowerperp = (
                        idsWaves.coherent_wave[ibeam]
                        .beam_tracing[0]
                        .beam[iray]
                        .power_flow_norm.perpendicular
                    )
                    length = (
                        idsWaves.coherent_wave[ibeam].beam_tracing[0].beam[iray].length
                    )
                    if firstloop:
                        if len(idsWaves.code.name) > 0:
                            label = idsWaves.code.name.upper()
                        else:
                            label = str(ishot) + "," + str(irun)
                        global_label = global_label + "_" + label
                        ax_polview.plot(
                            r[ibeam, iray, : len(wavesr)],
                            z[ibeam, iray, : len(wavesr)],
                            color=color,
                            linestyle=style,
                            label=label,
                        )
                        ax_topview.plot(
                            x[ibeam, iray, : len(wavesr)],
                            y[ibeam, iray, : len(wavesr)],
                            color=color,
                            linestyle=style,
                            label=label,
                        )
                        ax_powview.plot(
                            np.array(length),
                            np.array(wavespower) * 1.0e-6,
                            color=color,
                            linestyle=style,
                            label=label,
                        )
                        firstloop = False
                    else:
                        ax_polview.plot(
                            r[ibeam, iray, : len(wavesr)],
                            z[ibeam, iray, : len(wavesr)],
                            color=color,
                            linestyle=style,
                        )
                        # To ignore weird behaviour of peripheral rays in Torbeam
                        # if iray>0:
                        ax_topview.plot(
                            x[ibeam, iray, : len(wavesr)],
                            y[ibeam, iray, : len(wavesr)],
                            color=color,
                            linestyle=style,
                        )
                        ax_powview.plot(
                            np.array(length),
                            np.array(wavespower) * 1.0e-6,
                            color=color,
                            linestyle=style,
                        )
                        if extra == 1:
                            ax_powparview.plot(
                                np.array(length),
                                np.array(wavespowerpar),
                                color=color,
                                linestyle=style,
                            )
                            ax_powperpview.plot(
                                np.array(length),
                                np.array(wavespowerperp),
                                color=color,
                                linestyle=style,
                            )

ax_powview.legend(loc="upper left", shadow=True, fancybox=True)
plt.subplots_adjust(hspace=0.5)

print("------------------------------------------------------------")

try:
    plt.savefig("EC_rays" + global_label + "_time_" + "%.1f" % time + ".png", dpi=100)
    print(
        "----> Figure saved to EC_rays"
        + global_label
        + "_time_"
        + "%.1f" % time
        + ".png",
        file=sys.stderr,
    )
except:
    print("The figure could not be saved (check local permissions).", file=sys.stderr)

plt.show()


# # ITER Machine Description configuration
# file = open(os.path.dirname(__file__) + "/ITER_MD_configuration.yaml", "r")
# data = yaml.load(file, Loader=yaml.CLoader)
# file.close()

# # if args.wall == 1:
# if False:
#     wall_md = imas.DBEntry(
#         get_backend_id(args.backend),
#         data["wall"]["db"],
#         data["wall"]["shot"],
#         data["wall"]["run"],
#         data["wall"]["user"],
#     )
#     wall_md.open()
#     wall = wall_md.partial_get(
#         ids_name="wall",
#         data_path="description_ggd(0)/grid_ggd(0)/space(0)/objects_per_dimension(0)/object(:)",
#     )
#     wall_md.close()
#     npoints = len(wall)
#     xw = np.zeros(npoints)
#     yw = np.zeros(npoints)
#     zw = np.zeros(npoints)
#     rw = np.zeros(npoints)
#     for point in range(npoints):
#         xw[point] = wall[point].geometry[0]
#         yw[point] = wall[point].geometry[1]
#         zw[point] = wall[point].geometry[2]
#         rw[point] = np.sqrt(xw[point] ** 2 + yw[point] ** 2)
