#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import re
import getpass
import argparse
import textwrap
import traceback
from rich.markdown import Markdown
from rich_argparse import RichHelpFormatter
from idstools.database import DBMaster

from idstools.set_logger import set_logger
from idstools.eqdsk2ids import geqdsk2ids
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
)

# ----------------------------------------------------------------------


def main():
    """
    EQDSK Converter to IDS/equilibrium (eqdsk2ids)
    """

    # Convert GEQDSK to IDS/equilibrium
    eq = geqdsk2ids(args.gpath, cocos_in=args.cocos_in)

    # Create the output datafile
    logger.info("creating output datafile ...")

    outputargs = argparse.Namespace()
    outputargs.backend = args.backend
    outputargs.pulse = args.pulse
    outputargs.run = args.run
    outputargs.user = os.environ["USER"]
    outputargs.database = args.database
    outputargs.version = args.version
    outputargs.mode = "w"
    if args.dest is None:
        if args.uri is not None:
            args.dest = re.sub(r"user=public", f"user={getpass.getuser()}", args.uri)
    outputargs.uri = args.dest

    db = DBMaster.createConnection(outputargs)
    if db is None:
        logger.critical("----> Aborted.")
        exit(1)

    db.put(eq)
    db.close()
    logger.info(f"IDS/equilibrium populated in  {getDatabasePath(outputargs)}.")


# ----------------------------------------------------------------------

description = r"""
(I) Command Line Interface for EQDSK Converter (eqdsk2ids)
------------------------------------------------------------

**Usage:**

0) Load IMAS and install fortranformat and Cerberus (if not done before)

    > module load IMAS
    
    > pip install fortranformat cerberus

1) Compute COCOS and create IDS data file in local database

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER

2) Increase verbosity to see information as COCOS index and transformation coeff.

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER --log INFO

3) Coerce input COCOS index

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER --cocos_in 7

(II) Functional Interface in Python (idstools/eqdsk2ids.py)
------------------------------------------------------------

**Usage:**

0) Initialization

    > from idstools.eqdsk2ids import eqdsk2ids
 
1) Convert Gfile

    > eq = eqdsk2ids(gfile='path/to/gfile')
 
2) Convert Gfile with COCOS input (=1) coerced

    > eq = eqdsk2ids(gfile='path/to/gfile', cocos_in=1)"""
if __name__ == "__main__":
    # Parse for command line options
    prog = os.path.basename(__file__)
    parser = argparse.ArgumentParser(
        prog=prog,
        formatter_class=RichHelpFormatter,
        parents=[dbentryParser],
        description=Markdown(description, style="argparse.text"),
    )
    parser.add_argument(
        "-du",
        "--dest",
        type=str,
        help="destination uri \t\t(default=%(default)s)",
    )
    parser.add_argument(
        "-g",
        "--gfile",
        dest="gpath",
        help="path to GEQDSK file",
        required=True,
        default=None,
    )
    parser.add_argument(
        "--log",
        dest="log",
        default="WARNING",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Configure the logging level, default=%(default)s",
    )
    parser.add_argument(
        "-c",
        "--cocos_in",
        dest="cocos_in",
        help="Tokamak coordinate conventions (COCOS) describing input data",
        required=True,
        type=int,
        default=None,
        choices=[*range(1, 9), *range(11, 19)],
    )
    parser.set_defaults(user=os.environ["USER"])
    args = parser.parse_args()
    # Initialize logger
    logger = set_logger(__name__, level=args.log)

    try:
        main()
    except Exception as e:
        logger.error(traceback.format_exc())
