#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import getpass
import os
import re
import traceback

from rich.markdown import Markdown
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.eqdsk2ids import geqdsk2ids
from idstools.set_logger import set_logger
from idstools.utils.clihelper import (
    getDatabasePath,
)

# ----------------------------------------------------------------------


def main():
    """
    EQDSK Converter to IDS/equilibrium (eqdsk2ids)
    """

    # Convert GEQDSK to IDS/equilibrium
    eq = geqdsk2ids(args.gpath, cocos_in=args.cocos_in)

    # Create the output datafile
    logger.info("creating output datafile ...")

    outputargs = argparse.namespace()
    outputargs.user = os.environ["USER"]
    outputargs.mode = "w"
    # if args.dest is None:
    #     args.dest = re.sub(r"user=public", f"user={getpass.getuser()}", args.src)
    outputargs.uri = args.dest

    db = DBMaster.create_connection(outputargs)
    if db is None:
        logger.critical("----> Aborted.")
        exit(1)

    db.put(eq)
    db.close()
    logger.info(f"IDS/equilibrium populated in  {get_database_path(outputargs)}.")


# ----------------------------------------------------------------------

description = r"""
(I) Command Line Interface for EQDSK Converter (eqdsk2ids)
------------------------------------------------------------

**Usage:**

0) Load IMAS and install fortranformat and Cerberus (if not done before)

    > module load IMAS
    
    > pip install fortranformat cerberus

1) Compute COCOS and create IDS data file in local database

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER

2) Increase verbosity to see information as COCOS index and transformation coeff.

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER --log INFO

3) Coerce input COCOS index

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER --cocos_in 7

(II) Functional Interface in Python (idstools/eqdsk2ids.py)
------------------------------------------------------------

**Usage:**

0) Initialization

    > from idstools.eqdsk2ids import eqdsk2ids
 
1) Convert Gfile

    > eq = eqdsk2ids(gfile='path/to/gfile')
 
2) Convert Gfile with COCOS input (=1) coerced

    > eq = eqdsk2ids(gfile='path/to/gfile', cocos_in=1)"""
if __name__ == "__main__":
    # Parse for command line options
    prog = os.path.basename(__file__)
    parser = argparse.argument_parser(
        prog=prog,
        formatter_class=rich_help_formatter,
        description=markdown(description, style="argparse.text"),
    )
    parser.add_argument(
        "-s",
        "--src",
        type=str,
        required=True,
        help="source uri",
    )
    parser.add_argument(
        "-d",
        "--dest",
        type=str,
        required=True,
        help="destination uri",
    )
    parser.add_argument(
        "-g",
        "--gfile",
        dest="gpath",
        help="path to GEQDSK file",
        required=True,
        default=None,
    )
    parser.add_argument(
        "--log",
        dest="log",
        default="WARNING",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Configure the logging level, default=%(default)s",
    )
    parser.add_argument(
        "-c",
        "--cocos_in",
        dest="cocos_in",
        help="Tokamak coordinate conventions (COCOS) describing input data",
        required=True,
        type=int,
        default=None,
        choices=[*range(1, 9), *range(11, 19)],
    )
    args = parser.parse_args()
    # Initialize logger
    logger = set_logger(__name__, level=args.log)

    try:
        main()
    except Exception as e:
        logger.error(traceback.format_exc())
