#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import re
import argparse
import textwrap
import traceback
from rich.markdown import Markdown
from rich_argparse import RichHelpFormatter
from idstools.database import DBMaster

from idstools.set_logger import set_logger
from idstools.eqdsk2ids import geqdsk2ids
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getIMASVersion,
)

# ----------------------------------------------------------------------


def main():
    """
    EQDSK Converter to IDS/equilibrium (eqdsk2ids)
    """

    # Convert GEQDSK to IDS/equilibrium
    eq = geqdsk2ids(args.gpath, args.ipsign, args.b0sign, args.cocos_in)

    # Create the output datafile
    logger.info("creating output datafile ...")

    outputargs = argparse.Namespace()
    outputargs.backend = args.backend
    outputargs.pulse = args.pulse
    outputargs.run = args.run
    outputargs.user = os.environ["USER"]
    outputargs.database = args.database
    outputargs.version = args.version
    if getIMASVersion() > 4:
        outputargs.mode="w"
        if args.output_uri is None:
            outputargs.uri =  f"imas:mdsplus?user={outputargs.user};shot={outputargs.pulse};run={outputargs.run};database={outputargs.database};version={outputargs.version}"
        else:
            outputargs.uri = args.output_uri
 
    db = DBMaster.createConnection(outputargs)
    if db is None:
        logger.critical("----> Aborted.")
        exit(1)

    db.put(eq)
    db.close()
    logger.info(f"IDS/equilibrium populated in  {getDatabasePath(args)}.")


# ----------------------------------------------------------------------

description=r"""
(I) Command Line Interface for EQDSK Converter (eqdsk2ids)
------------------------------------------------------------

**Usage:**

0) Load IMAS and install fortranformat and Cerberus (if not done before)

    > module load IMAS
    
    > pip install fortranformat cerberus

1) Compute COCOS and create IDS data file in local database

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER

2) Enforce signs of Ip and/or B0 in output

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER --ipsign -1 --b0sign -1

3) Increase verbosity to see information such as COCOS index and transformation coefficients.

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER --log INFO

4) Coerce input COCOS index

    > eqdsk2ids -g path_to_gfile -p 12345 -r 1 -u userid -d ITER --cocos_in 7

(II) Functional Interface in Python (idstools/eqdsk2ids.py)
------------------------------------------------------------

**Usage:**

0) Initialization

    > from idstools.eqdsk2ids import eqdsk2ids
 
1) Convert Gfile

    > eq = eqdsk2ids(gfile='path/to/gfile')
 
2) Convert Gfile and alter signs both for Ip & B0

    > eq = eqdsk2ids(gfile='path/to/gfile', ipsign=-1, b0sign=-1)
 
3) Convert Gfile with COCOS input (set to 1) coerced

    > eq = eqdsk2ids(gfile='path/to/gfile', cocos_in=1)"""
if __name__ == "__main__":
    # Parse for command line options
    prog = os.path.basename(__file__)
    parser = argparse.ArgumentParser(
        prog=prog,
        formatter_class=RichHelpFormatter,
        parents=[dbentryParser],
        description=Markdown(description, style="argparse.text")
    )
    parser.add_argument(
            "-ouri",
            "--output_uri",
            type=str,
            help="output uri \t\t(default=%(default)s)",
        )
    parser.add_argument(
        "-g",
        "--gfile",
        dest="gpath",
        help="path to GEQDSK file",
        required=True,
        default=None,
    )
    parser.add_argument(
        "--log",
        dest="log",
        default="WARNING",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Configure the logging level, default=%(default)s",
    )
    parser.add_argument(
        "--ipsign",
        dest="ipsign",
        help="transform input data to obtain desired sign for Ip on the output, default=%(default)s uses input",
        required=False,
        type=int,
        default=0,
        choices=[-1, 0, 1],
    )
    parser.add_argument(
        "--b0sign",
        dest="b0sign",
        help="transform input data to obtain desired sign for B0 on the output, default=%(default)s uses input",
        required=False,
        type=int,
        default=0,
        choices=[-1, 0, 1],
    )
    parser.add_argument(
        "--cocos_in",
        dest="cocos_in",
        help="coerced COCOS index, otherwise default=%(default)s computes COCOS in GEQDSK file [1,3,5,7]",
        required=False,
        type=int,
        default=None,
        choices=[*range(1, 9), *range(11, 19)],
    )
    parser.set_defaults(user=os.environ["USER"])
    args = parser.parse_args()

    # Initialize logger
    logger = set_logger(__name__, level=args.log)

    try:
        main()
    except Exception as e:
        logger.error(traceback.format_exc())
