#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from os import getenv, path
from sys import exit
from sys import stdout
import argparse
import textwrap
from rich.markdown import Markdown
from rich_argparse import RichHelpFormatter
import yaml
from idstools.database import DBMaster
from idstools.utils.clihelper import dbentryParser

import imas
from idstools.idslist import available_in_dbentry
from idstools import idschk
from idstools.db_validator import ScenarioValidator


# ----------------------------------------------------------------------


def main():
    """
    Command Interface of IDS Data Validation Tool w.r.t. DD (IDSDef.xml)
    """
    db = DBMaster.getConnection(args)
    if db is None:
        print("----> Aborted.")
        exit(1)

    # Initialization for yaml Dumper
    yaml.Dumper.ignore_aliases = lambda *args: True

    # COCOS Initialization
    index = {"COCOS": idschk.IDS_COCOS, "ipsign": args.ipsign, "b0sign": args.b0sign}
    cocos = idschk.COCOS(index=index).get()

    # Load IMAS-DD File
    root = idschk.load_XML(idschk.FILE_IDSDef)

    # Validate COCOS in IDS/equilibrium
    if args.cocos:
        idsname = "equilibrium"
        dd0 = [dd for dd in root if dd.get("name") == idsname][0]
        maxoc = int(dd0.get("maxoccur"))
        #
        buf = {}
        for occ in range(maxoc):
            idsprop = db.partial_get(idsname, "ids_properties", occurrence=occ)
            if idsprop.homogeneous_time in [0, 1, 2]:
                #
                try:
                    idstime = db.partial_get(idsname, "time", occurrence=occ)
                    #
                    if (args.time is None) or (idstime is None):
                        ids = db.get(idsname, occurrence=occ)
                    else:
                        time, itime = idschk.find_time(idstime, args.time)
                        ids = db.get_slice(idsname, time, 1, occurrence=occ)
                except Exception as e:
                    print(f"Cannot retrieve IDS/{idsname}: {e}")
                #
                try:
                    flag, dump = idschk.ids_cocos_check(ids, verbose=args.verbose)
                except Exception as e:
                    exit(f"Cannot compute COCOS: {e}")
                #
                buf.update({"occurence(" + str(occ) + ")": dump})

        print(idschk.dict_to_yaml({"equilibrium": buf}))

    # IDS Validation
    if args.schema_file:
        # Initialize Scenario Validator
        sv = ScenarioValidator(schema_path=[path.abspath(args.schema_file)])

        # Validation for Class imas.DBEntry
        sv.validate_db(db)

description="""
Load IMAS and install Cerberus (if not done before)
----------------------------------------------------

.. code-block:: bash

    $ module load IMAS
    $ pip install cerberus

(I) Command Line Interface for IDS Data Validation (idschk)
-----------------------------------------------------------

Examples:

1) Validate if ITER Scenario meets with physics requirements

.. code-block:: bash

    $ idschk --uri "imas:mdsplus?user=public;shot=131024;run=40;database=ITER;version=3" -f path/to/schema_file/required_fields_core.yml

2) Same with 1) and only for one time slice. Specify time, otherwise middle point if blank

.. code-block:: bash

    $ idschk --uri "imas:mdsplus?user=public;shot=131024;run=40;database=ITER;version=3" -f path/to/schema_file/required_fields_core.yml -t 100.
    $ idschk --uri "imas:mdsplus?user=public;shot=131024;run=40;database=ITER;version=3" -f path/to/schema_file/required_fields_core.yml -t

3) Check IDS/equilibrium for COCOS

.. code-block:: bash

    $ idschk --uri "imas:mdsplus?user=public;shot=131024;run=40;database=ITER;version=3" -c

4) Check IDS/equilibrium with COCOS values

.. code-block:: bash

    $ idschk --uri "imas:mdsplus?user=public;shot=131024;run=40;database=ITER;version=3" -c --verbose

(II) Functional Interface in Python (idstools/idschk.py)
--------------------------------------------------------

Examples: 

0) Initialization

.. code-block:: python

    >>> import imas
    >>> from idstools.idschk import * 
    >>> input = imas.DBEntry(imas.imasdef.MDSPLUS_BACKEND,"ITER",131024,40,"public")
    >>> input.open()
    >>> equilibrium=input.get("equilibrium")

1) Validate if ITER Scenario meets with physics requirements

.. code-block:: python

    >>> flag, log = ids_validator(equilibrium, 'path/to/schema_file/required_fields_core.yml')

2) Validate length of coordinate for INT_*D and FLT_*D

.. code-block:: python

    >>> flag, log = ids_coordinate_check(equilibrium)

3) Same with 2), increasing verbosity,

.. code-block:: python

    >>> flag, log = ids_coordinate_check(equilibrium, verbose=True)

4) Compute COCOS

.. code-block:: python

    >>> cocos = ids_compute_cocos(equilibrium)

5) Get COCOS values

.. code-block:: python

    >>> flag, log = ids_cocos_check(equilibrium, verbose=True)
"""
# ----------------------------------------------------------------------


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="idschk",
        formatter_class=RichHelpFormatter,
        parents=[dbentryParser],
        description=Markdown(description, style="argparse.text")
    )
    parser.add_argument(
        "-l",
        "--list",
        dest="idslist",
        help="IDS names to be checked",
        required=False,
        nargs="*",
    )
    parser.add_argument(
        "-t",
        "--time",
        dest="time",
        help="time (default=middle)",
        type=float,
        required=False,
        const=-99.0,
        default=None,
        nargs="?",
    )
    parser.add_argument(
        "-f",
        "--schema_file",
        dest="schema_file",
        help="file name of validation schema",
        required=False,
        default=None,
    )
    parser.add_argument(
        "--ipsign",
        dest="ipsign",
        help="sign(Ip), default=%(default)s",
        required=False,
        type=int,
        default=-1,
        choices=[-1, 1],
    )
    parser.add_argument(
        "--b0sign",
        dest="b0sign",
        help="sign(B0), default=%(default)s",
        required=False,
        type=int,
        default=-1,
        choices=[-1, 1],
    )
    parser.add_argument(
        "--verbose",
        help="increase output verbosity",
        required=False,
        default=False,
        action="store_true",
    )
    parser.add_argument(
        "-c",
        "--cocos",
        help="compute COCOS values from IDS/equilibrium",
        required=False,
        default=False,
        action="store_true",
    )
    args = parser.parse_args()
    main()
