#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import logging
import os
import sys

from rich_argparse import RichHelpFormatter
from idstools.database import DBMaster

import imas

from idstools.utils.clihelper import imas_parser
from idstools.utils.idslogger import setup_logger

logger = setup_logger("module")

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Copy IDSs from a data-entry into another one",
    formatter_class=RichHelpFormatter,
)
parser.add_argument(
    "-s",
    "--src",
    type=str,
    required=True,
    help="source uri \t\t(default=%(default)s)",
)
parser.add_argument(
    "-d",
    "--dest",
    type=str,
    required=True,
    help="destination uri \t\t(default=%(default)s)",
)

parser.add_argument(
    "-f",
    "--force",
    action="store_true",
    help="Force the creation of destination data-entry (existing data will be lost)",
)
parser.add_argument(
    "--set-dataset-version",
    action="store_true",
    help="Store current DD version into dataset_description IDS if it exists",
)
parser.add_argument(
    "-i",
    "--interactive",
    action="store_true",
    help="Prompt the user to overwrite the ids (Default is to overwrite the ids without asking)",
)
occgroup = parser.add_mutually_exclusive_group()
occgroup.add_argument(
    "-a",
    "--all-occurrences",
    action="store_true",
    help="Copy all occurrences available in the source into the destination",
)
occgroup.add_argument(
    "-o",
    "--output-occurrence",
    type=int,
    default=None,
    help="Copy the selected source into the specified occurrence at the destination",
)
parser.add_argument(
    "ids",
    nargs="*",
    type=str,
    help='IDSs to copy (leave empty to select all IDSs with default occurrence, or append "/n" to copy a specific occurrence "n")',
)
args = parser.parse_args()

if args.src is not None and args.dest is not None:
    if args.src == args.dest:
        logger.error("Can not use the same uri as source and destination!")
        exit()

if args.ids == []:
    args.ids = [ids.value for ids in list(imas.IDSName)]


inputargs = argparse.Namespace()
inputargs.uri = args.src

src_connection = DBMaster.get_connection(inputargs)
if src_connection is None:
    logger.error("Error opening source pulse! Please check existence.")
    sys.exit()
outputargs = argparse.Namespace()
outputargs.uri = args.dest

dest_connection = DBMaster.get_db_entry_object(outputargs)

if not args.force:
    # OPEN DEST
    status, _ = dest_connection.open()
    if status != 0:
        logger.warning("Destination pulse does not exist. Creating.")
        status, _ = dest_connection.create()
    if status != 0:
        logger.error("Error opening destination pulse! Please check parameters.")
        exit(status)
else:
    # CREATE DEST
    status, _ = dest_connection.create()
    if status != 0:
        logger.error("Error creating destination pulse! Please check parameters and permissions.")
        exit(status)


if args.all_occurrences:
    if "/" in args.ids:
        logger.error("Please do not specify source occurrences together with -a/--allOccurrences option")
        exit(status)
    else:
        allids = []
        for idsname in args.ids:
            mocc = getattr(imas, idsname)().getMaxOccurrences()
            allids.append(idsname)
            allids.extend(f"{idsname}/{o}" for o in range(1, mocc + 1))
        args.ids = allids


# COPY IDSs FROM SOURCE TO DEST
for idsname in args.ids:
    inocc = 0
    idsid = idsname.split("/")
    if len(idsid) == 2:
        inocc = int(idsid[1])

    if args.interactive:
        if (
            dest_connection.partial_get(idsid[0], "ids_properties/homogeneous_time", occurrence=inocc)
            == imas.imasdef.EMPTY_INT
        ):
            user_choice = ""
            while user_choice not in ["y", "n"]:
                user_choice = input(f"{idsid[0]} already exists, do you want to overwrite it (y/n)? :")
            if user_choice == "n":
                print(f"skip {idsid[0]}")
                continue
    idsobj = src_connection.get(idsid[0], occurrence=inocc)
    if args.set_dataset_version and idsid[0] == "dataset_description":
        idsobj.dd_version = DBMaster.get_dd_version()
    try:
        if idsobj.ids_properties.homogeneous_time != imas.imasdef.EMPTY_INT:
            print(f"Copying {idsname}")
            outocc = inocc if args.output_occurrence is None else args.output_occurrence
            dest_connection.put(idsobj, occurrence=outocc)
    except Exception as exc:
        print(exc, file=sys.stderr)
        if not args.force:
            logger.warning(
                "This error could be due to difference of data dictionary version between the current one and the existing destination pulse"
            )
            logger.warning(
                "You can use option -f/--force to recreate the destination pulse with the current DD version (WARNING: all other IDSs will be lost at dest)"
            )

src_connection.close()
dest_connection.close()
