#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import imas
import logging
import numpy
import os
import sys

try:
    import StringIO 
except ImportError:
    from io import StringIO 
    
root_path = os.path.dirname(os.path.dirname(__file__))
sys.path.append(root_path)

from idstools.utils.clihelper import getBackendID, imasParser
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Prints content of an IDS onto the terminal",
        formatter_class=argparse.RawTextHelpFormatter,
        parents=[imasParser],
    )

    parser.add_argument("-s", "--shot", help="Shot number", required=True, type=int)
    parser.add_argument("-r", "--run", help="Run number", required=True, type=int)
    parser.add_argument(
        "-e",
        "--show-empty",
        action="store_true",
        dest="show_empty",
        help="Show empty fields of ids",
    )
    parser.add_argument(
        "ids",
        type=str,
        help="Name of the IDS to dump",
    )
    parser.add_argument("path", nargs="?", type=str, help="Data path", default=None)
    parser.add_argument(
        "-f",
        "--full",
        action="store_true",
        help="Print all array elements (can be very slow for large data)",
    )
    parser.add_argument(
        "-c",
        "--compact",
        action="store_true",
        help="Print only names which has data",
    )
    args = parser.parse_args()

    if args.full:
        numpy.set_printoptions(threshold=sys.maxsize)
    else:
        numpy.set_printoptions(threshold=10)

    connection = imas.DBEntry(
        getBackendID(args.backend),
        args.database,
        args.shot,
        args.run,
        args.user,
    )
    status, _ = connection.open()
    if status != 0:
        logger.error(
            f"Shot {args.shot}, run {args.run} for user={args.user} and database={args.database} does not exists"
        )
        exit(1)

    nameocc = args.ids.split("/")
    if len(nameocc) == 1:
        occurrence = 0
    elif len(nameocc) == 2:
        occurrence = int(nameocc[1])
    else:
        logger.error(f'ERROR: "{args.ids}" syntax error!')
        exit(1)
    idsname = nameocc[0]

    if args.path is None:
        ids = connection.get(idsname, occurrence)
        if args.compact:
            try:
                output = StringIO()
                sys.stdout = open(os.devnull, 'w')

                ids.dump(print_empty=args.show_empty, file=output)
                
                sys.stdout = sys.__stdout__
                output.seek(0)

                for line in output.readlines():
                    if "[" in line:
                        continue
                    if "]" in line:
                        continue
                    if "class" in line:
                        continue
                    if "value" in line:
                        continue
                    if ":" in line:
                        line = line.split(":")[0] + "\n"
                    line = line.replace("Attribute", "")
                    line = line.replace("class", "")
                    line = line.replace("\t", "  ")
                    print(line, end="")
                output.close()
            except Exception as e: print(e)
        else:
            try:
                ids.dump(print_empty=args.show_empty)
            except Exception:
                print(ids)
        
    else:
        try:
            result = connection.partial_get(idsname, args.path, occurrence)
        except Exception as exc:
            logger.error(exc)
            exit(1)

        resultType = type(result)
        print(f"Type: {resultType}")
        if result.__class__ == numpy.ndarray:
            print(f"Shape: {result.shape}")
            print(f"Data type: {result.dtype.name}")

        print("----------------------------------------------")
        if result.__class__ == numpy.ndarray and len(result) < 1:
            exit(0)

        print("----------------------------------------------")
        if (
            result.__class__ == numpy.ndarray
            and result[0].__class__.__module__ != "numpy"
        ):
            for i in range(len(result)):
                idsDump = result[i]
                print(idsDump)
                print("-------------------------")
        else:
            print(result)
    connection.close()
