#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import logging
import os
import sys

from rich_argparse import RichHelpFormatter
from idstools.database import DBMaster

import imas

from idstools.utils.clihelper import imasParser
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module")

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Copy IDSs from a data-entry into another one",
    formatter_class=RichHelpFormatter,
    parents=[imasParser],
)
parser.add_argument(
    "-su",
    "--src",
    type=str,
    help="source uri \t\t(default=%(default)s)",
)
parser.add_argument(
    "-du",
    "--dest",
    type=str,
    help="destination uri \t\t(default=%(default)s)",
)

parser.add_argument("-sp", "--src_pulse", help="Source pulse number", type=int)
parser.add_argument("-sr", "--src_run", help="Source run number", type=int)
parser.add_argument("-dp", "--dest_pulse", help="Destination pulse number", type=int)
parser.add_argument("-dr", "--dest_run", help="Destination run number", type=int)
# default user from parent parser is 'public', which is fine for exploration scripts but less for management scripts
parser.set_defaults(user=os.environ["USER"])
parser.add_argument(
    "-destd",
    "--dest_database",
    type=str,
    default=None,
    help="Database name for the destination data-entry",
)
parser.add_argument(
    "-destb",
    "--dest_backend",
    type=str,
    help="Backend name for the destination data-entry",
)
parser.add_argument(
    "-f",
    "--force",
    action="store_true",
    help="Force the creation of destination data-entry (existing data will be lost)",
)
parser.add_argument(
    "--setDatasetVersion",
    action="store_true",
    help="Store current DD version into dataset_description IDS if it exists",
)
parser.add_argument(
    "-i",
    "--interactive",
    action="store_true",
    help="Prompt the user to overwrite the ids (Default is to overwrite the ids without asking)",
)
occgroup = parser.add_mutually_exclusive_group()
occgroup.add_argument(
    "-a",
    "--allOccurrences",
    action="store_true",
    help="Copy all occurrences available in the source into the destination",
)
occgroup.add_argument(
    "-o",
    "--outputOccurrence",
    type=int,
    default=None,
    help="Copy the selected source into the specified occurrence at the destination",
)
parser.add_argument(
    "ids",
    nargs="*",
    type=str,
    help='IDSs to copy (leave empty to select all IDSs with default occurrence, or append "/n" to copy a specific occurrence "n")',
)
args = parser.parse_args()
if args.dest_database is None:
    args.dest_database = args.database


if args.dest_backend is None:
    args.dest_backend = args.backend

isUriCheckDone = False
if args.src is not None and args.dest is not None:
    isUriCheckDone = True
    if args.src == args.dest:
        logger.error("Can not use the same uri as source and destination!")
        exit()

if isUriCheckDone is False:
    if (
        args.src_pulse == args.dest_pulse
        and args.src_run == args.dest_run
        and args.user == os.environ["USER"]
        and args.database == args.dest_database
        and args.backend == args.dest_backend
    ):
        logger.error("Can not use the same data-entry as source and destination!")
        exit()

if args.ids == []:
    args.ids = [ids.value for ids in list(imas.IDSName)]


inputargs = argparse.Namespace()
inputargs.backend = args.backend
inputargs.pulse = args.src_pulse
inputargs.run = args.src_run
inputargs.user = args.user
inputargs.database = args.database
inputargs.version = args.version
inputargs.uri = args.src

src_connection = DBMaster.getConnection(inputargs)
if src_connection is None:
    logger.error("Error opening source pulse! Please check existence.")
    sys.exit()
outputargs = argparse.Namespace()
outputargs.backend = args.dest_backend
outputargs.pulse = args.dest_pulse
outputargs.run = args.dest_run
outputargs.user = os.environ["USER"]
outputargs.database = args.dest_database
outputargs.version = args.version
outputargs.uri = args.dest


dest_connection = DBMaster.getDBEntryObject(outputargs)

if not args.force:
    # OPEN DEST
    status, _ = dest_connection.open()
    if status != 0:
        logger.warning("Destination pulse does not exist. Creating.")
        status, _ = dest_connection.create()
    if status != 0:
        logger.error("Error opening destination pulse! Please check parameters.")
        exit(status)
else:
    # CREATE DEST
    status, _ = dest_connection.create()
    if status != 0:
        logger.error(
            "Error creating destination pulse! Please check parameters and permissions."
        )
        exit(status)


if args.allOccurrences:
    if "/" in args.ids:
        logger.error(
            "Please do not specify source occurrences together with -a/--allOccurrences option"
        )
        exit(status)
    else:
        allids = []
        for idsname in args.ids:
            mocc = getattr(imas, idsname)().getMaxOccurrences()
            allids.append(idsname)
            allids.extend(f"{idsname}/{o}" for o in range(1, mocc + 1))
        args.ids = allids


# COPY IDSs FROM SOURCE TO DEST
for idsname in args.ids:
    inocc = 0
    idsid = idsname.split("/")
    if len(idsid) == 2:
        inocc = int(idsid[1])

    if args.interactive:
        if (
            dest_connection.partial_get(
                idsid[0], "ids_properties/homogeneous_time", occurrence=inocc
            )
            == imas.imasdef.EMPTY_INT
        ):
            user_choice = ""
            while user_choice not in ["y", "n"]:
                user_choice = input(
                    f"{idsid[0]} already exists, do you want to overwrite it (y/n)? :"
                )
            if user_choice == "n":
                print(f"skip {idsid[0]}")
                continue
    idsobj = src_connection.get(idsid[0], occurrence=inocc)
    if args.setDatasetVersion and idsid[0] == "dataset_description":
        idsobj.dd_version = DBMaster.getDDVersion()
    try:
        if idsobj.ids_properties.homogeneous_time != imas.imasdef.EMPTY_INT:
            print(f"Copying {idsname}")
            outocc = inocc if args.outputOccurrence is None else args.outputOccurrence
            dest_connection.put(idsobj, occurrence=outocc)
    except Exception as exc:
        print(exc, file=sys.stderr)
        if not args.force:
            logger.warning(
                "This error could be due to difference of data dictionary version between the current one and the existing destination pulse"
            )
            logger.warning(
                "You can use option -f/--force to recreate the destination pulse with the current DD version (WARNING: all other IDSs will be lost at dest)"
            )

src_connection.close()
dest_connection.close()
