# #!/usr/bin/env python
import argparse
import base64
import datetime
import difflib
import imas
import logging
import matplotlib.pyplot as plt
import numpy as np
import os
import re
import sys
import tempfile
import time

from idstools.cli import get_backend_id, imas_parser
from io import BytesIO

root_path = os.path.dirname(os.path.dirname(__file__))
sys.path.append(root_path)
from src.compute.common.functions import compare_ids
from src.utils.dd_helper import DDHelper

THRESHOLD_PERCENT = 2


def setup_logger(name, log_file, verbose=False, fmt=None):
    logger = logging.getLogger(name)
    logger.setLevel(logging.WARN)  # default
    if verbose:
        logger.setLevel(logging.DEBUG)
    # Create stream handler for logging to stdout (log all five levels)
    stdout_handler = logging.StreamHandler(sys.stdout)
    stdout_handler.setLevel(logging.DEBUG)
    stdout_handler.setFormatter(logging.Formatter("%(message)s"))
    logger.addHandler(stdout_handler)

    """Add a file handler for this logger with the specified `name` (and store the log file
    under `log_dir`)."""
    # Format for file log
    if fmt is None:
        fmt = "%(asctime)s | %(levelname)9s | %(filename)s:%(lineno)d | %(message)s"
    formatter = logging.Formatter(fmt)

    # Create file handler for logging to a file (log all five levels)
    file_handler = logging.FileHandler(log_file)
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)
    return logger


def get_filename(name, file_title, log_dir):
    # Determine log path and file name; create log path if it does not exist

    now = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    if name == "":
        file_name = f"{now}_{file_title}"
    else:
        file_name = f'{str(name).replace(" ", "_")}_{now}_{file_title}'
    if not os.path.exists(log_dir):
        try:
            os.makedirs(log_dir)
        except:
            print(
                f"Cannot create directory {log_dir}. ",
                end="",
                file=sys.stderr,
            )
            log_dir = "/tmp" if sys.platform.startswith("linux") else "."
            print(f"Defaulting to {log_dir}.", file=sys.stderr)
    return os.path.join(log_dir, file_name)


def generate_html(file_path, data, shotA, runA, shotB, runB):
    logger.info("Writing to html file :" + file_path)

    dd_helper = DDHelper()

    file_object = open(file_path, "w")

    report_title = f"Differences : {shotA}/{runA} ~ {shotB}/{runB}"
    report_header_string = (
        """<head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
                <title>"""
        + report_title
        + """</title>
            </head>"""
    )
    report_table_header = f"""
    <thead class="table-primary">
    <tr>
                        <th>Field Name</th>
                        <th>{shotA}/{runA}</th>
                        <th>{shotB}/{runB}</th>
                        <th>Comments</th>
                        <th>Details</th>
                        <tr>
                    </thead>"""
    file_object.write(
        f"""<!DOCTYPE html>
            <html lang="en">
                {report_header_string}
                
                <body>
                <div class="jumbotron jumbotron-fluid text-center">
                    <div class="container">
                        <p class="h4">{report_title}</p>
                        <small class="text-muted">Result generated by idsdiff tool show difference between quantities and shows plots</small>
                    </div>
                </div>
                    <div class="table-responsive" >
                    <table class="table table-bordered table-striped table-hover table-sm align-top">
                    <caption>List of differences</caption>
                        {report_table_header}<tbody>"""
    )
    plot_counter = 0
    for idsname, values in data.items():
        compare_result, output = values
        if bool(output) is False:
            continue
        report_field_difference = ""
        report_details = ""

        add_header = True
        for key, values in output.items():
            report_diff_line = ""
            if add_header == True:
                report_diff_line = f"""<tr class="table-secondary">
                        <th scope="row" colspan="5">{idsname}</td>
                    </tr>"""
                report_field_difference += report_diff_line
                add_header = False
            badge_color = "bg-secondary"
            if values[3] is not None:
                if values[3] == "different values":
                    badge_color = "bg-primary"
                elif values[3] == "different length":
                    badge_color = "bg-warning"

            if values[2] is np.ndarray:
                if values[0] is not None and values[1] is not None:
                    if len(values[0]) <= len(values[1]):
                        threshold_candidate = values[0]
                        compare_candidate = values[1][: len(values[0])]
                    else:
                        threshold_candidate = values[1]
                        compare_candidate = values[0][: len(values[1])]
                    threshold_min = (
                        (threshold_candidate * THRESHOLD_PERCENT) / 100
                    ) - threshold_candidate
                    threshold_max = (
                        (threshold_candidate * THRESHOLD_PERCENT) / 100
                    ) + threshold_candidate

                    within_threshold = all(compare_candidate > threshold_min) and all(
                        compare_candidate < threshold_max
                    )
                    if within_threshold is False:
                        field_path = re.sub("\[(.*?)\]", "", key)
                        field_path = field_path[field_path.index(".") + 1 :]
                        field_path = field_path.replace(".", "/")
                        coordinate_path = dd_helper.get_coordinate(idsname, field_path)
                        if coordinate_path[0] == r"/":
                            coordinate_path = coordinate_path[1:]
                        if "itime" in coordinate_path:
                            coordinate_path = coordinate_path.replace("itime", "0")

                        valuesA = np.copy(values[0])
                        valuesB = np.copy(values[1])

                        # Calculate cross corelation
                        correlate_result = np.correlate(valuesA, valuesB, "full")
                        b_shift_positions = np.arange(-len(valuesA) + 1, len(valuesB))
                        itemindex = np.where(
                            correlate_result == np.max(correlate_result)
                        )
                        cross_correlation = b_shift_positions[itemindex][0]
                        # TODO Check the logic of normalised difference calculation
                        if len(valuesA) < len(valuesB):
                            valuesB = valuesB[: len(valuesA)]
                        else:
                            valuesA = valuesA[: len(valuesB)]
                        # valuesA[valuesA == 0] = 0.00000001
                        # valuesB[valuesB == 0] = 0.00000001

                        abs_diff = abs(valuesA - valuesB)
                        base = abs(valuesA)
                        if np.average(abs(valuesA)) > np.average(abs(valuesB)):
                            base = abs(valuesB)

                        norm_diff = abs_diff / np.linalg.norm(base, ord=np.inf)
                        # norm_diff = abs_diff / base

                        norm_avg_diff = np.average(norm_diff)

                        minA = np.amin(values[0])
                        minB = np.amin(values[1])
                        maxA = np.amax(values[0])
                        maxB = np.amax(values[1])
                        avgA = np.average(values[0])
                        avgB = np.average(values[1])
                        avg_diff = abs(avgA - avgB)
                        rmsA = np.sqrt(np.mean(values[0] ** 2))
                        rmsB = np.sqrt(np.mean(values[1] ** 2))
                        rms_diff = abs(rmsA - rmsB)

                        timeA = inputA.partial_get(idsname, coordinate_path)
                        timeB = inputB.partial_get(idsname, coordinate_path)
                        if timeA is not None and timeB is not None:
                            min_time_A = np.amin(timeA)
                            min_time_B = np.amin(timeB)

                            max_time_A = np.amax(timeA)
                            max_time_B = np.amax(timeB)
                            ax_timeA = np.linspace(
                                min_time_A if min_time_A < min_time_B else min_time_B,
                                max_time_A if max_time_A > max_time_B else max_time_B,
                                len(values[0]),
                            )
                            ax_timeB = np.linspace(
                                min_time_A if min_time_A < min_time_B else min_time_B,
                                max_time_A if max_time_A > max_time_B else max_time_B,
                                len(values[1]),
                            )
                            fig = plt.figure()
                            ax = fig.add_subplot(111)
                            ax.set_title(key)
                            ax.set_xlabel(coordinate_path)
                            ax.set_ylabel("values")
                            ax2 = ax.twinx()
                            ax2.plot(
                                ax_timeA,
                                abs_diff,
                                "-g",
                                label="difference",
                                linewidth="0.5",
                            )
                            ax2.set_yscale("log")
                            if len(values[0]) < 10:
                                ax.plot(
                                    ax_timeA,
                                    values[0],
                                    marker="o",
                                    color="r",
                                    label=f"{shotA}/{runA}",
                                    linewidth="0.5",
                                    ms=2,
                                )
                            else:
                                ax.plot(
                                    ax_timeA,
                                    values[0],
                                    color="r",
                                    label=f"{shotA}/{runA}",
                                    linewidth="0.5",
                                    ms=2,
                                )
                            if len(values[1]) < 10:
                                ax.plot(
                                    ax_timeB,
                                    values[1],
                                    marker="D",
                                    color="b",
                                    label=f"{shotB}/{runB}",
                                    linewidth="0.5",
                                    ms=2,
                                )
                            else:
                                ax.plot(
                                    ax_timeB,
                                    values[1],
                                    color="b",
                                    label=f"{shotB}/{runB}",
                                    linewidth="0.5",
                                    ms=2,
                                )
                            ax.legend(loc="upper right")
                            ax.grid()
                            tmpfile = BytesIO()
                            fig.savefig(tmpfile, format="png")
                            encoded = base64.b64encode(tmpfile.getvalue()).decode(
                                "utf-8"
                            )
                            plt.close()

                            report_details = f"""<table class="table table-bordered table-striped table-hover table-sm align-top">
                                                        <thead class="table-primary">
                                                            <tr>
                                                            <th>Attribute Name</th>
                                                            <th>{shotA}/{runA}</th>
                                                            <th>{shotB}/{runB} </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                        <tr>
                                                            <td>minimum</td>
                                                            <td>{"{:.4e}".format(minA)}</td>
                                                            <td>{"{:.4e}".format(minB)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td>maximum</td>
                                                            <td>{"{:.4e}".format(maxA)}</td>
                                                            <td>{"{:.4e}".format(maxB)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td>average</td>
                                                            <td>{"{:.4e}".format(avgA)}</td>
                                                            <td>{"{:.4e}".format(avgB)}</td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                    <ul class="list-group">
                                                    <li class="list-group-item d-flex justify-content-between align-items-center"> normalized average difference : <span>{"{:.4e}".format(norm_avg_diff)} </span></li>
                                                    <li class="list-group-item d-flex justify-content-between align-items-center"> cross correlation : <span>{cross_correlation}</span></li>
                                                    <li class="list-group-item d-flex justify-content-between align-items-center"> average difference : <span>{"{:.4e}".format(avg_diff)} </span></li>
                                                    <li class="list-group-item d-flex justify-content-between align-items-center"> rms difference : <span>{"{:.4e}".format(rms_diff)} </span></li>
                                                    </ul>
                                                    <img src="data:image/png;base64, {encoded}" alt="Red dot"  class="img-fluid rounded"/>"""
                            report_diff_line = f"""<tr>
                                    <td>{key}</td>
                                    <td>Array length : {len(values[0])}</td>
                                    <td>Array length : {len(values[1])}</td>
                                    <td><span class="badge {badge_color}">{values[3]}</span></td>
                                    <td><button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="collapse" data-bs-target="#plot{plot_counter}">See details</button>
                                    <div class="collapse" id="plot{plot_counter}">
                                    <div class="card card-body">{report_details}
                                    </div>
                                    </div>
                                    </td>
                                </tr>"""
                            plot_counter = plot_counter + 1

            elif values[2] == list:
                report_diff_line = f"""<tr>
                        <td>{key}</td>
                        <td>List length : {len(values[0])}</td>
                        <td>List length : {len(values[1])}</td>
                        <td><span class="badge {badge_color}">{values[3]}</span></td>
                        <td></td>
                    </tr>"""
            else:
                if type(values[0]) is int or type(values[1]) is int:
                    threshold_min = ((values[0] * THRESHOLD_PERCENT) / 100) - values[0]
                    threshold_max = ((values[0] * THRESHOLD_PERCENT) / 100) + values[0]
                    if values[1] > threshold_min and values[1] < threshold_max:
                        report_diff_line = f"""<tr>
                            <td>{key}</td>
                            <td>{values[0]}</td>
                            <td>{values[1]}</td>
                            <td><span class="badge {badge_color}">{values[3]}</span></td>
                            <td></td>
                        </tr>"""
                elif type(values[0]) is float or type(values[1]) is float:
                    threshold_min = ((values[0] * THRESHOLD_PERCENT) / 100) - values[0]
                    threshold_max = ((values[0] * THRESHOLD_PERCENT) / 100) + values[0]
                    if values[1] > threshold_min and values[1] < threshold_max:
                        report_diff_line = f"""<tr>
                            <td>{key}</td>
                            <td>{"{:.4e}".format(values[0])}</td>
                            <td>{"{:.4e}".format(values[1])}</td>
                            <td><span class="badge {badge_color}">{values[3]}</span></td>
                            <td></td>
                        </tr>"""
                elif type(values[0]) is str or type(values[1]) is str:
                    if len(values[0]) > 100:
                        tmpdir = "/dev/shm" if os.path.exists("/dev/shm") else "."
                        idsA = tempfile.mktemp(prefix="idsA_", dir=tmpdir)
                        idsB = tempfile.mktemp(prefix="idsB_", dir=tmpdir)
                        try:
                            with open(idsA, "wb") as f:
                                f.write(bytes(values[0], "UTF-8"))
                        except:
                            if os.path.exists(idsA):
                                os.unlink(idsA)
                            raise

                        try:
                            with open(idsB, "wb") as f:
                                f.write(bytes(values[1], "UTF-8"))
                        except:
                            if os.path.exists(idsB):
                                os.unlink(idsB)
                            raise

                        with open(idsA, "r") as file_idsA:
                            lines_idsA = file_idsA.readlines()
                        with open(idsB, "r") as file_idsB:
                            lines_idsB = file_idsB.readlines()

                        diff = difflib.unified_diff(
                            lines_idsA,
                            lines_idsB,
                            fromfile=idsA,
                            tofile=idsB,
                            lineterm="",
                        )

                        os.unlink(idsA)
                        os.unlink(idsB)
                        diff_lines = []
                        for line in diff:
                            if "\n" not in line:
                                line = line + "\n"
                            diff_lines.append(line)
                        diff_lines_text = "".join(
                            line for line in diff_lines if not line.isspace()
                        )
                        report_diff_line = f"""<tr>
                                <td>{key}</td>
                                <td colspan="2"><textarea class="form-control">{diff_lines_text}</textarea></td>
                                <td><span class="badge {badge_color}">{values[3]}</span></td>
                                <td></td>
                            </tr>"""
                    else:
                        report_diff_line = f"""<tr>
                                <td>{key}</td>
                                <td>{values[0]}</td>
                                <td>{values[1]}</td>
                                <td><span class="badge {badge_color}">{values[3]}</span></td>
                                <td></td>
                            </tr>"""
            report_field_difference += report_diff_line
        file_object.write(f"""   {report_field_difference}""")
    file_object.write(
        f"""</tbody></table>
                    </div>
                </body>
            </html>
            """
    )
    file_object.close()


if __name__ == "__main__":
    # Management of input arguments
    parser = argparse.ArgumentParser(
        description="Compare a IDS from 2 datasets", parents=[imas_parser]
    )
    parser.add_argument("shotA", type=int, help="shot number of first dataset")
    parser.add_argument("runA", type=int, help="run number of first dataset")
    parser.add_argument("shotB", type=int, help="shot number of second dataset")
    parser.add_argument("runB", type=int, help="run number of second dataset")
    parser.add_argument(
        "ids",
        nargs="*",
        type=str,
        help="Name (or space separated list of names) of IDS to compare (leave empty to compare all IDSs)",
    )
    parser.add_argument(
        "--backendB",
        type=str,
        default=None,
        help="Specifies the backend of second dataset (default: same as first dataset)",
    )
    parser.add_argument(
        "--databaseB",
        type=str,
        default=None,
        help="Specifies the database name of second dataset (default: same as first dataset)",
    )
    parser.add_argument(
        "--userB",
        type=str,
        default=None,
        help="Specifies the owner (username) of second dataset (default: same as first dataset)",
    )
    parser.add_argument(
        "--skip-provenance",
        action="store_true",
        help="Discards provenance data differences (optional)",
    )
    parser.add_argument(
        "--generate-html",
        action="store_true",
        help="Generate static html page for showing difference including plots",
    )
    parser.add_argument(
        "--report-dir",
        type=str,
        default=None,
        help="Specifies directory where report should be stored",
    )
    args = parser.parse_args()

    # set defaults for second dataset
    if args.databaseB is None:
        args.databaseB = args.database
    if args.backendB is None:
        args.backendB = args.backend
    if args.userB is None:
        args.userB = args.user

    inputA = imas.DBEntry(
        get_backend_id(args.backend),
        args.database,
        args.shotA,
        args.runA,
        user_name=args.user,
    )
    status, _ = inputA.open()
    if status != 0:
        print("Error opening first dataset! Please check existence.", file=sys.stderr)
        sys.exit(status)

    inputB = imas.DBEntry(
        get_backend_id(args.backendB),
        args.databaseB,
        args.shotB,
        args.runB,
        user_name=args.userB,
    )
    status, _ = inputB.open()
    if status != 0:
        print("Error opening second dataset! Please check existence.", file=sys.stderr)
        sys.exit(status)

    if args.ids == []:
        args.ids = [ids.value for ids in list(imas.IDSName)]

    report_dir = "report"
    if args.report_dir is not None:
        if os.path.exists(args.report_dir):
            report_dir = args.report_dir

    file_title = f"_{args.shotA}_{args.runA}_{args.shotB}_{args.runB}"
    file_path = get_filename("", file_title, report_dir)
    log_file = file_path + ".log"
    html_file = file_path + ".html"
    logger = setup_logger("module", log_file=log_file, verbose=True, fmt="%(message)s")
    st = time.time()
    data = {}
    for idsname in args.ids:
        idsA = inputA.get(idsname)
        idsB = inputB.get(idsname)
        compare_result, output = compare_ids(
            idsA, idsB, field=idsname, ignore_version=args.skip_provenance, output={}
        )
        data[idsname] = (compare_result, output)
    et = time.time()
    elapsed_time = et - st
    # logger.debug(
    #     "ids difference is calculated in:" + "{:10.2f}".format(elapsed_time) + "seconds"
    # )
    if bool(data):
        if args.generate_html is True:
            st = time.time()
            generate_html(html_file, data, args.shotA, args.runA, args.shotB, args.runB)
            et = time.time()
            elapsed_time = et - st
            try:
                import webbrowser

                webbrowser.open(html_file)
            except:
                pass
            # logger.info(
            #     "HTML file is generated in:" + "{:10.2f}".format(elapsed_time) + "seconds."
            # )
