#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ids_content and listidss is merged

import argparse
import sys

import numpy as np
from rich.markdown import Markdown
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.utils.clihelper import dbentryParser
from idstools.utils.idshelper import (
    getAvailableIdsAndOccurrences,
    getAvailableIdsAndTimes,
)
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module")
np.set_printoptions(threshold=1, precision=2, suppress=True)

description = """
By default this script lists available IDSes in the pulse. It prints all IDSes along with its time length. The fullarray option allows you to print the complete time array.
with occurrence option you can view ids with their occurrences, its comment and occurrence type if present
yaml option is provided which is used by other scripts to provide list of idses with their time ranges in yaml format

[``ids_content(yaml)``, ``listidss`` (with time slices), ``idsoccurrences(occ)`` merged into one script]
"""
parser = argparse.ArgumentParser(
    prog="idslist",
    formatter_class=RichHelpFormatter,
    description=Markdown(description, style="argparse.text"),
    parents=[dbentryParser],
)
parser.add_argument(
    "-y",
    "--yaml",
    action="store_true",
    help="List ids content for yaml files aimed at describing a scenario",
)
parser.add_argument(
    "-o",
    "--occ",
    action="store_true",
    help="List ids with their number of occurrences with comment and occurrence_type if available",
)
parser.add_argument("-i", "--ids", required=False, type=str, help="IDS name to filter")
parser.add_argument(
    "-f",
    "--fullarray",
    action="store_true",
    help="Show full time array values [Use with default]",
)

args = parser.parse_args()

connection = DBMaster.getConnection(args)
if connection is None:
    print("----> Aborted.")
    exit(1)

if args.yaml is True:
    if args.fullarray:
        print(
            "(-f fullarray) option is provided, can not show full array for yaml output"
        )
    for idsname, oc in getAvailableIdsAndOccurrences(connection):
        if args.ids:
            if idsname != args.ids:
                continue
        homogeneous_time = connection.partial_get(
            idsname, "ids_properties/homogeneous_time", occurrence=oc
        )
        times = connection.partial_get(idsname, "time", occurrence=oc)

        # Format idsname
        idsnameoc = f"{idsname}/{str(oc)}" if oc > 0 else idsname
        # For every homogeneous_time [0,1,2]
        if homogeneous_time == 0:
            print(f"  {idsnameoc}:")
            if times is not None:
                print(f"     time_step_number: {len(times)}")
            print("     time:             [unhomogeneous]")
        elif homogeneous_time == 1:
            if times is not None:
                if len(times) > 1:
                    time_step = (times[len(times) - 1] - times[0]) / (len(times) - 1)
                    start_time = times[0]
                    end_time = times[len(times) - 1]
                    print(f"  {idsnameoc}:")
                    print(f"     time_step_number: {len(times)}")
                    print(
                        f"     start_end_step:   [{str(start_time)} {str(end_time)} {str(time_step)}]"
                    )
                elif len(times) == 1:
                    print(f"  {idsnameoc}:")
                    print(f"     time_step_number: {len(times)}")
                    print(f"     time:             [{str(times[0])}]")
        elif homogeneous_time == 2:
            print(f"  {idsnameoc}:")
            if times is not None:
                print(f"     time_step_number: {len(times)}")
            print("     time:             [static]")
    connection.close()
    exit(0)


elif args.occ is True:
    if args.fullarray:
        print(
            "(-f fullarray) option is provided, can not show full array for yaml output"
        )

    for idsname, oc, comment in getAvailableIdsAndOccurrences(
        connection, getComment=True
    ):
        # If user wants to check specific ids type
        if args.ids:
            if idsname != args.ids:
                continue
        # Format idsname
        idsnameoc = f"{idsname}/{str(oc)}"
        print(f"  {idsnameoc}: {comment}")
    connection.close()
    exit(0)
else:
    question_string = "?"

    availableIdsAndTimes = getAvailableIdsAndTimes(connection)
    question_string = "?"
    for idsName, timeArray in availableIdsAndTimes:
        if args.ids:
            if idsName != args.ids:
                continue
        if len(timeArray) == 1 and np.isnan(timeArray[0]):
            print(f"{idsName:15}:  {question_string:5} slices: heterogeneous IDS ")
        elif len(timeArray) == 1 and timeArray[0] == np.NINF:
            print(f"{idsName:15}:  {question_string:5} slices: time independent IDS ")
        else:
            if args.fullarray is True:
                np.set_printoptions(threshold=sys.maxsize)
            print(f"{idsName:15}: {str(len(timeArray)):5} slices: {timeArray} ")
    connection.close()
    exit(0)
