#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
import sys

from rich_argparse import RichHelpFormatter

import numpy

try:
    import StringIO
except ImportError:
    from io import StringIO

from idstools.database import DBMaster
from idstools.utils.clihelper import dbentryParser
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Prints content of an IDS onto the terminal [previously known as idsdump and idsdumppath]",
        formatter_class=RichHelpFormatter,
        parents=[dbentryParser],
    )

    parser.add_argument(
        "-e",
        "--show-empty",
        action="store_true",
        dest="show_empty",
        help="Show empty fields of ids",
    )
    parser.add_argument(
        "ids",
        type=str,
        help="Name of the IDS to dump",
    )
    parser.add_argument(
        "idspath", nargs="?", type=str, help="IDS data path", default=None
    )
    parser.add_argument(
        "-f",
        "--full",
        action="store_true",
        help="Print all array elements (can be very slow for large data)",
    )
    parser.add_argument(
        "-c",
        "--compact",
        action="store_true",
        help="Print only names which has data",
    )
    args = parser.parse_args()
    connection = DBMaster.getConnection(args)
    if connection is None:
        exit(1)
    if args.full:
        numpy.set_printoptions(threshold=sys.maxsize)
    else:
        numpy.set_printoptions(threshold=10)

    nameocc = args.ids.split("/")
    if len(nameocc) == 1:
        occurrence = 0
    elif len(nameocc) == 2:
        occurrence = int(nameocc[1])
    else:
        logger.error(f'ERROR: "{args.ids}" syntax error!')
        exit(1)
    idsname = nameocc[0]

    if args.idspath is None:
        ids = connection.get(idsname, occurrence)
        if args.compact:
            try:
                output = StringIO()
                sys.stdout = open(os.devnull, "w")

                ids.dump(print_empty=args.show_empty, file=output)

                sys.stdout = sys.__stdout__
                output.seek(0)

                for line in output.readlines():
                    if "[" in line and "]" not in line:
                        continue
                    if "]" in line and "[" not in line:
                        continue
                    if "]" in line and "[" in line and "." in line:
                        continue
                    if "class" in line:
                        continue
                    if "value" in line:
                        continue
                    if ":" in line:
                        line = line.split(":")[0] + "\n"
                    line = line.replace("Attribute", "")
                    line = line.replace("class", "")
                    line = line.replace("=", "")
                    line = line.replace("\t", "  ")
                    print(line, end="")
                output.close()
            except Exception as e:
                print(e)
        else:
            try:
                ids.dump(print_empty=args.show_empty)
            except Exception as e:
                print(ids)

    else:
        try:
            result = connection.partial_get(idsname, args.idspath, occurrence)
        except Exception as exc:
            logger.error(exc)
            exit(1)

        resultType = type(result)
        print(f"Type: {resultType}")
        if result.__class__ == numpy.ndarray:
            print(f"Shape: {result.shape}")
            print(f"Data type: {result.dtype.name}")

        print("----------------------------------------------")
        if result.__class__ == numpy.ndarray and len(result) < 1:
            exit(0)

        print("----------------------------------------------")
        if (
            result.__class__ == numpy.ndarray
            and result[0].__class__.__module__ != "numpy"
        ):
            for i in range(len(result)):
                idsDump = result[i]
                print(idsDump)
                print("-------------------------")
        else:
            print(result)
    connection.close()
