#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
import sys

from rich_argparse import RichHelpFormatter
import numpy

try:
    import StringIO
except ImportError:
    from io import StringIO

from idstools.database import DBMaster
from idstools.utils.clihelper import dbentryParser
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="""Prints content of an IDS onto the terminal\n 
        provide with fragment
        e.g. -u imas:hdf5?path=/home/ITER/fleuryl/public/imasdb/west/3/54914/4#wall or #wall:0/description_2d | less
        [previously known as idsdump and idsdumppath]""",
        formatter_class=RichHelpFormatter,
        parents=[dbentryParser],
    )
    parser.add_argument(
        "-e",
        "--show-empty",
        action="store_true",
        dest="show_empty",
        help="Show empty fields of ids",
    )
    parser.add_argument(
        "-f",
        "--full",
        action="store_true",
        help="Print all array elements (can be very slow for large data)",
    )
    parser.add_argument(
        "-c",
        "--compact",
        action="store_true",
        help="Print only names which has data",
    )
    args = parser.parse_args()
    splittedIdsInfo = args.uri.split("#")

    uri = splittedIdsInfo[0]
    idsName = ""
    idsPath = None
    occurrence = 0
    if len(splittedIdsInfo) == 2:
        idsFragment = splittedIdsInfo[1]

        splittedIdsFragment = idsFragment.split(":")
        idsName = splittedIdsFragment[0]
        if len(splittedIdsFragment) == 2:
            idsPathFragment = splittedIdsFragment[1]

            splittedIdsPathFragment = idsPathFragment.split("/", 1)
            occurrence = int(splittedIdsPathFragment[0])
            if len(splittedIdsPathFragment) == 2:
                idsPath = splittedIdsPathFragment[1]
    if idsName == "":
        logger.error("Please provide ids name at the end of uri with hash")
        exit(1)
    args.uri = uri
    connection = DBMaster.getConnection(args)
    if connection is None:
        logger.error("Please provide valid URI")
        exit(1)
    if args.full:
        numpy.set_printoptions(threshold=sys.maxsize)
    else:
        numpy.set_printoptions(threshold=10)

    if idsPath is None:
        ids = connection.get(idsName, occurrence)
        if args.compact:
            try:
                output = StringIO()
                sys.stdout = open(os.devnull, "w")

                ids.dump(print_empty=args.show_empty, file=output)

                sys.stdout = sys.__stdout__
                output.seek(0)

                for line in output.readlines():
                    if "[" in line and "]" not in line:
                        continue
                    if "]" in line and "[" not in line:
                        continue
                    if "]" in line and "[" in line and "." in line:
                        continue
                    if "class" in line:
                        continue
                    if "value" in line:
                        continue
                    if ":" in line:
                        line = line.split(":")[0] + "\n"
                    line = line.replace("Attribute", "")
                    line = line.replace("class", "")
                    line = line.replace("=", "")
                    line = line.replace("\t", "  ")
                    print(line, end="")
                output.close()
            except Exception as e:
                print(e)
        else:
            try:
                ids.dump(print_empty=args.show_empty)
            except Exception as e:
                print(ids)

    else:
        try:
            result = connection.partial_get(idsName, idsPath, occurrence)
        except Exception as exc:
            logger.error(exc)
            exit(1)

        resultType = type(result)
        print(f"Type: {resultType}")
        if result.__class__ == numpy.ndarray:
            print(f"Shape: {result.shape}")
            print(f"Data type: {result.dtype.name}")

        print("----------------------------------------------")
        if result.__class__ == numpy.ndarray and len(result) < 1:
            exit(0)

        print("----------------------------------------------")
        if (
            result.__class__ == numpy.ndarray
            and result[0].__class__.__module__ != "numpy"
        ):
            for i in range(len(result)):
                idsDump = result[i]
                print(idsDump)
                print("-------------------------")
        else:
            print(result)
    connection.close()
