#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Small utility script to profile performance of some AL operations on any dataset."""
import argparse
import copy
import os
import statistics as stat
import sys

from rich_argparse import RichHelpFormatter

import imas

from idstools import idsperf
from idstools.database import DBMaster
from idstools.utils.clihelper import dbentryParser

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="This script gives simple timing and performance information for different types of operations on IDS data with the IMAS Python Access Layer (get/get_slice/put depending on selected options)",
        parents=[dbentryParser],
        formatter_class=RichHelpFormatter,
    )
    timegroup = parser.add_mutually_exclusive_group()
    timegroup.add_argument(
        "-t",
        "--sliceTime",
        type=float,
        nargs="+",
        help="Use get_slice with selected time(s)",
    )
    timegroup.add_argument(
        "-a",
        "--allSlices",
        action="store_true",
        help="Use get_slice with all available times",
    )
    parser.add_argument(
        "-m",
        "--memoryBackend",
        action="store_true",
        help="Use MEMORY_BACKEND for this test (involve reading from file and loading in memory first)",
    )
    parser.add_argument(
        "-do",
        "--database_output",
        type=str,
        default=None,
        help="Database name for the destination data-entry",
    )
    parser.add_argument(
        "-bo",
        "--backend_output",
        type=str,
        help="Backend name for the destination data-entry",
    )
    parser.add_argument(
        "--repeat",
        type=int,
        default=1,
        help="Repeat timing n times (default: %(default)s)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Verbose mode, prints additional information",
    )
    parser.add_argument(
        "--showStats", action="store_true", help="Print addition stats for timings"
    )
    parser.add_argument(
        "--profile",
        action="store_true",
        help="Also do full profile of the selected operation, via cProfile",
    )
    parser.add_argument(
        "-o", "--outputRun", type=int, help="Output run number for checking perf of put"
    )
    parser.add_argument(
        "ids",
        nargs="*",
        type=str,
        help='IDS name(s) (leave empty to select all IDSs with default occurrence, or append "/n" to copy a specific occurrence "n")',
    )
    parser.add_argument(
        "-uriOut",
        "--uriOut",
        type=str,
        help="uri out \t\t(default=%(default)s)",
    )
    args = parser.parse_args()

    if not args.database_output:
        args.database_output = args.database

    if not args.backend_output:
        args.backend_output = args.backend
    # For memory backend need to read the full IDS and load it into memory
    if args.memoryBackend:
        print("First import data into memory...", file=sys.stderr)
        # sys.exit(1)
        dbref = DBMaster.getConnection(args)
        if dbref is None:
            print("----> Aborted.")
            exit(1)

        args.backend = "MEMORY"
        if "uri" in args.__dict__ and args.uri is not None:
            startIndex = args.uri.index(":") + 1
            endIndex = args.uri.index("?")

            # Replace the substring between ':' and '?' with 'memory'
            args.uri = args.uri[:startIndex] + "memory" + args.uri[endIndex:]
        dbm = DBMaster.createConnection(args)
        if dbm is None:
            print("----> Aborted.")
            exit(1)

        for idsname in args.ids:
            nameocc = idsname.split("/")
            idsname = nameocc[0]
            occ = 0
            if len(nameocc) == 2:
                occ = int(nameocc[1])
            dbm.put(dbref.get(idsname, occ))
        args.mode = "r"

    db = DBMaster.getConnection(args)
    if db is None:
        print("----> Aborted.")
        exit(1)

    if args.ids == []:
        allidss = [ids.value for ids in list(imas.IDSName)]
        # TODO: treat occurrences
        args.ids = [
            ids
            for ids in allidss
            if db.partial_get(ids, "ids_properties/homogeneous_time")
            != imas.imasdef.EMPTY_INT
        ]
    idsobj = None
    dbout = None

    # Set command
    if args.outputRun != None:
        dboutArgs = argparse.Namespace()
        dboutArgs.user = os.environ["USER"]
        dboutArgs.database = args.database_output
        dboutArgs.backend = args.backend_output
        dboutArgs.version = args.version
        dboutArgs.run = args.outputRun
        dboutArgs.pulse = args.pulse
        dboutArgs.uri = args.uri
        if args.uriOut is not None:
            dboutArgs.uri = args.uriOut
            if args.verbose:
                print("Using out URI given")
        else:
            if dboutArgs.uri is None:
                dboutArgs.uri = f"imas:{dboutArgs.backend.lower()}?user={dboutArgs.user};shot={dboutArgs.pulse};run={dboutArgs.run};database={dboutArgs.database};version={dboutArgs.version}"
            else:
                import re

                dboutArgs.uri = re.sub(
                    r"user=[^;]+", f"user={dboutArgs.user}", dboutArgs.uri
                )
                dboutArgs.uri = re.sub(
                    r"run=[^;]+", f"run={args.outputRun}", dboutArgs.uri
                )

        dbout = DBMaster.createConnection(dboutArgs)
        if dbout is None:
            print("----> Aborted.")
            exit(1)
        if args.verbose:
            print("Create pulse for put operation")

    for idsname in args.ids:
        nameocc = idsname.split("/")
        idsname = nameocc[0]
        occ = 0
        if len(nameocc) == 2:
            occ = int(nameocc[1])

        if args.allSlices:
            # TODO: might not be relevant if homogeneous_time != 1
            times = (db.partial_get(idsname, "time", occurrence=occ)).tolist()
        else:
            times = args.sliceTime

        timings = idsperf.get_timings(
            db,
            idsname,
            occ=occ,
            times=times,
            repeat=args.repeat,
            verbose=args.verbose,
            profile=args.profile,
        )

        if args.showStats and args.repeat > 1:
            print(f"All timings  = {timings}")
            print(f"Mean         = {stat.mean(timings)}")
            print(f"Standard dev = {stat.stdev(timings)}")
            print(f"Variance     = {stat.variance(timings)}")
        print(f"{idsname} best time = {min(timings)} s")
