#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
import sys

import numpy
from rich_argparse import RichHelpFormatter

try:
    import StringIO
except ImportError:
    from io import StringIO

from idstools.database import DBMaster
from idstools.utils.clihelper import dbentry_parser
from idstools.utils.idslogger import setup_logger

logger = setup_logger("module")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="""Prints content of an IDS onto the terminal\n 
        provide with fragment
        e.g. -u imas:hdf5?path=/home/ITER/fleuryl/public/imasdb/west/3/54914/4#wall or #wall:0/description_2d | less
        [previously known as idsdump and idsdumppath]""",
        formatter_class=RichHelpFormatter,
        parents=[dbentry_parser],
    )
    parser.add_argument(
        "-e",
        "--show-empty",
        action="store_true",
        dest="show_empty",
        help="Show empty fields of ids",
    )
    parser.add_argument(
        "-f",
        "--full",
        action="store_true",
        help="Print all array elements (can be very slow for large data)",
    )
    parser.add_argument(
        "-c",
        "--compact",
        action="store_true",
        help="Print only names which has data",
    )
    args = parser.parse_args()
    splitted_ids_info = args.uri.split("#")

    uri = splitted_ids_info[0]
    ids_name = ""
    ids_path = None
    occurrence = 0
    if len(splitted_ids_info) == 2:
        ids_fragment = splitted_ids_info[1]
        if ":" in ids_fragment:
            splitted_ids_fragment = ids_fragment.split(":")
            ids_name = splitted_ids_fragment[0]
            if len(splitted_ids_fragment) == 2:
                ids_path_fragment = splitted_ids_fragment[1]
                splitted_ids_path_fragment = ids_path_fragment.split("/", 1)
                occurrence = int(splitted_ids_path_fragment[0])
                if len(splitted_ids_path_fragment) == 2:
                    ids_path = splitted_ids_path_fragment[1]
        else:
            splitted_ids_fragment = ids_fragment.split("/", 1)
            ids_name = splitted_ids_fragment[0]
            if len(splitted_ids_fragment) == 2:
                ids_path = splitted_ids_fragment[1]
    if ids_name == "":
        logger.error("Please provide ids name at the end of uri with hash")
        exit(1)
    args.uri = uri
    connection = DBMaster.get_connection(args)
    if connection is None:
        logger.error("Please provide valid URI")
        exit(1)
    if args.full:
        numpy.set_printoptions(threshold=sys.maxsize)
    else:
        numpy.set_printoptions(threshold=10)

    if ids_path is None:
        ids = connection.get(ids_name, occurrence)
        if args.compact:
            try:
                output = StringIO()
                sys.stdout = open(os.devnull, "w")

                ids.dump(print_empty=args.show_empty, file=output)

                sys.stdout = sys.__stdout__
                output.seek(0)

                for line in output.readlines():
                    if "[" in line and "]" not in line:
                        continue
                    if "]" in line and "[" not in line:
                        continue
                    if "]" in line and "[" in line and "." in line:
                        continue
                    if "class" in line:
                        continue
                    if "value" in line:
                        continue
                    if ":" in line:
                        line = line.split(":")[0] + "\n"
                    line = line.replace("Attribute", "")
                    line = line.replace("class", "")
                    line = line.replace("=", "")
                    line = line.replace("\t", "  ")
                    print(line, end="")
                output.close()
            except Exception as e:
                print(e)
        else:
            try:
                ids.dump(print_empty=args.show_empty)
            except Exception as e:
                print(ids)

    else:
        try:
            result = connection.partial_get(ids_name, ids_path, occurrence)
        except Exception as exc:
            logger.error(exc)
            exit(1)

        result_type = type(result)
        print(f"Type: {result_type}")
        if result.__class__ == numpy.ndarray:
            print(f"Shape: {result.shape}")
            print(f"Data type: {result.dtype.name}")

        print("----------------------------------------------")
        if result.__class__ == numpy.ndarray and len(result) < 1:
            exit(0)

        print("----------------------------------------------")
        if result.__class__ == numpy.ndarray and result[0].__class__.__module__ != "numpy":
            for i in range(len(result)):
                ids_dump = result[i]
                print(ids_dump)
                print("-------------------------")
        else:
            print(result)
    connection.close()
