#!/usr/bin/env python3
import argparse
import logging
import os
import sys
from idstools.database import DBMaster

from rich_argparse import RichHelpFormatter

from idstools.compute.equilibrium import EquilibriumCompute
from idstools.utils.clihelper import getCoreVersion, imasParser
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module", stdout_level=logging.INFO)

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Rescaling an equilibrium magnetic field, storing the output into another entry of the same DB. replaced by ids_rescale_eq",
    parents=[imasParser],
    formatter_class=RichHelpFormatter,
)
if getCoreVersion() > 4:
    parser.add_argument(
        "-su",
        "--src",
        type=str,
        help="source uri \t\t(default=%(default)s)",
    )
    parser.add_argument(
        "-du",
        "--dest",
        type=str,
        help="destination uri \t\t(default=%(default)s)",
    )
        
parser.add_argument("-sp", "--src_pulse", help="Source pulse number", type=int)
parser.add_argument("-sr", "--src_run", help="Source run number", type=int)
parser.add_argument("-dp", "--dest_pulse", help="Destination pulse number", type=int)
parser.add_argument("-dr", "--dest_run", help="Destination run number", type=int)
parser.add_argument(
    "-destd",
    "--dest_database",
    type=str,
    default=None,
    help="Database name for the destination data-entry",
)
parser.add_argument(
    "-destb",
    "--dest_backend",
    type=str,
    help="Backend name for the destination data-entry",
)
parser.add_argument(
    "--rescale",
    help="Rescaling factor of the equilibrium magnetic field",
    type=float,
    required=True,
)

args = parser.parse_args()

if args.dest_database == None:
    args.dest_database = args.database

if args.dest_backend == None:
    args.dest_backend = args.backend

rescale = args.rescale

if rescale == 0:
    logger.critical("Rescale factor cannot be zero!")
    sys.exit(1)

            
# OPEN INPUT
inputargs = argparse.Namespace()
inputargs.backend = args.backend
inputargs.pulse = args.src_pulse
inputargs.run = args.src_run
inputargs.user = args.user
inputargs.database = args.database
inputargs.version = args.version
if getCoreVersion() > 4:
    inputargs.uri = args.src
connection = DBMaster.getConnection(inputargs)
if connection is None:
    print("Error opening source pulse! Please check existence.")
    sys.exit()

idsEquilibrium = connection.get("equilibrium")

outputargs = argparse.Namespace()
outputargs.backend = args.dest_backend
outputargs.pulse = args.dest_pulse
outputargs.run = args.dest_run
outputargs.user = os.environ["USER"]
outputargs.database = args.dest_database
outputargs.version = args.version
if getCoreVersion() > 4:
    outputargs.mode="w"
    outputargs.uri = args.dest
        
outputConnection = DBMaster.getConnection(outputargs)
if outputConnection is None:
    outputConnection = DBMaster.createConnection(outputargs)
    if outputConnection is None:
        sys.exit()
        

logger.info(f"Rescaling equilibrium magnetic field by {rescale}")
equilibriumCompute = EquilibriumCompute(idsEquilibrium)
equout = equilibriumCompute.rescale(rescale)

# PUT IDS INTO OUTPUT
outputConnection.put(equout)

# CLOSE FILES
connection.close()
outputConnection.close()

logger.info(f"Equilibrium IDS is rescaled successfully.")
if getCoreVersion() > 4:
    if args.dest is not None:
        logger.info(
        f"Output database details {args.dest}"
    )
    else:
        logger.info(
        f"Output database details database={args.dest_database}, pulse={args.dest_pulse}, run={args.dest_run}, user={os.environ['USER']}"
    )
else:
    logger.info(
        f"Output database details database={args.dest_database}, pulse={args.dest_pulse}, run={args.dest_run}, user={os.environ['USER']}"
    )
