#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import sys

import imaspy as imas
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.utils.idshelper import get_ids_types, resample_indices, resample_times

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Resample IDSs from a data-entry and save them into another data-entry "
        "[previously known as ids_resampling]",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "-s",
        "--src",
        type=str,
        required=True,
        help="source uri",
    )
    parser.add_argument(
        "-d",
        "--dest",
        type=str,
        required=True,
        help="destination uri",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--index-range",
        type=str,
        help="Specified range of slices index as 'start,stop,step'. If omitted, start=0, stop=len(timebase),step=1,"
        " e.g. '0,,10' to keep 1 every 10 slices. Works only for IDS with homogeneous timebase. (Default)",
    )
    group.add_argument(
        "--time-range",
        type=str,
        help="Specified range of times as 'start,stop,step'. If omitted, start=time[0], stop=time[-1]), while "
        "omitting step will keep of slices between start and stop, e.g. '10.,50.,' to keep all times between 10. "
        "and 50. secondes). Works only for IDS with homogeneous timebase unless all three values are specified.",
    )
    parser.add_argument(
        "ids",
        nargs="*",
        type=str,
        help="IDSs to resample (leave empty to resample all)",
    )
    args = parser.parse_args()

    if args.src is not None and args.dest is not None:
        if args.src == args.dest:
            print("Can not use the same uri as source and destination!")
            exit()

    if args.ids == []:
        args.ids = get_ids_types()

    inputargs = argparse.Namespace()
    inputargs.uri = args.src
    src = DBMaster.get_connection(inputargs)
    if src is None:
        print("Error opening source pulse! Please check existence.")
        sys.exit()

    tmp = imas.DBEntry("imas:memory?path=tmp/1/1", "w")

    if tmp is None:
        print("Error creating temporary data-entry in memory!", file=sys.stderr)
        sys.exit(1)

    outputargs = argparse.Namespace()
    outputargs.mode = "w"
    outputargs.uri = args.dest
    dest = DBMaster.create_connection(outputargs)
    if dest is None:
        print("Error creating pulse! Please check existence.")
        sys.exit()
    for ids_name in args.ids:
        idsobj = None
        try:
            idsobj = src.get(ids_name)
        except Exception as _:  # noqa: F841
            pass
        if idsobj:
            homogeneous_time = idsobj.ids_properties.homogeneous_time

            if homogeneous_time == 1:
                if args.time_range is None:  # index range
                    if args.index_range is None:
                        args.index_range = ",,"
                    time_range = args.index_range.split(",")
                    start = int(time_range[0]) if time_range[0] != "" else 0
                    stop = int(time_range[1]) if time_range[1] != "" else None
                    step = int(time_range[2]) if time_range[2] != "" else 1
                    print(f"resampling indices :{ids_name} with {start}, {stop}, {step}")
                    if start == stop:
                        print(f"Please provide range. start={start} and stop={stop} are the same", file=sys.stderr)
                        exit(0)
                    resample_indices(src, tmp, ids_name, start=start, stop=stop, step=step)
                else:
                    time_range = args.time_range.split(",")
                    start = float(time_range[0]) if time_range[0] != "" else idsobj.time[0]
                    stop = float(time_range[1]) if time_range[1] != "" else idsobj.time[-1]
                    step = float(time_range[2]) if time_range[2] != "" else 1.0
                    print(f"resampling times :{ids_name} with {start}, {stop}, {step}")
                    if start == stop:
                        print(f"Please provide range. start={start} and stop={stop} are the same", file=sys.stderr)
                        exit(0)
                    try:
                        resample_times(src, tmp, ids_name, start=start, stop=stop, step=step)
                    except Exception as e:  # noqa: F841
                        print(f"Error resampling times for {ids_name} : {e}")
                        continue
            elif homogeneous_time == 0:
                if args.time_range is not None:
                    time_range = args.time_range.split(",")
                    if time_range[0] != "" and time_range[1] != "" and time_range[2] != "":
                        print(f"resampling times :{ids_name}")
                        resample_times(
                            src,
                            tmp,
                            ids_name,
                            start=time_range[0],
                            stop=time_range[1],
                            step=time_range[2],
                        )
                    else:
                        print(
                            f"Skipping IDS {ids_name} because its homogeneous_time={homogeneous_time}",
                            file=sys.stderr,
                        )
                        continue
                else:
                    print(
                        f"Skipping IDS {ids_name} because its homogeneous_time={homogeneous_time}",
                        file=sys.stderr,
                    )
                    continue
            else:
                # print(f'Skipping IDS {idsname} because its homogeneous_time={homogeneous}',file=sys.stderr)
                continue

            dest.put(tmp.get(ids_name))
