#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import getpass
import sys

import imas
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.utils.clihelper import getCoreVersion
from idstools.utils.idshelper import resampleIndices, resampleTimes

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Resample IDSs from a data-entry and save them into another data-entry [previously known as ids_resampling]",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "-s",
        "--src",
        type=str,
        required=True,
        help="source uri",
    )
    parser.add_argument(
        "-d",
        "--dest",
        type=str,
        required=True,
        help="destination uri",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--index-range",
        type=str,
        help='Specified range of slices index as "start,stop,step". If omitted, start=0, stop=len(timebase),step=1, e.g. "0,,10" to keep 1 every 10 slices. Works only for IDS with homogeneous timebase. (Default)',
    )
    group.add_argument(
        "--time-range",
        type=str,
        help='Specified range of times as "start,stop,step". If omitted, start=time[0], stop=time[-1]), while omitting step will keep of slices between start and stop, e.g. "10.,50.," to keep all times between 10. and 50. secondes). Works only for IDS with homogeneous timebase unless all three values are specified.',
    )
    parser.add_argument(
        "ids",
        nargs="*",
        type=str,
        help="IDSs to resample (leave empty to resample all)",
    )
    args = parser.parse_args()

    if args.src is not None and args.dest is not None:
        if args.src == args.dest:
            print("Can not use the same uri as source and destination!")
            exit()

    if args.ids == []:
        args.ids = [ids.value for ids in list(imas.IDSName)]

    inputargs = argparse.namespace()
    inputargs.uri = args.src
    src = DBMaster.get_connection(inputargs)
    if src is None:
        print("Error opening source pulse! Please check existence.")
        sys.exit()

    if get_core_version() > 4:
        tmp = imas.DBEntry("imas:memory?path=tmp/1/1", "w")
    else:
        tmp = imas.DBEntry(imas.imasdef.m_e_m_o_r_y__b_a_c_k_e_n_d, "tmp", 1, 1)
    status, _ = tmp.create()
    if status != 0:
        print("Error creating temporary data-entry in memory!", file=sys.stderr)
        sys.exit(status)

    outputargs = argparse.namespace()
    outputargs.mode = "w"
    outputargs.uri = args.dest
    dest = DBMaster.create_connection(outputargs)
    if dest is None:
        print("Error creating pulse! Please check existence.")
        sys.exit()

    for ids_name in args.ids:
        homogeneous_time = src.partial_get(ids_name, "ids_properties/homogeneous_time")
        if homogeneous_time == 1:
            if args.time_range is None:
                if args.index_range is None:
                    args.index_range = ",,"
                time_range = args.index_range.split(",")
                start = int(time_range[0]) if time_range[0] != "" else 0
                stop = int(time_range[1]) if time_range[1] != "" else None
                step = int(time_range[2]) if time_range[2] != "" else 1
                print(f"resampling indices :{ids_name}")
                resample_indices(src, tmp, ids_name, start=start, stop=stop, step=step)
            else:
                time_range = args.time_range.split(",")
                start = int(time_range[0]) if time_range[0] != "" else 0
                stop = int(time_range[1]) if time_range[1] != "" else None
                step = int(time_range[2]) if time_range[2] != "" else 1
                print(f"resampling times :{ids_name}")
                resample_times(src, tmp, ids_name, start=start, stop=stop, step=step)
        elif homogeneous_time == 0:
            if args.time_range != None:
                time_range = args.time_range.split(",")
                if time_range[0] != "" and time_range[1] != "" and time_range[2] != "":
                    print(f"resampling times :{ids_name}")
                    resample_times(
                        src,
                        tmp,
                        ids_name,
                        start=time_range[0],
                        stop=time_range[1],
                        step=time_range[2],
                    )
                else:
                    print(
                        f"Skipping IDS {ids_name} because its homogeneous_time={homogeneous_time}",
                        file=sys.stderr,
                    )
                    continue
            else:
                print(
                    f"Skipping IDS {ids_name} because its homogeneous_time={homogeneous_time}",
                    file=sys.stderr,
                )
                continue
        else:
            # print(f'Skipping IDS {idsname} because its homogeneous_time={homogeneous}',file=sys.stderr)
            continue

        dest.put(tmp.get(ids_name))
