#!/usr/bin/env python3
import argparse
import logging
import os
import sys

import imas
from rich_argparse import RichHelpFormatter

from idstools.compute.equilibrium import EquilibriumCompute
from idstools.utils.clihelper import getBackendID, imasParser
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module", stdout_level=logging.INFO)

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Rescaling an equilibrium magnetic field, storing the output into another entry of the same DB. replaced by ids_rescale_eq",
    parents=[imasParser],
    formatter_class=RichHelpFormatter,
)
parser.add_argument(
    "-si", "--shot_input", help="Input shot number", required=True, type=int
)
parser.add_argument(
    "-ri", "--run_input", help="Input run number", required=True, type=int
)
parser.add_argument(
    "-so", "--shot_output", help="Output shot number", required=True, type=int
)
parser.add_argument(
    "-ro", "--run_output", help="Output run number", required=True, type=int
)
parser.add_argument(
    "-do",
    "--database_output",
    type=str,
    default=None,
    help="Database name for the destination data-entry",
)
parser.add_argument(
    "-bo",
    "--backend_output",
    type=str,
    help="Backend name for the destination data-entry",
)
parser.add_argument(
    "--rescale",
    help="Rescaling factor of the equilibrium magnetic field",
    type=float,
    required=True,
)

args = parser.parse_args()

if args.database_output == None:
    args.database_output = args.database

if args.backend_output == None:
    args.backend_output = args.backend

rescale = args.rescale

if rescale == 0:
    logger.critical("Rescale factor cannot be zero!")
    sys.exit(1)

# OPEN INPUT
connection = imas.DBEntry(
    getBackendID(args.backend),
    args.database,
    args.shot_input,
    args.run_input,
    args.user,
)
status, _ = connection.open()
if status != 0:
    logger.critical("Can't open the input pulse file!")
    sys.exit(1)

idsEquilibrium = connection.get("equilibrium")

# OPEN OUTPUT
outputConnection = imas.DBEntry(
    getBackendID(args.backend),
    args.database_output,
    args.shot_output,
    args.run_output,
    user_name=os.environ["USER"],
)
status, _ = outputConnection.open()
if status != 0:
    logger.warning("Can't open the output pulse file!, Trying to create a new one")
    status, _ = outputConnection.create()
    if status != 0:
        logger.critical("Can't create the output pulse file!")
        sys.exit(1)

logger.info(f"Rescaling equilibrium magnetic field by {rescale}")
equilibriumCompute = EquilibriumCompute(idsEquilibrium)
equout = equilibriumCompute.rescale(rescale)

# PUT IDS INTO OUTPUT
outputConnection.put(equout)

# CLOSE FILES
connection.close()
outputConnection.close()

logger.info(f"Equilibrium IDS is rescaled successfully.")
logger.info(
    f"Output database details database={args.database_output}, shot={args.shot_output}, run={args.run_output}, user={os.environ['USER']}"
)
