#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import sys
from idstools.database import DBMaster

import imas

from idstools.utils.clihelper import getIMASVersion, imasParser
from idstools.utils.idshelper import resampleIndices, resampleTimes

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Resample IDSs from a data-entry and save them into another data-entry",
        parents=[imasParser],
    )
    if getIMASVersion() > 4:
        parser.add_argument(
            "-iuri",
            "--input_uri",
            type=str,
            help="input uri \t\t(default=%(default)s)",
        )
        parser.add_argument(
            "-ouri",
            "--output_uri",
            type=str,
            help="output uri \t\t(default=%(default)s)",
        )

    parser.add_argument("-si", "--pulse_input", help="Input pulse number", type=int)
    parser.add_argument("-ri", "--run_input", help="Input run number", type=int)
    parser.add_argument("-so", "--pulse_output", help="Output pulse number", type=int)
    parser.add_argument("-ro", "--run_output", help="Output run number", type=int)
    # default user from parent parser is 'public',
    # which is fine for exploration scripts but less
    # for management scripts
    parser.set_defaults(user=os.environ["USER"])
    parser.add_argument(
        "-do",
        "--database_output",
        type=str,
        default=None,
        help="Database name for the destination data-entry",
    )
    parser.add_argument(
        "-bo",
        "--backend_output",
        type=str,
        help="Backend name for the destination data-entry",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--index-range",
        type=str,
        help='Specified range of slices index as "start,stop,step". If omitted, start=0, stop=len(timebase),step=1, e.g. "0,,10" to keep 1 every 10 slices. Works only for IDS with homogeneous timebase. (Default)',
    )
    group.add_argument(
        "--time-range",
        type=str,
        help='Specified range of times as "start,stop,step". If omitted, start=time[0], stop=time[-1]), while omitting step will keep of slices between start and stop, e.g. "10.,50.," to keep all times between 10. and 50. secondes). Works only for IDS with homogeneous timebase unless all three values are specified.',
    )
    parser.add_argument(
        "ids",
        nargs="*",
        type=str,
        help="IDSs to resample (leave empty to resample all)",
    )
    args = parser.parse_args()

    if args.database_output is None:
        args.database_output = args.database

    if args.backend_output is None:
        args.backend_output = args.backend

    isUriCheckDone = False
    if getIMASVersion() > 4:
        if args.input_uri is not None and args.output_uri is not None:
            isUriCheckDone = True
            if args.input_uri == args.output_uri:
                print("Can not use the same uri as source and destination!")
                exit()
    if isUriCheckDone is False:
        if (
            args.pulse_input == args.pulse_output
            and args.run_input == args.run_output
            and args.user == os.environ["USER"]
            and args.database == args.database_output
            and args.backend == args.backend_output
        ):
            print(
                "Can not use the same data-entry as source and destination!",
                file=sys.stderr,
            )
            exit()

    if args.ids == []:
        args.ids = [ids.value for ids in list(imas.IDSName)]

    inputargs = argparse.Namespace()
    inputargs.backend = args.backend
    inputargs.pulse = args.pulse_input
    inputargs.run = args.run_input
    inputargs.user = args.user
    inputargs.database = args.database
    inputargs.version = args.version
    if getIMASVersion() > 4:
        if args.input_uri is None:
            inputargs.uri = f"imas:{args.backend.lower()}?user={args.user };shot={args.pulse_input};run={args.run_input};database={args.database};version={args.version}"
        else:
            inputargs.uri = args.input_uri
    src = DBMaster.getConnection(inputargs)
    if src is None:
        print("Error opening source pulse! Please check existence.")
        sys.exit()

    if getIMASVersion() > 4:
        # tmp = imas.DBEntry("imas:memory?user=;shot=q;run=q;database=tmp;version=", "w")
        tmp = imas.DBEntry(imas.imasdef.MEMORY_BACKEND, "tmp", 1, 1)
    else:
        tmp = imas.DBEntry(imas.imasdef.MEMORY_BACKEND, "tmp", 1, 1)
    status, _ = tmp.create()
    if status != 0:
        print("Error creating temporary data-entry in memory!", file=sys.stderr)
        sys.exit(status)

    outputargs = argparse.Namespace()
    outputargs.backend = args.backend_output
    outputargs.pulse = args.pulse_output
    outputargs.run = args.run_output
    outputargs.user = os.environ["USER"]
    outputargs.database = args.database_output
    outputargs.version = args.version
    if getIMASVersion() > 4:
        if args.output_uri is None:
            outputargs.uri = f"imas:{args.backend_output.lower()}?user={os.environ['USER']};shot={args.pulse_output};run={args.run_output};database={args.database_output};version={args.version}"
        else:
            outputargs.uri = args.output_uri
    dest = DBMaster.getConnection(outputargs)
    if dest is None:
        print("Error creating pulse! Please check existence.")
        sys.exit()

    for idsName in args.ids:
        homogeneousTime = src.partial_get(idsName, "ids_properties/homogeneous_time")
        if homogeneousTime == 1:
            if args.time_range is None:
                if args.index_range is None:
                    args.index_range = ",,"
                timeRange = args.index_range.split(",")
                start = int(timeRange[0]) if timeRange[0] != "" else 0
                stop = int(timeRange[1]) if timeRange[1] != "" else None
                step = int(timeRange[2]) if timeRange[2] != "" else 1
                print(f"resampling indices :{idsName}")
                resampleIndices(src, tmp, idsName, start=start, stop=stop, step=step)
            else:
                timeRange = args.time_range.split(",")
                start = int(timeRange[0]) if timeRange[0] != "" else 0
                stop = int(timeRange[1]) if timeRange[1] != "" else None
                step = int(timeRange[2]) if timeRange[2] != "" else 1
                print(f"resampling times :{idsName}")
                resampleTimes(src, tmp, idsName, start=start, stop=stop, step=step)
        elif homogeneousTime == 0:
            if args.time_range != None:
                timeRange = args.time_range.split(",")
                if timeRange[0] != "" and timeRange[1] != "" and timeRange[2] != "":
                    print(f"resampling times :{idsName}")
                    resampleTimes(
                        src,
                        tmp,
                        idsName,
                        start=timeRange[0],
                        stop=timeRange[1],
                        step=timeRange[2],
                    )
                else:
                    print(
                        f"Skipping IDS {idsName} because its homogeneous_time={homogeneousTime}",
                        file=sys.stderr,
                    )
                    continue
            else:
                print(
                    f"Skipping IDS {idsName} because its homogeneous_time={homogeneousTime}",
                    file=sys.stderr,
                )
                continue
        else:
            # print(f'Skipping IDS {idsname} because its homogeneous_time={homogeneous}',file=sys.stderr)
            continue

        dest.put(tmp.get(idsName))
