#!/usr/bin/env python3
import argparse
import logging
import os
import sys
from idstools.database import DBMaster

from rich_argparse import RichHelpFormatter

from idstools.compute.equilibrium import EquilibriumCompute
from idstools.utils.clihelper import getIMASVersion, imasParser
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module", stdout_level=logging.INFO)

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Rescaling an equilibrium magnetic field, storing the output into another entry of the same DB. replaced by ids_rescale_eq",
    parents=[imasParser],
    formatter_class=RichHelpFormatter,
)
if getIMASVersion() > 4:
    parser.add_argument(
        "-iuri",
        "--input_uri",
        type=str,
        help="input uri \t\t(default=%(default)s)",
    )
    parser.add_argument(
        "-ouri",
        "--output_uri",
        type=str,
        help="output uri \t\t(default=%(default)s)",
    )
        
parser.add_argument(
    "-pi", "--pulse_input", help="Input pulse number", type=int
)
parser.add_argument(
    "-ri", "--run_input", help="Input run number", type=int
)
parser.add_argument(
    "-po", "--pulse_output", help="Output pulse number", type=int
)
parser.add_argument(
    "-ro", "--run_output", help="Output run number", type=int
)
parser.add_argument(
    "-do",
    "--database_output",
    type=str,
    default=None,
    help="Database name for the destination data-entry",
)
parser.add_argument(
    "-bo",
    "--backend_output",
    type=str,
    help="Backend name for the destination data-entry",
)
parser.add_argument(
    "--rescale",
    help="Rescaling factor of the equilibrium magnetic field",
    type=float,
    required=True,
)

args = parser.parse_args()

if args.database_output == None:
    args.database_output = args.database

if args.backend_output == None:
    args.backend_output = args.backend

rescale = args.rescale

if rescale == 0:
    logger.critical("Rescale factor cannot be zero!")
    sys.exit(1)

            
# OPEN INPUT
inputargs = argparse.Namespace()
inputargs.backend = args.backend
inputargs.pulse = args.pulse_input
inputargs.run = args.run_input
inputargs.user = args.user
inputargs.database = args.database
inputargs.version = args.version
if getIMASVersion() > 4:
    inputargs.uri = args.input_uri
connection = DBMaster.getConnection(inputargs)
if connection is None:
    print("Error opening source pulse! Please check existence.")
    sys.exit()

idsEquilibrium = connection.get("equilibrium")

outputargs = argparse.Namespace()
outputargs.backend = args.backend_output
outputargs.pulse = args.pulse_output
outputargs.run = args.run_output
outputargs.user = os.environ["USER"]
outputargs.database = args.database_output
outputargs.version = args.version
if getIMASVersion() > 4:
    outputargs.mode="w"
    outputargs.uri = args.output_uri
        
outputConnection = DBMaster.getConnection(outputargs)
if outputConnection is None:
    outputConnection = DBMaster.createConnection(outputargs)
    if outputConnection is None:
        sys.exit()
        

logger.info(f"Rescaling equilibrium magnetic field by {rescale}")
equilibriumCompute = EquilibriumCompute(idsEquilibrium)
equout = equilibriumCompute.rescale(rescale)

# PUT IDS INTO OUTPUT
outputConnection.put(equout)

# CLOSE FILES
connection.close()
outputConnection.close()

logger.info(f"Equilibrium IDS is rescaled successfully.")
if getIMASVersion() > 4:
    if args.output_uri is not None:
        logger.info(
        f"Output database details {args.output_uri}"
    )
    else:
        logger.info(
        f"Output database details database={args.database_output}, pulse={args.pulse_output}, run={args.run_output}, user={os.environ['USER']}"
    )
else:
    logger.info(
        f"Output database details database={args.database_output}, pulse={args.pulse_output}, run={args.run_output}, user={os.environ['USER']}"
    )
