#! /usr/bin/env python3
# -*- coding: utf-8 -*-

"""Show size and time of IDSs.
Author : David.Coster@ipp.mpg.de

The module retrieves the size of IDS objects from a database entry and shows IDS size in bytes and the time taken to read each object. 
It also shows total size of all IDS objects in the data entry. It shows total time taken to read all objects from the data entry

Example:
    Following is the example how to use dbsize module
    literal blocks::

        $ python scripts/idssize -p 122525 -r 1
        Examining data for public, ITER, 3, 122525, 1
        Reading 0.001 MB of data for dataset_description/0 took 0.00 seconds
        Reading 0.003 MB of data for divertors/0 took 0.02 seconds
        Reading 35.431 MB of data for edge_profiles/0 took 5.58 seconds
        Reading 27.630 MB of data for edge_sources/0 took 5.62 seconds
        Reading 14.335 MB of data for edge_transport/0 took 4.48 seconds
        Reading 3.057 MB of data for equilibrium/0 took 0.02 seconds
        Reading 5.578 MB of data for radiation/0 took 3.94 seconds
        Reading 0.016 MB of data for summary/0 took 0.12 seconds
        Reading 0.011 MB of data for wall/0 took 0.01 seconds
        Total reading time = 19.79 s
        Total data size =  86.1 MB
        Fractions of the total size for public/ITER/3/122525/1
        % bytes    IDS
         0.00 %    dataset_description/0
         0.00 %    divertors/0
        41.17 %    edge_profiles/0
        32.11 %    edge_sources/0
        16.66 %    edge_transport/0
         3.55 %    equilibrium/0
         6.48 %    radiation/0
         0.02 %    summary/0
         0.01 %    wall/0


Attributes:
    pulse (int): pulse number
    run (int): run number

Todo:
    * TODOs

"""


import argparse

import imas
import numpy as np
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.utils.clihelper import dbentryParser, getCoreVersion
from idstools.utils.idshelper import getIDSSize

parser = argparse.ArgumentParser(
    description="Show size and time of IDSs [previously knwon as analyze_db_sizes]",
    epilog="""
""",
    formatter_class=RichHelpFormatter,
    parents=[dbentryParser],
)

parser.add_argument(
    "ids",
    nargs="*",
    type=str,
    help="Name (or space separated list of names) of IDS to (leave empty to show size of all IDSs)",
)
args = parser.parse_args()

connection = DBMaster.getConnection(args)
if connection is None:
    print("----> Aborted.")
    exit(1)

if args.ids == []:
    args.ids = [ids.value for ids in list(imas.IDSName)]

idsSizeDict = getIDSSize(connection, args.ids)
totalBytes = np.array([v["bytes"] for v in idsSizeDict.values()]).sum()
totalTime = np.array([v["time"] for v in idsSizeDict.values()]).sum()

print(f"Total reading time = {totalTime:0.2f} s")

print(f"Total data size = {totalBytes/1024**2:5.1f} MB")
if getCoreVersion() > 4:
    if args.uri is not None:
        print(f"Fractions of the total size for {args.uri}")
    else:
        print(
            f"Fractions of the total size for {args.user}/{args.database}/{args.version}/{args.pulse}/{args.run}"
        )
else:
    print(
        f"Fractions of the total size for {args.user}/{args.database}/{args.version}/{args.pulse}/{args.run}"
    )
print("% bytes    IDS")
for idsSize in idsSizeDict:
    bytesData = idsSizeDict[idsSize]["bytes"] / totalBytes * 100
    print(f"{bytesData:5.2f} %    {idsSize}")
