#!/usr/bin/env python3
# ids_shift_eq -pi 131035 -ri 124 -po 123001 -ro 1 --shift -0.01 -u bonninx -d iter

import argparse
import logging
import os
import sys
from idstools.database import DBMaster

from rich_argparse import RichHelpFormatter

from idstools.compute.equilibrium import EquilibriumCompute
from idstools.utils.idslogger import setupLogger

logger = setupLogger("module", stdout_level=logging.INFO)
#

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Rigidly shifts vertically an equilibrium, storing the output into another entry of the same DB. replaced by ids_shift_eq",
    formatter_class=RichHelpFormatter,
)
parser.add_argument(
    "-s",
    "--src",
    type=str,
    required=True,
    help="source uri",
)
parser.add_argument(
    "-d",
    "--dest",
    type=str,
    required=True,
    help="destination uri",
)


parser.add_argument(
    "--shift", help="Upward shift of equilibrium (m)", type=float, required=True
)

args = parser.parse_args()

shiftParam = args.shift

# OPEN INPUT
inputargs = argparse.Namespace()
inputargs.uri = args.src
connection = DBMaster.getConnection(inputargs)
if connection is None:
    sys.exit()

idsEquilibrium = connection.get("equilibrium")

outputargs = argparse.Namespace()
outputargs.mode = "w"
outputargs.uri = args.dest

outputConnection = DBMaster.getConnection(outputargs)
if outputConnection is None:
    outputConnection = DBMaster.createConnection(outputargs)
    if outputConnection is None:
        sys.exit()


logger.info(f"Shifting equilibrium by {shiftParam} m")
logger.info(
    "Values for wall gaps, locations of strike-points and closest wall points are no longer guaranteed!"
)
equilibriumCompute = EquilibriumCompute(idsEquilibrium)
equout = equilibriumCompute.z_shift(shiftParam)

# PUT IDS INTO OUTPUT
outputConnection.put(equout)

# CLOSE FILES
connection.close()
outputConnection.close()
logger.info("Equilibrium IDS is upward shifted successfully.")

if args.dest is not None:
    logger.info(f"Output database details {args.dest}")
else:
    logger.info(
        f"Output database details database={args.dest_database}, pulse={args.dest_pulse}, run={args.dest_run}, user={os.environ['USER']}"
    )
