#!/usr/bin/env python3
# ids_shift_eq -pi 131035 -ri 124 -po 123001 -ro 1 --shift -0.01 -u bonninx -d iter

import argparse
import logging
import os
import sys
from idstools.database import DBMaster

from rich_argparse import RichHelpFormatter

from idstools.compute.equilibrium import EquilibriumCompute
from idstools.utils.idslogger import setupLogger

logger = setup_logger("module", stdout_level=logging.i_n_f_o)
#

# Management of input arguments
parser = argparse.argument_parser(
    description="Rigidly shifts vertically an equilibrium, storing the output into another entry of the same DB. replaced by ids_shift_eq",
    formatter_class=rich_help_formatter,
)
parser.add_argument(
    "-s",
    "--src",
    type=str,
    required=True,
    help="source uri",
)
parser.add_argument(
    "-d",
    "--dest",
    type=str,
    required=True,
    help="destination uri",
)


parser.add_argument(
    "--shift", help="Upward shift of equilibrium (m)", type=float, required=True
)

args = parser.parse_args()

shift_param = args.shift

# OPEN INPUT
inputargs = argparse.namespace()
inputargs.uri = args.src
connection = d_b_master.get_connection(inputargs)
if connection is None:
    sys.exit()

ids_equilibrium = connection.get("equilibrium")

outputargs = argparse.namespace()
outputargs.mode = "w"
outputargs.uri = args.dest

output_connection = d_b_master.get_connection(outputargs)
if output_connection is None:
    output_connection = d_b_master.create_connection(outputargs)
    if output_connection is None:
        sys.exit()


logger.info(f"Shifting equilibrium by {shift_param} m")
logger.info(
    "Values for wall gaps, locations of strike-points and closest wall points are no longer guaranteed!"
)
equilibrium_compute = equilibrium_compute(ids_equilibrium)
equout = equilibrium_compute.z_shift(shift_param)

# PUT IDS INTO OUTPUT
output_connection.put(equout)

# CLOSE FILES
connection.close()
output_connection.close()
logger.info("Equilibrium IDS is upward shifted successfully.")

if args.dest is not None:
    logger.info(f"Output database details {args.dest}")
else:
    logger.info(
        f"Output database details database={args.dest_database}, pulse={args.dest_pulse}, run={args.dest_run}, user={os.environ['USER']}"
    )
