#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import platform
import sys

from idstools import __version__


def display_version():
    compiled_status = "yes" if getattr(sys, "frozen", False) else "no"
    python_info = f"{platform.python_implementation()} {platform.python_version()}"
    print(f"idstools, {__version__} (compiled: {compiled_status})")
    print(f"Python {python_info}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="idstools CLI")
    parser.add_argument("--version", action="store_true", help="Show version information")
    args = parser.parse_args()

    if args.version:
        display_version()
        sys.exit(0)
