#!/usr/bin/env python3

import argparse
from idstools.machinedescription import MachineDescription

# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Show status and potential parent and children for a given simulation stored in ITER machine description database folder"
)
parser.add_argument(
    "-f",
    "--folder",
    help="folder where to search for machine description data",
    required=False,
)
parser.add_argument("-s", "--shot", help="shot number", required=True, type=int)

parser.add_argument(
    "-r",
    "--run",
    help="run number",
    required=True,
    type=int,
)
args = vars(parser.parse_args())
shot = args["shot"]
run = args["run"]


# FOLDER
if args["folder"] != None:
    machineDescriptionFolder = args["folder"]
else:
    machineDescriptionFolder = "/work/imas/shared/imasdb/ITER_MD/3"

mdObject = MachineDescription(machineDescriptionFolder)

if not mdObject.checkIfExist(shot, run):
    print(f"Data entry {shot}/{run} does not exist")
    exit()


family = mdObject.getFamily(shot, run)

print("-----------------------------------------------------------------")
print(f"  {'DATASET':<10}\t{'STATUS':<10}\tREASON WHY IT REPLACES PREVIOUS")
print("-----------------------------------------------------------------")
for iparent in range(len(family["parents"]["shot"])):
    shotInfo = family["parents"]["shot"][iparent]
    runInfo = family["parents"]["run"][iparent]
    status = family["parents"]["status"][iparent]
    reason_for_replacement = family["parents"]["reason_for_replacement"][iparent]
    shotLen = len(family["parents"]["shot"][iparent])
    runLen = len(family["parents"]["run"][iparent])
    print(f"  {shotInfo:<6} {runInfo:<4}\t{status:<10}\t{reason_for_replacement}")

mdstatus = mdObject.getStatus(shot, run)
mdreason_for_replacement = mdObject.getReasonForReplacement(shot, run)
print(f"* {shot:<6} {run:<4}\t{mdstatus:<10}\t{mdreason_for_replacement}")

for ichild in range(len(family["children"]["shot"])):
    shotInfo = family["children"]["shot"][ichild]
    runInfo = family["children"]["run"][ichild]
    status = family["children"]["status"][ichild]
    reason_for_replacement = family["children"]["reason_for_replacement"][ichild]
    shotLen = len(family["children"]["shot"][ichild])
    runLen = len(family["children"]["run"][ichild])
    print(f"  {shotInfo:<6} {runInfo:<4}\t{status:<10}\t{reason_for_replacement}")
print("-----------------------------------------------------------------")
