#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# python scripts/plotequilibrium -p 134174 -r 117
# -md "imas:mdsplus?user=public;shot=116000;run=2;database=ITER_MD;version=3#wall"
# "imas:mdsplus?user=public;shot=111001;run=102;database=ITER_MD;version=3#pf_active"

import argparse
import copy
import logging
import os

import imas
from rich_argparse import RichHelpFormatter

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idshelper import getAvailableIdsAndTimes
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.equilibrium import EquilibriumView
from idstools.view.pf_active import PFActiveView
from idstools.view.wall import WallView


class md_action(argparse.action):
    def __call__(self, parser, namespace, values, option_string=None):
        if len(values) == 0:
            setattr(namespace, self.dest, True)
        else:
            setattr(namespace, self.dest, values)


parser = argparse.ArgumentParser(
    description="---- Display the plasma equilibrium from the equilibrium IDS. It also shows pf coils and wall position overlay if exists [Previously known as equiplot]",
    parents=[dbentry_parser],
    formatter_class=rich_help_formatter,
)

parser.add_argument("-t", "--time", help="Time (default=middle)", type=float, default=-99.0)
parser.add_argument(
    "--rho",
    help="Show rho overlay on the plot",
    action="store_true",
)
parser.add_argument(
    "-md",
    "--md",
    nargs="*",
    action=md_action,
    default=[],
    help="""Provide machine descriptions that you need to plot\n
with ids names for example wall pf_active \n
or with uris for example\n
"imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3#wall"\n
"imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3"\n
""",
)
parser.add_argument(
    "--show-labels",
    help="Show labels",
    action="store_true",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()

splitted_ids_info = args.uri.split("#")
uri = splitted_ids_info[0]
occurrence = 0
if len(splitted_ids_info) == 2:
    ids_fragment = splitted_ids_info[1]

    splitted_ids_fragment = ids_fragment.split(":")
    if len(splitted_ids_fragment) == 2:
        ids_path_fragment = splitted_ids_fragment[1]

        splitted_ids_path_fragment = ids_path_fragment.split("/", 1)
        occurrence = int(splitted_ids_path_fragment[0])

logger = setup_logger("module", stdout_level=logging.i_n_f_o)

connection = DBMaster.get_connection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

# if md not provided then get it from list of idses
if isinstance(args.md, bool) and args.md is True:
    args.md = []
    _ids_connection = DBMaster.get_connection(args)
    available_ids_and_times = get_available_ids_and_times(_ids_connection)
    for ids_name, _ in available_ids_and_times:
        args.md.append(ids_name)
    _ids_connection.close()

ids_obj_equilibrium = imas.equilibrium()
ids_obj_equilibrium.time = connection.partial_get("equilibrium", "time", occurrence)
if ids_obj_equilibrium.time is not None:
    time_index, time_value = get_nearest_time(ids_obj_equilibrium.time, args.time)
    ids_obj_equilibrium.time_slice.resize(1)
    ids_obj_equilibrium.time_slice[0] = connection.partial_get(
        "equilibrium", f"time_slice({str(time_index)})", occurrence
    )
    plotequilibrium = equilibrium_view(ids_obj_equilibrium)

    title = f"2D Equilibrium at time {time_value:.1f}"
    database_text = ""
    canvas = canvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="", row=0, col=0)

    for mdids_info in args.md:
        inputargs = copy.deepcopy(args)
        splittedms_ids_info = mdids_info.split("#")
        _ids_name = []
        _md_uri = None
        if len(splittedms_ids_info) == 2:
            _md_uri, ids_name = splittedms_ids_info
            _ids_name.append(ids_name)
            mdargs = argparse.namespace()
            mdargs.uri = _md_uri
            inputargs = mdargs
        if len(splittedms_ids_info) == 1:
            if "imas:" in splittedms_ids_info[0]:
                _md_uri = splittedms_ids_info[0]
                mdargs = argparse.namespace()
                mdargs.uri = _md_uri
                inputargs = mdargs
            else:
                _ids_name = splittedms_ids_info
        if len(_ids_name) == 0:
            ids_connection = DBMaster.get_connection(inputargs)
            available_ids_and_times = get_available_ids_and_times(ids_connection)
            for ids_name, _ in available_ids_and_times:
                _ids_name.append(ids_name)
            ids_connection.close()
        if "wall" in _ids_name:
            connection = DBMaster.get_connection(inputargs)
            if connection is not None:
                _ids_data = connection.get("wall")
                from imas import imasdef

                if _ids_data.ids_properties.homogeneous_time != imasdef.EMPTY_INT:
                    wallview = wall_view(_ids_data)
                    if found_data := wallview.view_wall(ax, args.show_labels, wallcolor="slategray"):
                        title += " wall"
                        database_text += f"{_ids_name}={get_database_path(inputargs)}\n"
                else:
                    logger.warning(f"{_ids_name} ids is empty in the dbentry")
                connection.close()
            else:
                logger.warning(f"{_ids_name} ids is not present")
        if "pf_active" in _ids_name:
            connection = DBMaster.get_connection(inputargs)
            if connection is not None:
                _ids_data = connection.get("pf_active")
                from imas import imasdef

                if _ids_data.ids_properties.homogeneous_time != imasdef.EMPTY_INT:
                    view_pf_coils = p_f_active_view(_ids_data)
                    view_pf_coils.view_active_pf_coils(ax, args.show_labels)
                    title += " Active PF Coils"
                    database_text += f"{_ids_name}={get_database_path(inputargs)}\n"
                else:
                    logger.warning(f"{_ids_name} ids is empty in the dbentry")
                connection.close()
            else:
                logger.warning("f{_idsName} ids is not present")

    plotequilibrium.view_magnetic_poloidal_flux(ax, plot_rho=args.rho)
    ax.set_title(title)

    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    ax.text(
        xmax + 0.01 * abs(xmax),
        ymin + 0.5 * abs(ymax - ymin),
        f"{get_database_path(args, time_value=time_value)}\n{database_text}",
        horizontalalignment="left",
        verticalalignment="center",
        rotation="vertical",
        fontsize=7,
    )

    canvas.fig.suptitle(get_title(args, "Equilibrium", time_value), size=12)
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    if args.save:
        fname = get_file_name(args, f"{os.path.basename(__file__)}_Equilibrium", time_value)
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()
else:
    logger.warning("Can not produce plot, equilibrium/time is None")
