#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import os
import re

from imaspy import convert_ids
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.machinedescription import MachineDescription
from idstools.utils.clihelper import (
    get_database_path,
)
from idstools.utils.idshelper import (
    get_available_ids_and_occurrences,
    parse_uri,
)
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.magnetics import MagneticsView
from idstools.view.pf_active import PFActiveView
from idstools.view.pf_passive import PFPassiveView
from idstools.view.tf import TFView
from idstools.view.wall import WallView

# ----------------------------------------------------------------------


logger = setup_logger("module", stdout_level=logging.INFO)
idses = "tf,wall,pf_passive,pf_active,magnetics"


def plot_machine_description(ids_data, show_labels=False):
    """
    The `plotMachineDescription` method is responsible for plotting the machine description
    based on the provided pulse list.

    """

    # Initialization
    canvas = PlotCanvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="R (m)", ylabel="Z (m)", row=0, col=0)

    database_path = ""

    mdlegends = []
    mdlabels = []
    for idsinfo, ids_data_and_config in ids_data.items():
        # if idsDataAndConfig["yamlConfig"] is None:
        #     logger.error(f"Could not retrieve machine description for {idsName}")
        #     databasePath += f"{idsName} = not found"
        #     continue
        logger.info(f"Processing for plotting {idsinfo}")
        ids_name = ids_data_and_config["idsname"]
        idsfield = ids_data_and_config["idsfield"] or ""
        idsocc = ids_data_and_config["idsocc"]
        print(ids_data_and_config)
        matches = re.findall(r"[\[(]([^\])]+)[\])]", idsfield)
        select = ":"
        if len(matches) > 1:
            select = matches[0]
        if ids_name == "pf_active":
            pfcoilsview = PFActiveView(ids_data_and_config["idsData"])
            if "coil" in idsfield or idsfield == "":
                _legend = pfcoilsview.view_active_pf_coils(ax, select=select, show_labels=show_labels)
                if _legend:
                    mdlegends.append(_legend)
                    mdlabels.append(f"pf_active:{idsocc}/coil[{select}]")
                    database_path += "pf_active = " + get_database_path(ids_data_and_config["connectionArgs"]) + "\n"
        elif ids_name == "tf":
            select2 = ":"
            if len(matches) == 2:
                select2 = matches[1]
            tfview = TFView(ids_data_and_config["idsData"])
            if "coil" in idsfield or idsfield == "":
                _legend = tfview.view_tf_coils(
                    ax, select_coil=select, select_conductor=select2, show_labels=show_labels
                )
                if _legend:
                    mdlegends.append(_legend)
                    mdlabels.append(f"tf:{idsocc}/coil[{select}]/conductor[{select2}]")
                    database_path += "tf = " + get_database_path(ids_data_and_config["connectionArgs"]) + "\n"
        elif ids_name == "pf_passive":
            pfpassiveview = PFPassiveView(ids_data_and_config["idsData"])
            if "loop" in idsfield or idsfield == "":
                _legend = pfpassiveview.view_pf_passive_loops(ax, select=select, show_labels=show_labels)
                if _legend:
                    mdlegends.append(_legend)

                    mdlabels.append(f"pf_passive:{idsocc}/loop[{select}]")
                    database_path += "pf_passive = " + get_database_path(ids_data_and_config["connectionArgs"]) + "\n"
        elif ids_name == "wall":
            wallview = WallView(ids_data_and_config["idsData"])
            select2 = ":"
            if len(matches) == 2:
                select2 = matches[1]
            if "vessel" in idsfield:
                wallview.view_wall_vessel(ax, select_description2d=select, select_unit=select2, show_labels=show_labels)
            if "limiter" in idsfield or idsfield == "":
                wallview.view_wall_limiter(
                    ax, select_description2d=select, select_unit=select2, show_labels=show_labels
                )
            database_path += "wall = " + get_database_path(ids_data_and_config["connectionArgs"]) + "\n"
        elif ids_name == "magnetics":
            magnetics_view = MagneticsView(ids_data_and_config["idsData"])
            if "b_field_phi_probe" in idsfield or idsfield == "":
                _legend = magnetics_view.view_b_field_probes(
                    ax, probe_type="b_field_phi_probe", select=select, show_labels=show_labels
                )
                if _legend:
                    mdlegends.append(_legend)
                    mdlabels.append(f"magnetics:{idsocc}/b_field_phi_probe[{select}]")
            if "b_field_pol_probe" in idsfield or idsfield == "":
                _legend = magnetics_view.view_b_field_probes(
                    ax, probe_type="b_field_pol_probe", select=select, show_labels=show_labels
                )
                if _legend:
                    mdlegends.append(_legend)
                    mdlabels.append(f"magnetics:{idsocc}/b_field_pol_probe[{select}]")
            if "flux_loop" in idsfield or idsfield == "":
                _legend = magnetics_view.view_flux_loop(ax, select=select, show_labels=show_labels)
                if _legend:
                    mdlegends.append(_legend)
                    mdlabels.append(f"magnetics:{idsocc}/flux_loop[{select}]")
            if "rogowski_coil" in idsfield or idsfield == "":
                _legend = magnetics_view.view_rogowski_coil(ax, select=select, show_labels=show_labels)
                if _legend:
                    mdlegends.append(_legend)
                    mdlabels.append(f"magnetics:{idsocc}/rogowski_coil[{select}]")
            if "shunt" in idsfield or idsfield == "":
                _legend = magnetics_view.view_shunt(ax, select=select, show_labels=show_labels)
                if _legend:
                    mdlegends.append(_legend)
                    mdlabels.append(f"magnetics:{idsocc}/shunt[{select}]")
            database_path += "magnetics = " + get_database_path(ids_data_and_config["connectionArgs"]) + "\n"
        else:
            database_path += (
                f"{ids_name} = " + get_database_path(ids_data_and_config["connectionArgs"]) + "No visualization yet\n"
            )
            logger.info(f"Visualization is not implemented yet for machine description {ids_name}")

    handles, labels = ax.get_legend_handles_labels()
    handles.extend(mdlegends)
    labels.extend(mdlabels)
    if labels:
        ax.legend(handles=handles, labels=labels, loc="upper left", bbox_to_anchor=(1.15, 1))
    ax.set_aspect("equal", adjustable="box")
    ax.plot()
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    ax.text(
        xmax + 0.01 * abs(xmax),
        ymin + 0.5 * abs(ymax - ymin),
        f"{database_path}",
        horizontalalignment="left",
        verticalalignment="center",
        rotation="vertical",
        fontsize=7,
    )
    canvas.fig.subplots_adjust(top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2)
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    canvas.fig.suptitle("Machine Description", size=12)
    if args.save:
        fname = os.path.basename(__file__) + "_machine_description.png"
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="---- View and plot machine description with one or more URIs as data entries",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "-u",
        "--uri",
        nargs="*",
        default=[],
        help="""Provide machine descriptions that you need to plot\n
    with uris for example\n
    "imas:mdsplus?user=public;pulse=116000;run=4;database=ITER_MD;version=3#wall"\n
    "imas:mdsplus?user=public;pulse=116000;run=4;database=ITER_MD;version=3"\n
    """,
    )
    parser.add_argument(
        "--dd-update",
        action="store_true",
        help=(
            "Convert IDS to the default version of the data dictionary if enabled"
            "otherwise, use the original IDS stored on disk."
        ),
    )
    parser.add_argument(
        "--show-labels",
        help="Show labels",
        action="store_true",
    )
    parser.add_argument(
        "--save",
        help="Save figure at default location",
        action="store_true",
    )
    parser.add_argument(
        "--directory",
        help="Directory to save the figure",
        default=None,
    )
    args = parser.parse_args()
    machine_description = MachineDescription()
    ids_data = {}

    for mduri in args.uri:
        mdargs = argparse.Namespace()

        result = parse_uri(mduri)
        # specified things in uri
        _md_uri = result["uri_part"]
        _ids_occurrence = result["occurrence"]
        _ids_name = result["ids_name"]
        _ids_field = result["ids_path"]
        _ids_names = _ids_name
        mdargs.uri = _md_uri
        connection = DBMaster.get_connection(mdargs)
        if connection:
            all_idses_list = get_available_ids_and_occurrences(connection, None)
            if _ids_names == "":
                _ids_names = idses

            for _ids_name in _ids_names.split(","):
                if _ids_name not in idses:
                    continue
                ids_found = False
                if _ids_occurrence is None:
                    _ids_occurrences = [value for term, value in all_idses_list if _ids_name in term]
                else:
                    _ids_occurrences = [_ids_occurrence]
                for occ in _ids_occurrences:
                    if args.dd_update:
                        _ids_data = convert_ids(
                            connection.get(_ids_name, autoconvert=False, occurrence=occ), connection.factory.version
                        )
                    else:
                        _ids_data = connection.get(_ids_name, autoconvert=False, occurrence=occ)
                    data = {}
                    if _ids_data is not None:
                        ids_found = True
                        (
                            data["idsData"],
                            data["yamlConfig"],
                            data["connectionArgs"],
                            data["idsname"],
                            data["idsfield"],
                            data["idsocc"],
                        ) = (_ids_data, None, mdargs, _ids_name, _ids_field, occ)
                        ids_data[f"{_md_uri}#{_ids_name}:{occ}/{_ids_field}"] = data
                if not ids_found:
                    logger.info(f"Could not find {_ids_name} in the given data entry")
            connection.close()

    plot_machine_description(ids_data, args.show_labels)
