#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import os

from imaspy import convert_ids
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.machinedescription import MachineDescription
from idstools.utils.idshelper import (
    get_available_ids_and_occurrences,
    parse_uri,
)
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.domain.mdplot import plot_machine_description

# ----------------------------------------------------------------------


logger = setup_logger("module", stdout_level=logging.INFO)
idses = "tf,wall,pf_passive,pf_active,magnetics"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="---- View and plot machine description with one or more URIs as data entries",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "-u",
        "--uri",
        nargs="*",
        default=[],
        help="""Provide machine descriptions that you need to plot\n
    with uris for example\n
    "imas:mdsplus?user=public;pulse=116000;run=4;database=ITER_MD;version=3#wall"\n
    "imas:mdsplus?user=public;pulse=116000;run=4;database=ITER_MD#wall:0/description2d[0]/vessel/unit[:]"
    "imas:mdsplus?user=public;pulse=116000;run=4;database=ITER_MD;version=3"\n
    """,
    )
    parser.add_argument(
        "--dd-update",
        action="store_true",
        help=(
            "Convert IDS to the default version of the data dictionary if enabled"
            "otherwise, use the original IDS stored on disk."
        ),
    )
    parser.add_argument(
        "--save",
        help="Save figure at default location",
        action="store_true",
    )
    parser.add_argument(
        "--directory",
        help="Directory to save the figure",
        default=None,
    )
    args = parser.parse_args()
    machine_description = MachineDescription()
    ids_data = {}

    for mduri in args.uri:
        mdargs = argparse.Namespace()

        result = parse_uri(mduri)

        # specified things in uri
        _md_uri = result["uri_part"]
        _ids_occurrence = result["occurrence"]
        _ids_name = result["ids_name"]
        _ids_field = result["ids_path"]
        _ids_names = _ids_name
        mdargs.uri = _md_uri
        connection = DBMaster.get_connection(mdargs)
        if connection:
            all_idses_list = get_available_ids_and_occurrences(connection, None)
            if _ids_names == "":
                _ids_names = idses

            for _ids_name in _ids_names.split(","):
                if _ids_name not in idses:
                    continue
                ids_found = False
                if _ids_occurrence is None:
                    _ids_occurrences = [value for term, value in all_idses_list if _ids_name in term]
                else:
                    _ids_occurrences = [_ids_occurrence]
                for occ in _ids_occurrences:
                    if args.dd_update:
                        _ids_data = convert_ids(
                            connection.get(_ids_name, autoconvert=False, occurrence=occ), connection.factory.version
                        )
                    else:
                        _ids_data = connection.get(_ids_name, autoconvert=False, occurrence=occ)
                    data = {}
                    if _ids_data is not None:
                        ids_found = True
                        (
                            data["idsData"],
                            data["yamlConfig"],
                            data["connectionArgs"],
                            data["idsname"],
                            data["idsfield"],
                            data["idsocc"],
                        ) = (_ids_data, None, mdargs, _ids_name, _ids_field, occ)
                        ids_data[f"{_md_uri}#{_ids_name}:{occ}/{_ids_field}"] = data
                if not ids_found:
                    logger.info(f"Could not find {_ids_name} in the given data entry")
            connection.close()

    # Initialization
    mdcanvas = PlotCanvas(1, 1)
    ax = mdcanvas.add_axes(title="", xlabel="R (m)", ylabel="Z (m)", row=0, col=0)
    plot_machine_description(ax, ids_data)
    mdcanvas.fig.subplots_adjust(top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2)
    mdcanvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    mdcanvas.fig.suptitle("Machine Description", size=12)
    if args.save:
        fname = os.path.basename(__file__) + "_machine_description.png"
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        mdcanvas.save(fname)
    else:
        mdcanvas.show()
