#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# python scripts/plotequilibrium -p 134174 -r 117
# -md "imas:mdsplus?user=public;shot=116000;run=2;database=ITER_MD;version=3#wall"
# "imas:mdsplus?user=public;shot=111001;run=102;database=ITER_MD;version=3#pf_active"

import argparse
import copy
import logging
import os

import imas
from rich_argparse import RichHelpFormatter

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idshelper import getAvailableIdsAndTimes
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.equilibrium import EquilibriumView
from idstools.view.pf_active import PFActiveView
from idstools.view.wall import WallView


class MdAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        if len(values) == 0:
            setattr(namespace, self.dest, True)
        else:
            setattr(namespace, self.dest, values)


parser = argparse.ArgumentParser(
    description="---- Display the plasma equilibrium from the equilibrium IDS. It also shows pf coils and wall position overlay if exists [Previously known as equiplot]",
    parents=[dbentryParser],
    formatter_class=RichHelpFormatter,
)

parser.add_argument(
    "-t", "--time", help="Time (default=middle)", type=float, default=-99.0
)
parser.add_argument(
    "--rho",
    help="Show rho overlay on the plot",
    action="store_true",
)
parser.add_argument(
    "-md",
    "--md",
    nargs="*",
    action=MdAction,
    default=[],
    help="""Provide machine descriptions that you need to plot\n
with ids names for example wall pf_active \n
or with uris for example\n
"imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3#wall"\n
"imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3"\n
""",
)
parser.add_argument(
    "--show-labels",
    help="Show labels",
    action="store_true",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()

splittedIdsInfo = args.uri.split("#")
uri = splittedIdsInfo[0]
occurrence = 0
if len(splittedIdsInfo) == 2:
    idsFragment = splittedIdsInfo[1]

    splittedIdsFragment = idsFragment.split(":")
    if len(splittedIdsFragment) == 2:
        idsPathFragment = splittedIdsFragment[1]

        splittedIdsPathFragment = idsPathFragment.split("/", 1)
        occurrence = int(splittedIdsPathFragment[0])

logger = setupLogger("module", stdout_level=logging.INFO)

connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

# if md not provided then get it from list of idses
if isinstance(args.md, bool) and args.md is True:
    args.md = []
    _idsConnection = DBMaster.getConnection(args)
    availableIdsAndTimes = getAvailableIdsAndTimes(_idsConnection)
    for idsName, _ in availableIdsAndTimes:
        args.md.append(idsName)
    _idsConnection.close()

idsObjEquilibrium = imas.equilibrium()
idsObjEquilibrium.time = connection.partial_get("equilibrium", "time", occurrence)
if idsObjEquilibrium.time is not None:
    timeIndex, timeValue = getNearestTime(idsObjEquilibrium.time, args.time)
    idsObjEquilibrium.time_slice.resize(1)
    idsObjEquilibrium.time_slice[0] = connection.partial_get(
        "equilibrium", f"time_slice({str(timeIndex)})", occurrence
    )
    plotequilibrium = EquilibriumView(idsObjEquilibrium)

    title = f"2D Equilibrium at time {timeValue:.1f}"
    databaseText = ""
    canvas = Canvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="", row=0, col=0)

    for mdidsInfo in args.md:
        inputargs = copy.deepcopy(args)
        splittedmsIdsInfo = mdidsInfo.split("#")
        _idsName = []
        _mdUri = None
        if len(splittedmsIdsInfo) == 2:
            _mdUri, idsName = splittedmsIdsInfo
            _idsName.append(idsName)
            mdargs = argparse.Namespace()
            mdargs.uri = _mdUri
            inputargs = mdargs
        if len(splittedmsIdsInfo) == 1:
            if "imas:" in splittedmsIdsInfo[0]:
                _mdUri = splittedmsIdsInfo[0]
                mdargs = argparse.Namespace()
                mdargs.uri = _mdUri
                inputargs = mdargs
            else:
                _idsName = splittedmsIdsInfo
        if len(_idsName) == 0:
            idsConnection = DBMaster.getConnection(inputargs)
            availableIdsAndTimes = getAvailableIdsAndTimes(idsConnection)
            for idsName, _ in availableIdsAndTimes:
                _idsName.append(idsName)
            idsConnection.close()
        if "wall" in _idsName:
            connection = DBMaster.getConnection(inputargs)
            if connection is not None:
                _idsData = connection.get("wall")
                from imas import imasdef

                if _idsData.ids_properties.homogeneous_time != imasdef.EMPTY_INT:
                    wallview = WallView(_idsData)
                    if foundData := wallview.view_wall(
                        ax, args.show_labels, wallcolor="slategray"
                    ):
                        title += " wall"
                        databaseText += f"{_idsName}={getDatabasePath(inputargs)}\n"
                else:
                    logger.warning(f"{_idsName} ids is empty in the dbentry")
                connection.close()
            else:
                logger.warning(f"{_idsName} ids is not present")
        if "pf_active" in _idsName:
            connection = DBMaster.getConnection(inputargs)
            if connection is not None:
                _idsData = connection.get("pf_active")
                from imas import imasdef

                if _idsData.ids_properties.homogeneous_time != imasdef.EMPTY_INT:
                    ViewPfCoils = PFActiveView(_idsData)
                    ViewPfCoils.viewActivePfCoils(ax, args.show_labels)
                    title += " Active PF Coils"
                    databaseText += f"{_idsName}={getDatabasePath(inputargs)}\n"
                else:
                    logger.warning(f"{_idsName} ids is empty in the dbentry")
                connection.close()
            else:
                logger.warning("f{_idsName} ids is not present")

    plotequilibrium.viewMagneticPoloidalFlux(ax, plotRho=args.rho)
    ax.set_title(title)

    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    ax.text(
        xmax + 0.01 * abs(xmax),
        ymin + 0.5 * abs(ymax - ymin),
        f"{getDatabasePath(args, timeValue=timeValue)}\n{databaseText}",
        horizontalalignment="left",
        verticalalignment="center",
        rotation="vertical",
        fontsize=7,
    )

    canvas.fig.suptitle(getTitle(args, "Equilibrium", timeValue), size=12)
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    if args.save:
        fname = getFileName(
            args, f"{os.path.basename(__file__)}_Equilibrium", timeValue
        )
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()
else:
    logger.warning("Can not produce plot, equilibrium/time is None")
