#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import os

from imaspy import convert_ids
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.machinedescription import MachineDescription
from idstools.utils.idshelper import (
    get_available_ids_and_occurrences,
)
from idstools.utils.clihelper import (
    get_database_path,
)
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.pf_active import PFActiveView
from idstools.view.wall import WallView

# ----------------------------------------------------------------------


logger = setup_logger("module", stdout_level=logging.INFO)
idses = "wall,pf_active"


def plot_machine_description(ids_data, show_labels=False):
    """
    The `plotMachineDescription` method is responsible for plotting the machine description
    based on the provided pulse list.
    """

    # Initialization
    canvas = PlotCanvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="R (m)", ylabel="Z (m)", row=0, col=0)

    ax.set_aspect("equal", adjustable="box")

    database_path = ""
    # Plot Overlay
    for ids_name, ids_data_and_config in ids_data.items():
        # if idsDataAndConfig["yamlConfig"] is None:
        #     logger.error(f"Could not retrieve machine description for {idsName}")
        #     databasePath += f"{idsName} = not found"
        #     continue
        ids_uri, ids_name = ids_name.split("#")
        if ids_name == "pf_active":
            pfcoilsview = PFActiveView(ids_data_and_config["idsData"])
            pfcoilsview.view_active_pf_coils(ax, show_labels=show_labels)
            database_path += "pf_active = " + get_database_path(ids_data_and_config["connectionArgs"]) + "\n"

        elif ids_name == "wall":
            wallview = WallView(ids_data_and_config["idsData"])
            wallview.view_wall(ax, show_labels=show_labels)
            database_path += "wall = " + get_database_path(ids_data_and_config["connectionArgs"]) + "\n"
        else:
            database_path += (
                f"{ids_name} = " + get_database_path(ids_data_and_config["connectionArgs"]) + "No visualization yet\n"
            )
            logger.info(f"Visualization is not implemented yet for machine description {ids_name}")

    # wallview.view_DIR(ax)
    # wallview.view_TS(ax)
    # wallview.view_Cryostat(ax)
    ax.plot()

    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    ax.text(
        xmax + 0.01 * abs(xmax),
        ymin + 0.5 * abs(ymax - ymin),
        f"{database_path}",
        horizontalalignment="left",
        verticalalignment="center",
        rotation="vertical",
        fontsize=7,
    )
    canvas.fig.subplots_adjust(top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2)
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    canvas.fig.suptitle("Machine Description", size=12)
    if args.save:
        fname = os.path.basename(__file__) + "_machine_description.png"
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="---- View and plot machine description with one or more URIs as data entries",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "-u",
        "--uri",
        nargs="*",
        default=[],
        help="""Provide machine descriptions that you need to plot\n
    with uris for example\n
    "imas:mdsplus?user=public;pulse=116000;run=4;database=ITER_MD;version=3#wall"\n
    "imas:mdsplus?user=public;pulse=116000;run=4;database=ITER_MD;version=3"\n
    """,
    )
    parser.add_argument(
        "--dd-update",
        action="store_true",
        help=(
            "Convert IDS to the default version of the data dictionary if enabled"
            "otherwise, use the original IDS stored on disk."
        ),
    )
    parser.add_argument(
        "--show-labels",
        help="Show labels",
        action="store_true",
    )
    parser.add_argument(
        "--save",
        help="Save figure at default location",
        action="store_true",
    )
    parser.add_argument(
        "--directory",
        help="Directory to save the figure",
        default=None,
    )
    args = parser.parse_args()
    machine_description = MachineDescription()
    ids_data = {}

    for mdids_info in args.uri:
        mdargs = argparse.Namespace()
        splittedms_ids_info = mdids_info.split("#")
        _ids_names = ""
        _md_uri = None
        if len(splittedms_ids_info) == 2:
            _md_uri, _ids_names = splittedms_ids_info
        if len(splittedms_ids_info) == 1:
            _md_uri = splittedms_ids_info[0]
        mdargs.uri = _md_uri
        connection = DBMaster.get_connection(mdargs)
        if connection:
            all_idses_list = [item for item, _ in get_available_ids_and_occurrences(connection, None)]
            if _ids_names == "":
                _ids_names = idses
            for _ids_name in _ids_names.split(","):
                if _ids_name not in idses:
                    continue
                ids_found = False
                if connection is not None:
                    if _ids_name in all_idses_list:
                        if args.dd_update:
                            _ids_data = convert_ids(
                                connection.get(_ids_name, autoconvert=False), connection.factory.version
                            )
                        else:
                            _ids_data = connection.get(_ids_name, autoconvert=False)

                        data = {}
                        if _ids_data is not None:
                            ids_found = True
                            (
                                data["idsData"],
                                data["yamlConfig"],
                                data["connectionArgs"],
                            ) = (
                                _ids_data,
                                None,
                                mdargs,
                            )
                            ids_data[f"{_md_uri}#{_ids_name}"] = data
                if not ids_found:
                    logger.info(f"Could not find {_ids_name} in the given data entry")
            connection.close()

    plot_machine_description(ids_data, args.show_labels)
