#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# python scripts/plotequilibrium -p 134174 -r 117
# -md "imas:mdsplus?user=public;shot=116000;run=2;database=ITER_MD;version=3#wall"
# "imas:mdsplus?user=public;shot=111001;run=102;database=ITER_MD;version=3#pf_active"

import argparse
import copy
import logging
import os

from imaspy import ids_defs
from rich_argparse import RichHelpFormatter

from idstools.compute.common import get_nearest_time
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentry_parser,
    get_database_path,
    get_file_name,
    get_title,
)
from idstools.utils.idshelper import get_available_ids_and_times
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.equilibrium import EquilibriumView
from idstools.view.pf_active import PFActiveView
from idstools.view.wall import WallView


class MdAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        if len(values) == 0:
            setattr(namespace, self.dest, True)
        else:
            setattr(namespace, self.dest, values)


parser = argparse.ArgumentParser(
    description="""---- Display the plasma equilibrium from the equilibrium IDS.
    It also shows pf coils and wall position overlay if exists [Previously known as equiplot]""",
    parents=[dbentry_parser],
    formatter_class=RichHelpFormatter,
)
parser.add_argument("-t", "--time", help="Time (default=middle)", type=float, default=-99.0)
parser.add_argument(
    "--rho",
    help="Show rho overlay on the plot",
    action="store_true",
)
parser.add_argument(
    "-p",
    "--plots",
    help="Plots available quantities along with equilibrium",
    action="store_true",
)
parser.add_argument(
    "-md",
    "--md",
    nargs="*",
    action=MdAction,
    default=[],
    help="""Provide machine descriptions that you need to plot\n
with ids names for example wall pf_active \n
or with uris for example\n
"imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3#wall"\n
"imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3"\n
""",
)
parser.add_argument(
    "--show-labels",
    help="Show labels",
    action="store_true",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()

splitted_ids_info = args.uri.split("#")
uri = splitted_ids_info[0]
occurrence = 0
if len(splitted_ids_info) == 2:
    ids_fragment = splitted_ids_info[1]

    splitted_ids_fragment = ids_fragment.split(":")
    if len(splitted_ids_fragment) == 2:
        ids_path_fragment = splitted_ids_fragment[1]

        splitted_ids_path_fragment = ids_path_fragment.split("/", 1)
        occurrence = int(splitted_ids_path_fragment[0])

logger = setup_logger("module", stdout_level=logging.INFO)

connection = DBMaster.get_connection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

# if md not provided then get it from list of idses
if isinstance(args.md, bool) and args.md is True:
    args.md = []
    _ids_connection = DBMaster.get_connection(args)
    available_ids_and_times = get_available_ids_and_times(_ids_connection)
    for ids_name, _ in available_ids_and_times:
        args.md.append(ids_name)
    _ids_connection.close()


ids_obj_equilibrium = connection.get("equilibrium", occurrence=occurrence, lazy=True)

if ids_obj_equilibrium.time is not None:
    time_slice, time_value = get_nearest_time(ids_obj_equilibrium.time, args.time)
    view_object = EquilibriumView(ids_obj_equilibrium)

    title = f"2D Equilibrium at time {time_value:.1f}"
    database_text = ""
    if args.plots:
        canvas = PlotCanvas(2, 6)
        axes_list1 = []
        ax2 = canvas.add_axes(title="", xlabel="", row=0, col=1)
        ax3 = canvas.add_axes(title="", xlabel="", row=0, col=2)
        ax4 = canvas.add_axes(title="", xlabel="", row=1, col=1)
        # ax5=canvas.add_axes(title="", xlabel="", row=1, col=2)
        axes_list1 = [ax2, ax3, ax4]

        axes_list2 = []
        ax6 = canvas.add_axes(title="", xlabel="", row=0, col=3)
        ax7 = canvas.add_axes(title="", xlabel="", row=0, col=4)
        ax8 = canvas.add_axes(title="", xlabel="", row=0, col=5)
        ax9 = canvas.add_axes(title="", xlabel="", row=1, col=3)
        ax10 = canvas.add_axes(title="", xlabel="", row=1, col=4)
        # ax11=canvas.add_axes(title="", xlabel="", row=1, col=5)
        axes_list2 = [ax6, ax7, ax8, ax9, ax10]

    else:
        canvas = PlotCanvas(1, 1)
        ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)

    for mdids_info in args.md:
        inputargs = copy.deepcopy(args)
        splittedms_ids_info = mdids_info.split("#")
        _ids_name = []
        _md_uri = None
        if len(splittedms_ids_info) == 2:
            _md_uri, ids_name = splittedms_ids_info
            _ids_name.append(ids_name)
            mdargs = argparse.Namespace()
            mdargs.uri = _md_uri
            inputargs = mdargs
        if len(splittedms_ids_info) == 1:
            if "imas:" in splittedms_ids_info[0]:
                _md_uri = splittedms_ids_info[0]
                mdargs = argparse.Namespace()
                mdargs.uri = _md_uri
                inputargs = mdargs
            else:
                _ids_name = splittedms_ids_info
        if len(_ids_name) == 0:
            ids_connection = DBMaster.get_connection(inputargs)
            available_ids_and_times = get_available_ids_and_times(ids_connection)
            for ids_name, _ in available_ids_and_times:
                _ids_name.append(ids_name)
            ids_connection.close()
        if "wall" in _ids_name:
            connection = DBMaster.get_connection(inputargs)
            if connection is not None:
                try:
                    _ids_data = connection.get("wall")
                    if _ids_data.ids_properties.homogeneous_time == ids_defs.EMPTY_INT:
                        logger.warning(f"{_ids_name} ids is empty in the dbentry")
                except Exception as e:
                    logger.warning(f"{_ids_name} ids is not present error {e}")
                if _ids_data:

                    wallview = WallView(_ids_data)
                    if found_data := wallview.view_wall(ax1, args.show_labels, wallcolor="slategray"):
                        title += " wall"
                        database_text += f"{_ids_name}={get_database_path(inputargs)}\n"
                connection.close()
            else:
                logger.warning(f"given data entry is not present for {_ids_name}")
        if "pf_active" in _ids_name:
            connection = DBMaster.get_connection(inputargs)
            if connection is not None:
                _ids_data = None
                try:
                    _ids_data = connection.get("pf_active")
                    if _ids_data.ids_properties.homogeneous_time == ids_defs.EMPTY_INT:
                        logger.warning(f"{_ids_name} ids is empty in the dbentry")
                except Exception as e:
                    logger.warning(f"{_ids_name} ids is not present error {e}")
                if _ids_data:
                    view_pf_coils = PFActiveView(_ids_data)
                    view_pf_coils.view_active_pf_coils(ax1, args.show_labels)
                    title += " Active PF Coils"
                    database_text += f"{_ids_name}={get_database_path(inputargs)}\n"
                connection.close()
            else:
                logger.warning(f"given data entry is not present for {_ids_name}")

    view_object.view_magnetic_poloidal_flux(ax1, time_slice, plot_rho=args.rho)
    ax1.set_title(title)

    xmin, xmax = ax1.get_xlim()
    ymin, ymax = ax1.get_ylim()
    ax1.text(
        xmax + 0.01 * abs(xmax),
        ymin + 0.5 * abs(ymax - ymin),
        f"{get_database_path(args, time_value=time_value)}\n{database_text}",
        horizontalalignment="left",
        verticalalignment="center",
        rotation="vertical",
        fontsize=7,
    )
    if args.plots:
        view_object.plot_profiles_1d_quantities(axes_list1, time_slice)
        view_object.plot_global_quantities(axes_list2, time_slice)

    canvas.fig.suptitle(get_title(args, "Equilibrium", time_value), size=12)
    canvas.fig.subplots_adjust(top=0.933, bottom=0.05, left=0.03, right=0.988, hspace=0.221, wspace=0.364)
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    if args.save:
        fname = get_file_name(args, f"{os.path.basename(__file__)}_Equilibrium", time_value)
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()
else:
    logger.warning("Can not produce plot, equilibrium/time is None")
