#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import json
import logging
import sys
import os
from rich_argparse import RichHelpFormatter
import imas

from idstools.compute.common import get_nearest_time
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentry_parser,
    get_database_path,
    get_file_name,
    get_title,
)
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.core_profiles import CoreProfilesView
from idstools.view.equilibrium import EquilibriumView
from idstools.view.summary import SummaryView

# ----------------------------------------------------------------------

# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Display the plasma kinetic profiles and equilibrium from the core_profiles and equilibrium IDSs [previously known as scenplot]",
    parents=[dbentry_parser],
    formatter_class=RichHelpFormatter,
)

group = parser.add_mutually_exclusive_group()
group.add_argument("-t", "--time", help="Time for profiles", required=False, type=float, default=-99.0)
group.add_argument(
    "-n",
    "--noProfiles",
    action="store_true",
    help="Do not plot profiles or equilibrium",
)
parser.add_argument(
    "-i",
    "--info",
    action="store_true",
    help="Add title with additional provenance information",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()
logger = setup_logger("module", stdout_level=logging.i_n_f_o)

# Open the database and read the necessary IDSs
connection = DBMaster.get_connection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

if not args.no_profiles:
    try:
        ids_core_profiles = imas.core_profiles()  # To initialise the empty IDS structure
        ids_core_profiles.time = connection.partial_get("core_profiles", "time")
        ids_core_profiles.global_quantities = connection.partial_get("core_profiles", "global_quantities")
        if ids_core_profiles.time is None:
            logger.critical("No core_profiles IDS in the data-entry --> Abort.")
            exit()
    except Exception as e:
        logger.critical("The core_profiles IDS is absent from the input data-entry")
        logger.critical("----> Aborted.")
        exit()

    try:
        ids_equilibrium = imas.equilibrium()  # To initialise the empty IDS structure
    except Exception as e:
        logger.critical("The equilibrium IDS is absent from the input data-entry")
        logger.critical("----> Aborted.")
        exit()

    # Search for adequate time slice for display
    time_array = ids_core_profiles.time
    ntime = len(ids_core_profiles.time)
    time_index, time_value = get_nearest_time(time_array, args.time)

    # Read 1D-profiles for this time slice
    ids_core_profiles.profiles_1d.resize(1)
    ids_core_profiles.profiles_1d[0] = connection.partial_get("core_profiles", "profiles_1d(" + str(time_index) + ")")

    ids_equilibrium.time_slice.resize(1)
    ids_equilibrium.time_slice[0].profiles_2d.resize(1)
    ids_equilibrium.time_slice[0].profiles_2d = connection.partial_get(
        "equilibrium", "time_slice(" + str(time_index) + ")/profiles_2d"
    )

try:
    ids_summary = connection.get("summary")
except Exception as e:
    logger.critical("The summary IDS is absent from the input data-entry")
    logger.critical("----> Aborted.")
    exit(1)


summary_time = len(ids_summary.time)

if summary_time < 1:
    logger.critical("The summary IDS is absent from the input data-entry")
    logger.critical("----> Aborted.")
    exit(1)


if not args.no_profiles:
    canvas = PlotCanvas(4, 2)
else:
    canvas = PlotCanvas(4, 1)
ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax2 = canvas.add_axes(title="", xlabel="", row=1, col=0, sharex=ax1)
ax3 = canvas.add_axes(title="", xlabel="", row=2, col=0, sharex=ax1)
ax4 = canvas.add_axes(title="", xlabel="", row=3, col=0, sharex=ax1)
if not args.no_profiles:
    ax5 = canvas.add_axes(title="", xlabel="", row=0, col=1, rowspan=2)
    ax6 = canvas.add_axes(title="", xlabel="", row=2, col=1)
    ax7 = canvas.add_axes(title="", xlabel="", row=3, col=1)

# H&CD waveforms
obje_summary_view = SummaryView(ids_summary)
obje_summary_view.view_hcd_waveforms(ax1)

obje_summary_view.view_hmode(ax1)
ax1.tick_params(axis="x", which="both", bottom=False, top=False, right=False, labelbottom=False)

if not args.no_profiles:
    ax1.set_title("Profiles displayed for t = " + "%.1f" % time_value + " s")
    obje_summary_view.view_time_line(ax1, time_value)

obje_summary_view.view_ip_b0_waveforms(ax2)

obje_summary_view.view_hmode(ax2)
ax2.tick_params(axis="x", which="both", bottom=False, top=False, right=False, labelbottom=False)
if not args.no_profiles:
    obje_summary_view.view_time_line(ax2, time_value)


obje_summary_view.view_energy_content_waveforms(ax3)

obje_summary_view.view_hmode(ax3)
ax3.tick_params(axis="x", which="both", bottom=False, top=False, right=False, labelbottom=False)
if not args.no_profiles:
    obje_summary_view.view_time_line(ax3, time_value)

obje_summary_view.view_vloop_waveforms(ax4)

obje_summary_view.view_hmode(ax4)

if not args.no_profiles:
    obje_summary_view.view_time_line(ax4, time_value)


if not args.no_profiles:
    core_core_profiles_view = CoreProfilesView(ids_core_profiles)
    core_core_profiles_view.view_q_profile_and_magnetic_shear_profile(ax6)

    core_core_profiles_view.view_current_desnity_profiles(ax7)

    plotequilibrium = EquilibriumView(ids_equilibrium)
    plotequilibrium.plotequilibrium(ax5)

title = get_title(args, "Scenario")
if not args.no_profiles:
    title = get_title(args, "Scenario", time_value)
else:
    title = get_title(args, "Scenario")
if args.info:
    try:
        dataset_description = connection.get("dataset_description")
        if dataset_description.ids_properties.homogeneous_time == imas.imasdef.EMPTY_INT:
            got_dataset_description = False
        else:
            got_dataset_description = True
    except Exception as e:
        logger.warning("Warning: The dataset_description IDS is absent from the input data-entry")
        got_dataset_description = False
    # F4F specific?
    if got_dataset_description:
        title += f"\nprovider={ids_summary.ids_properties.provider}, shot_date_time={dataset_description.pulse_time_begin}\ndata_dictionary={ids_summary.ids_properties.version_put.data_dictionary}, access_layer-{ids_summary.ids_properties.version_put.access_layer}"
    else:
        additional_data = ""

        if ids_summary.tag.name != "":
            try:
                additional_data = json.loads(ids_summary.tag.name)
            except Exception as e:
                additional_data = ""
        if "date" in additional_data:
            txtdate = additional_data["date"]
            txttime = additional_data["time"]

            title += f"\nprovider={ids_summary.ids_properties.provider}, shot_date={txtdate}, shot_time={txttime}\ndata_dictionary={ids_summary.ids_properties.version_put.data_dictionary}, access_layer={ids_summary.ids_properties.version_put.access_layer}"

        else:
            title += f"\nprovider={ids_summary.ids_properties.provider}, creation_date={ids_summary.ids_properties.creation_date}\ndata_dictionary={ids_summary.ids_properties.version_put.data_dictionary}, access_layer={ids_summary.ids_properties.version_put.access_layer}"

if not args.no_profiles:
    canvas.set_text(text=f"{get_database_path(args, time_value=time_value)}")
else:
    canvas.set_text(text=f"{get_database_path(args)}")
canvas.set_sup_title(title)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
canvas.fig.subplots_adjust(top=0.914, bottom=0.099, left=0.042, right=0.9, hspace=0.113, wspace=0.26)


if args.save:
    if not args.no_profiles:
        fname = get_file_name(args, os.path.basename(__file__) + "_summary", time_value)
    else:
        fname = get_file_name(args, os.path.basename(__file__) + "_Scenario_shot")
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname = os.path.join(args.directory, fname)
    canvas.save(fname)
else:
    canvas.show()
