#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter


from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    getDatabasePath,
    getFileName,
    getTitle,
    dbentryParser,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.distributions import DistributionsView

logger = setup_logger("module", stdout_level=logging.i_n_f_o)


def show_plots(args):
    conn = DBMaster.get_connection(args)
    if conn is None:
        logger.critical("----> Aborted.")
        exit(1)

    ids_distributions = conn.get("distributions")
    conn.close()

    time_array = ids_distributions.time
    ntime = len(time_array)
    time_index, time_value = get_nearest_time(ids_distributions.time, args.time)
    time = time_value
    ndistributions = len(ids_distributions.distribution)

    canvas = canvas(3, 2)
    # canvas.setStyle(style="retro")

    if ntime == 1:
        logger.info("Only one time slice --> Power and CD waveforms not displayed")
    ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
    ax2 = canvas.add_axes(title="", xlabel="", row=1, col=0)
    ax3 = canvas.add_axes(title="", xlabel="", row=2, col=0)
    distributions_view = distributions_view(ids_distributions)
    distributions_view.plot_absorbed_power_density_individual(ax1, time_index)
    distributions_view.plot_absorbed_power_density(ax2, time_index)
    distributions_view.plot_c_d_profile(ax3, time_index)
    if ntime != 1:
        ax4 = canvas.add_axes(title="", xlabel="", row=0, col=1)
        ax5 = canvas.add_axes(title="", xlabel="", row=1, col=1)
        distributions_view.plot_n_b_i_fus_power_and_c_d_waveforms(ax4, time_index)
        distributions_view.plot_c_d_waveform(ax5, time_index)

    canvas.set_text(text=f"{get_database_path(args, time_value=time_value)}")

    canvas.fig.subplots_adjust(
        top=0.92,
        bottom=0.122,
        left=0.044,
        right=0.886,
        hspace=0.438,
        wspace=0.328,
    )
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    canvas.fig.suptitle(get_title(args, "Distributions profile", time_value), size=12)

    if args.save:
        fname = get_file_name(args, os.path.basename(__file__) + "_Distributions_profile", time_value)
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()


if __name__ == "__main__":
    parser = argparse.argument_parser(
        description="---- Display EC results",
        parents=[dbentry_parser],
        formatter_class=rich_help_formatter,
    )
    parser.add_argument("-t", "--time", help="Time", required=False, type=float, default=-99.0)

    parser.add_argument(
        "--save",
        help="Save figure at default location",
        action="store_true",
    )
    parser.add_argument(
        "--directory",
        help="Directory to save the figure",
        default=None,
    )
    args = parser.parse_args()

    show_plots(args)

    # pulse = args.pulse
    # run = args.run

    # To handle multiple datafiles (for scans)
    # if "-" in run:
    #     [runmin, runmax] = [int(x) for x in run.split("-")]  # int(run.split('-'))
    # else:
    #     runmin = int(run)
    #     runmax = int(run)

    # for irun in range(runmin, runmax + 1):
