#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# migrated from neutronplot
import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter

import imas

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.distribution_sources import DistributionSourcesView

# Management of input arguments
parser = argparse.argument_parser(
    description="---- Display the neutron profiles from the distribution_sources IDSs [previously known as neutronplot]",
    parents=[dbentry_parser],
    formatter_class=rich_help_formatter,
)

parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=-99.0
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()
logger = setup_logger("module", stdout_level=logging.i_n_f_o)


# Open the database and read the necessary IDSs
connection = d_b_master.get_connection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

hostdir = get_database_path(args)
if hostdir is None:
    logger.critical(
        "Environment variable IMAS_HOME is not defined. Quitting.",
    )
    exit(1)

try:
    # connection.distribution_sources.get()
    ids_distribution_sources = imas.distribution_sources()
    ids_distribution_sources.time = connection.partial_get("distribution_sources", "time")
    if ids_distribution_sources.time is None:
        logger.critical(
            "No distribution_sources IDS in the data-entry --> Abort.",
        )
        exit()

except Exception as e:
    logger.critical(
        "The distribution_sources IDS is absent from the input data-entry",
    )
    logger.critical(
        "----> Aborted.",
    )
    exit()

time_array = ids_distribution_sources.time
time_index, time_value = get_nearest_time(time_array, args.time)

ids_slice_distribution_sources = connection.get_slice("distribution_sources", time_value, 1)

nsources = len(ids_slice_distribution_sources.source)
if nsources > 1:
    logger.info(
        f"Distribution_sources contains {nsources} sources",
    )
else:
    logger.info(
        f"Distribution_sources contains {nsources} source",
    )


active = [1] * nsources  # A priori all sources are active
ids_distribution_sources.source.resize(nsources)
for isource in range(nsources):
    ids_distribution_sources.source[isource].profiles_1d.resize(1)
    ids_distribution_sources.source[isource].global_quantities.resize(1)
    ids_distribution_sources.source[isource].process.resize(1)
    try:
        ids_distribution_sources.source[isource].profiles_1d[0] = (
            ids_slice_distribution_sources.source[isource].profiles_1d[0]
        )
    except Exception as e:
        logger.warning(
            f"Source {str(isource)} has no profiles_1d -> considered as inactive",
        )
        active[isource] = 0
    try:
        ids_distribution_sources.source[isource].global_quantities[0] = (
            ids_slice_distribution_sources.source[isource].global_quantities[0]
        )
    except Exception as e:
        if active[isource] == 1:
            logger.warning(
                f"Source {str(isource)} has no global_quantities -> considered as inactive",
            )
            active[isource] = 0
    try:
        ids_distribution_sources.source[isource].process[0] = (
            ids_slice_distribution_sources.source[isource].process[0]
        )
    except Exception as e:
        if active[isource] == 1:
            logger.warning(
                f"Source {str(isource)} has no process -> considered as inactive",
            )
            active[isource] = 0

if sum(active) == 0:
    logger.critical("No active neutron sources --> Leave.")
    exit()

canvas = canvas(1, 1)
ax = canvas.add_axes(title="", xlabel="", row=0, col=0)
distribution_sources_view = distribution_sources_view(ids_distribution_sources)
distribution_sources_view.view_neutrons(ax)
distribution_sources_view.view_time(ax, time_value)

canvas.set_text(text=f"{get_database_path(args, time_value=time_value)}")

canvas.fig.subplots_adjust(
    top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2
)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
canvas.fig.suptitle(get_title(args, "Neutrons profiles", time_value), size=12)

if args.save:
    fname = get_file_name(args, os.path.basename(__file__) + "_Neutrons", time_value)
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname = os.path.join(args.directory, fname)
    canvas.save(fname)
else:
    canvas.show()
