#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# plotequi --uri "imas:hdf5?user=appell;shot=105027;run=200;database=ITER;version=3"
import argparse
import logging
import os

try:
    import imaspy as imas
except ImportError:
    import imas
import numpy as np

try:
    import imaspy as imas
except ImportError:
    import imas
from rich_argparse import RichHelpFormatter

from idstools.compute.common import get_nearest_time
from idstools.utils.clihelper import (
    rcparam_parser,
)
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.equilibrium import EquilibriumView
from idstools.view.wall import WallView

logger = setup_logger("module", stdout_level=logging.INFO)
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="""---- Display the plasma equilibrium from the equilibrium IDS.
        It also shows pf coils and wall position overlay if exists [Previously known as equiplot]""",
        formatter_class=RichHelpFormatter,
        parents=[rcparam_parser],
    )
    parser.add_argument(
        "-u",
        "--uri",
        nargs="*",
        type=str,
        required=True,
        help="uri separated by spaces if comparing\t\t(default=%(default)s)",
    )
    parser.add_argument(
        "--dd-update",
        action="store_true",
        help=(
            "Convert IDS to the default version of the data dictionary if enabled"
            "otherwise, use the original IDS stored on disk."
        ),
    )
    parser.add_argument("-t", "--time", help="Time (default=middle)", type=float, default=-99.0)

    parser.add_argument(
        "--save",
        help="Save figure at default location",
        action="store_true",
    )
    parser.add_argument(
        "--directory",
        help="Directory to save the figure",
        default=None,
    )
    args = parser.parse_args()
    equilibrium1 = None
    equilibrium2 = None
    wall1 = None
    wall2 = None

    if args.uri is not None:
        if len(args.uri) >= 1:
            connection1 = imas.DBEntry(args.uri[0], "r")
            if args.dd_update:
                equilibrium1 = connection1.get("equilibrium", autoconvert=False)
                equilibrium1 = imas.convert_ids(equilibrium1, connection1.factory.version)
            else:
                equilibrium1 = connection1.get("equilibrium", lazy=True, autoconvert=False)

            time_array1 = equilibrium1.time
            time_slice1, time_value1 = get_nearest_time(time_array1, args.time)
            try:
                if args.dd_update:
                    wall1 = connection1.get("wall", autoconvert=False)
                    wall1 = imas.convert_ids(wall1, connection1.factory.version)
                else:
                    wall1 = connection1.get("wall", lazy=True, autoconvert=False)
            except Exception as e:
                logger.warning(f"Could not load wall data for first connection: {e}")
                wall1 = None

            if connection1 is None:
                logger.critical("----> Could not open first data entry. Aborted.")
                exit(1)
        if len(args.uri) == 2:
            connection2 = imas.DBEntry(args.uri[1], "r")
            if args.dd_update:
                equilibrium2 = connection2.get("equilibrium", autoconvert=False)
                equilibrium2 = imas.convert_ids(equilibrium2, connection2.factory.version)
            else:
                equilibrium2 = connection2.get("equilibrium", autoconvert=False)
            time_array2 = equilibrium2.time
            time_slice2 = np.argmin(abs(time_array2 - time_array1[time_slice1]))
            time_value2 = time_array2[time_slice2]
            try:
                if args.dd_update:
                    wall2 = connection2.get("wall", autoconvert=False)
                    wall2 = imas.convert_ids(wall2, connection2.factory.version)
                else:
                    wall2 = connection2.get("wall", autoconvert=False)
            except Exception as e:
                logger.warning(f"Could not load wall data for second connection: {e}")
                wall2 = None

            if connection2 is None:
                logger.critical("----> Could not open second data entry.")
                exit(1)

    canvas = PlotCanvas(1, 4)
    canvas.update_style(args.rc)
    ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
    ax2 = canvas.add_axes(title="", xlabel="", row=0, col=1)
    ax3 = canvas.add_axes(title="", xlabel="", row=0, col=2)
    ax4 = canvas.add_axes(title="", xlabel="", row=0, col=3)
    equiview = EquilibriumView(equilibrium1)
    if equilibrium2:
        equiview.view_profile_plot(ax1, time_slice1, equilibrium2_ids=equilibrium2, time_index2=time_slice2)
    else:
        equiview.view_profile_plot(ax1, time_slice1)

    if wall1:
        wallview1 = WallView(wall1)
        wallview1.view_inner_wall_line(ax2)
    if wall2:
        wallview2 = WallView(wall2)
        wallview2.view_inner_wall_line(ax2)

    if equilibrium2:
        equiview.view_equilibrium_plot(ax2, time_index1=time_slice1, equilibrium2_ids=equilibrium2)
        equiview.view_current_plot(ax3, time_index1=time_slice1, equilibrium2_ids=equilibrium2)
        equiview.view_constraints(ax4, time_index1=time_slice1, equilibrium2_ids=equilibrium2)
    else:
        equiview.view_equilibrium_plot(ax2, time_index1=time_slice1)
        equiview.view_current_plot(ax3, time_index1=time_slice1)
        equiview.view_constraints(ax4, time_index1=time_slice1)

    if len(args.uri) == 2:
        y = 0.97
        canvas.fig.text(0.5, y, args.uri[0] + f"(time {time_value1}), ", ha="right", va="top", color="tab:green")
        canvas.fig.text(0.5, y, args.uri[1] + f"(time {time_value2})", ha="left", va="top", color="tab:blue")
    else:
        canvas.fig.suptitle(f"{args.uri[0]} time {time_value1}")
    canvas.fig.subplots_adjust(top=0.916, bottom=0.101, left=0.044, right=0.946, hspace=0.216, wspace=0.240)
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    if args.save:
        fname = f"plotequicomp_time_{time_value1}.png"
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()
