#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# migrated from rotationplot

import argparse
import logging
import os
from rich_argparse import RichHelpFormatter

import imas
import sys
from idstools.compute.common import get_nearest_time
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentry_parser,
    get_database_path,
    get_file_name,
    get_title,
)
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.core_profiles import CoreProfilesView

parser = argparse.ArgumentParser(
    description="---- Display the efield, toroidal, polidal velocities from the core_profiles IDSs [previously known as rotationplot]",
    parents=[dbentry_parser],
    formatter_class=RichHelpFormatter,
)

parser.add_argument("-t", "--time", help="Time", required=False, type=float, default=99.0)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()
logger = setup_logger("module", stdout_level=logging.i_n_f_o)

connection = DBMaster.get_connection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

try:
    ids_core_profiles = imas.core_profiles()
    ids_core_profiles.time = connection.partial_get("core_profiles", "time")
    if ids_core_profiles.time is None:
        logger.critical("No core_profiles IDS in the data-entry --> Abort.")
        exit()
except Exception as e:
    logger.critical("The core_profiles IDS is absent from the input data-entry")
    logger.critical("----> Aborted.")
    exit()

# Search for adequate time slice for display
time_array = ids_core_profiles.time
time_index, time_value = get_nearest_time(time_array, args.time)
ntime = len(ids_core_profiles.time)

# Read 1D-profiles for this time slice
ids_core_profiles.profiles_1d.resize(1)
ids_core_profiles.profiles_1d[0] = connection.partial_get("core_profiles", f"profiles_1d({time_index})")

canvas = PlotCanvas(2, 2)

ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax2 = canvas.add_axes(title="", xlabel="", row=0, col=1)
ax3 = canvas.add_axes(title="", xlabel="", row=1, col=0)
ax4 = canvas.add_axes(title="", xlabel="", row=1, col=1)


coreprofiles_view = CoreProfilesView(ids_core_profiles)

coreprofiles_view.plot_efield_profile(ax1)
coreprofiles_view.plot_toroidal_velocity_profile(ax2)
coreprofiles_view.plot_poloidal_velocity_profile(ax3)
coreprofiles_view.plot_diamagnetic_velocity_profile(ax4)

ax1.sharex(ax3)
ax2.sharex(ax4)

canvas.set_text(text=f"{get_database_path(args, time_value=time_value)}")

canvas.fig.subplots_adjust(top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.174, wspace=0.117)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
canvas.fig.suptitle(get_title(args, "Kinetic profiles", time_value), size=12)

if args.save:
    fname = get_file_name(args, os.path.basename(__file__) + "_Kinetic_profiles", time_value)
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname = os.path.join(args.directory, fname)
    canvas.save(fname)
else:
    canvas.show()
