#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.domain.kineticprofiles import KineticProfilesView

# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Display the plasma kinetic profiles from the core_profiles IDSs [previously known as kinplot]",
    parents=[dbentryParser],
    formatter_class=RichHelpFormatter,
)

parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=-99.0
)
parser.add_argument(
    "-e", "--edge", help="Add edge profiles if available", action="store_true"
)
parser.add_argument("--verbose", help="Verbose output", action="store_true")
parser.add_argument(
    "--logscale",
    help="Shows y axis with logarithmic scale wherever appropriate",
    action="store_true",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()
if args.verbose:
    logger = setupLogger("module", stdout_level=logging.DEBUG)
else:
    logger = setupLogger("module", stdout_level=logging.INFO)

connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

kpView = KineticProfilesView(connection, args.edge, args.time)

hostdir = getDatabasePath(args)

canvas = Canvas(3, 4)
ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0, colspan=2)
ax2 = canvas.add_axes(title="", xlabel="", row=1, col=0, colspan=2)
ax3 = canvas.add_axes(title="", xlabel="", row=2, col=0, colspan=2)
ax4 = canvas.add_axes(title="", xlabel="", row=0, col=2)
ax5 = canvas.add_axes(title="", xlabel="", row=1, col=2)
ax6 = canvas.add_axes(title="", xlabel="", row=2, col=2)
ax7 = canvas.add_axes(title="", xlabel="", row=0, col=3)
ax8 = canvas.add_axes(title="", xlabel="", row=1, col=3)

if kpView.kProfiles.isCoreProfilesPresent:
    kpView.viewCentralTemperatureWaveforms(ax1)  # Central temperature waveforms
    kpView.viewCentralDensityWaveforms(
        ax2, logscale=args.logscale
    )  # Central density waveforms
    kpView.viewCentralZeffWaveform(ax3)  # Central Zeff waveform
    kpView.viewTemperatureProfiles(ax4)  # Temperature profiles
    kpView.viewZeffProfile(ax5)  # Zeff profiles
    kpView.viewVpolProfile(ax6, logscale=args.logscale)  # Vpol profiles
    kpView.viewDensityProfiles(ax7, logscale=args.logscale)  # Density profiles
    kpView.viewVtorProfile(ax8, logscale=args.logscale)  # Vtol profiles

    canvas.setText(
        text=f"{getDatabasePath(args, timeValue=kpView.kProfiles.commonTime)}"
    )

    canvas.fig.subplots_adjust(
        top=0.928, bottom=0.11, left=0.033, right=0.91, hspace=0.435, wspace=0.518
    )
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))

    canvas.fig.suptitle(
        getTitle(args, "Plasma kinetic profiles ", kpView.kProfiles.commonTime), size=12
    )

    if args.save:
        fname = getFileName(
            args, os.path.basename(__file__) + "_Kinetic", kpView.kProfiles.commonTime
        )
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()
