#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# migrated from pressureplot

import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter

import imas

from idstools.compute.common import get_nearest_time
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentry_parser,
    get_database_path,
    get_file_name,
    get_title,
)
from idstools.utils.idslogger import setup_logger
from idstools.view.common import PlotCanvas
from idstools.view.core_profiles import CoreProfilesView

logger = setup_logger("module", stdout_level=logging.i_n_f_o)

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Display the plasma pressure properties from the core_profiles IDS [previsouly known as pressureplot]",
    epilog="""
""",
    formatter_class=RichHelpFormatter,
    parents=[dbentry_parser],
)

parser.add_argument("-t", "--time", type=float, help="Time", default=-99)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()

connection = DBMaster.get_connection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)


try:
    ids_core_profiles = imas.core_profiles()
    ids_core_profiles.time = connection.partial_get("core_profiles", "time")
    if ids_core_profiles.time is None:
        logger.critical("No core_profiles IDS in the data-entry --> Abort.")
        exit()
except Exception as e:
    logger.critical("The core_profiles IDS is absent from the input data-entry")
    logger.critical("----> Aborted.")
    exit(1)

time_array = ids_core_profiles.time
time_index, time_value = get_nearest_time(time_array, args.time)

ids_core_profiles.profiles_1d.resize(1)  # Read 1D-profiles for this time slice
ids_core_profiles.profiles_1d[0] = connection.partial_get("core_profiles", f"profiles_1d({time_index})")
title = "Profiles displayed for t = " + "%.1f" % time_value + " s"
canvas = PlotCanvas(3, 1)
canvas.fig.suptitle(title, size=12)

ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0, colspan=1)
ax2 = canvas.add_axes(title="", xlabel="", row=1, col=0, colspan=1)
ax3 = canvas.add_axes(title="", xlabel="", row=2, col=0, colspan=1)

coreprofiles_view = CoreProfilesView(ids_core_profiles)

coreprofiles_view.plot_total_pressure_properties(ax1)
coreprofiles_view.plot_ion_pressure_properties(ax2)
coreprofiles_view.plot_electron_pressure_properties(ax3)

canvas.set_text(text=f"{get_database_path(args, time_value=time_value)}")

canvas.fig.subplots_adjust(top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
canvas.fig.suptitle(get_title(args, "Pressure", time_value), size=12)

if args.save:
    fname = get_file_name(args, os.path.basename(__file__) + "_Pressure", time_value)
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname = os.path.join(args.directory, fname)
    canvas.save(fname)
else:
    canvas.show()
