#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.waves import WavesView

# MANAGEMENT OF INPUT ARGUMENTS
# ------------------------------
parser = argparse.ArgumentParser(
    description="---- Display EC results [previously known as eccomp]", parents=[dbentryParser],formatter_class=RichHelpFormatter,
)
parser.add_argument(
    "-t",
    "--time",
    help="Time for which profiles are displayed",
    type=float,
    default=-99.0,
)
parser.add_argument(
    "-f",
    "--force_psi",
    help="= 1 to force displaying the profiles versus poloidal flux",
    type=int,
    default=0,
)
parser.add_argument(
    "--verbose",
    help="= 1 to display numerical analysis of gaussian profiles",
    action="store_true",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None, 
)
args = parser.parse_args()

logger = setupLogger("module", stdout_level=logging.INFO)


verbose = args.verbose
# Flag to force psi radial coordinate to be used
force_psi = int(args.force_psi)


conn = DBMaster.getConnection(args)
if conn is None:
    logger.critical("----> Aborted.")
    exit(1)

idsWaves = conn.get("waves")
conn.close()

# TIME VECTOR AND TIME INDEX
# ---------------------------
timeArray = idsWaves.time
ntime = len(timeArray)
timeIndex, timeValue = getNearestTime(timeArray, args.time)
time = timeValue
rows = 2
if ntime == 1:
    logger.error("Only one time slice --> ECCD and ECRH waveforms not displayed")
    rows = 1
canvas = Canvas(rows, 2)
ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax2 = canvas.add_axes(title="", xlabel="", row=0, col=1)
if ntime != 1:
    ax3 = canvas.add_axes(title="", xlabel="", row=1, col=0)
    ax4 = canvas.add_axes(title="", xlabel="", row=1, col=1)

wavesView = WavesView(idsWaves)

wavesView.displayECLaunchersInfo(timeIndex=timeIndex)
wavesView.plotECRHProfiles(ax1, timeIndex=timeIndex, verbose=args.verbose)
wavesView.plotECCDProfiles(ax2, timeIndex=timeIndex, verbose=args.verbose)
if ntime != 1:
    wavesView.plotECRHWaveform(ax3, timeIndex=timeIndex)
    wavesView.plotECCDWaveform(ax4, timeIndex=timeIndex)

canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")
canvas.fig.suptitle(getTitle(args, "EC Composition", timeValue), size=12)
canvas.fig.subplots_adjust(
    top=0.941, bottom=0.122, left=0.052, right=0.925, hspace=0.2, wspace=0.2
)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))

if args.save:
    fname = getFileName(args, os.path.basename(__file__)+"_EC_Composition", timeValue)
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname=os.path.join(args.directory,fname)
    canvas.save(fname)
else:
    canvas.show()

# def StrToList(string):
#     if string[0] == "[":
#         slist = string.split(",")
#         slist[0] = slist[0][1:]
#         slist[-1] = slist[-1][:-1]
#         slist = [int(slist[i]) for i in range(len(slist))]
#         return slist
#     else:
#         return [int(string)]
# pulseString, runString = args.pulse, args.run
# pulseList, runList = StrToList(pulseString), StrToList(runString)
# assert len(pulseList) <= len(
#     runList
# ), "There must be a run number corresponding to each pulse"

# if len(runList) > len(pulseList):
#     assert (
#         len(pulseList) == 1
#     ), "Either give a pulse for each run or give a single pulse for every run"
#     pulseList = len(runList) * pulseList
# nsimu = len(pulseList)
# for isimu in range(len(pulseList)):
#     ipulse = pulseList[isimu]
#     irun = runList[isimu]
#     # Reading in data from run in pulse
#     logger.info(
#         f"Open pulse: {ipulse}/{irun} in DB {args.user}/{args.database}/{args.version}"
#     )
