#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# migrated from print_fluxes by David.Coster@ipp.mpg.de

import argparse
import logging
import sys

from rich_argparse import RichHelpFormatter
from idstools.database import DBMaster

from imas import imasdef

from idstools.utils.clihelper import dbentry_parser, get_database_path
from idstools.utils.idslogger import setup_logger
from idstools.view.core_transport import CoreTransportView

logger = setup_logger("module", stdout_level=logging.i_n_f_o)

slicing_methods = {
    "CLOSEST": imasdef.c_l_o_s_e_s_t__i_n_t_e_r_p,
    "PREVIOUS": imasdef.PREVIOUS_INTERP,
    "LINEAR": imasdef.l_i_n_e_a_r__i_n_t_e_r_p,
}
# Management of input arguments
parser = argparse.ArgumentParser(
    description="View information about fluxes [Previously known as print_fluxes]",
    epilog="""
""",
    formatter_class=RichHelpFormatter,
    parents=[dbentry_parser],
)

parser.add_argument(
    "-m",
    "--slicingmethod",
    type=str,
    default="CLOSEST",
    choices=["CLOSEST", "PREVIOUS", "LINEAR"],
    help="Slicing method \t(default=%(default)s)",
)

parser.add_argument("-o", "--occurrence", type=int, default=0, help="occurrence")
parser.add_argument("-t", "--time", type=float, help="Time", default=-99)
args = parser.parse_args()

connection = DBMaster.get_connection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

ids_slice_core_transport = connection.get_slice(
    "core_transport",
    args.time,
    slicing_methods[args.slicingmethod],
    occurrence=args.occurrence,
)
if len(ids_slice_core_transport.time) == 0:
    logger.critical("Time vector is empty! aborting")
    sys.exit(1)

print(f"Showing details for {get_database_path(args, ids_slice_core_transport.time[0])}")

core_transport_view = core_transport_view(ids_slice_core_transport)
core_transport_view.view_fluxes()
