#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
from idstools.database import DBMaster
from idstools.utils.clihelper import getCoreVersion
from rich.console import Console
from rich.syntax import Syntax
from rich.table import Table
from rich_argparse import RichHelpFormatter
from idstools.scenariodescription import ScenarioDescription
from idstools.utils.idslogger import setupLogger
console = Console()
# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Show status and potential parent and children for a given simulation stored in ITER database folder",formatter_class=RichHelpFormatter,
)
parser.add_argument(
    "-f", "--folder", help="folder where to search for scenarios", required=False
)
parser.add_argument("-s", "--shot", help="Shot number", required=True, type=int)
# currently limiting run < 10000 because of the search path /3/0
parser.add_argument(
    "-r",
    "--run",
    help="run number",
    required=True,
    type=int,
    choices=range(0, 9999),
    metavar="[0-9999]",
)
parser.add_argument(
    "--print",
    help="print yaml on console",
    action="store_true",
)
args = vars(parser.parse_args())

logger = setupLogger("module")

shot = args["shot"]
run = args["run"]

# FOLDER
folder = ""
if args["folder"] is not None:
    folder = args["folder"]
else:
    folder = os.environ["IMAS_HOME"] + "/shared/imasdb/ITER/3/0"
    lowlevelVersion = DBMaster.getCoreVersion()
    lowlevelVersion = int(lowlevelVersion.split(".")[0])
    if lowlevelVersion < 4:
        folder = os.environ["IMAS_HOME"] + "/shared/iterdb/3/0"
sdObject = ScenarioDescription(shot, run, folder)
if args["print"] is True:
    sdObject.printYaml()
    exit(0)

family = sdObject.getFamily()

table = Table(
    title="Scenario Status"
)
table.add_column("SCENARIO", style="magenta")
table.add_column("STATUS", style="green")
table.add_column("REASON WHY IT REPLACES PREVIOUS", style="green")

for iparent in range(len(family["parents"]["shot"])):
    table.add_row(
        f" {family['parents']['shot'][iparent]:>7}{family['parents']['run'][iparent]:>5}", f"{family['parents']['status'][iparent]:<10}", f"{family['parents']['comment'][iparent]}"
    )
if "database_relations" in sdObject.yamlData.keys():
    if "replaced_by" in sdObject.yamlData["database_relations"].keys():
        table.add_row(
            f"*{shot:>7}{run:>5}",f"{sdObject.yamlData['status']:<10}",f"{sdObject.yamlData['database_relations']['replaces']}"
        )
else:
    logger.warn("database relations not found")
for ichild in range(len(family["children"]["shot"])):
    table.add_row(
        f" {family['children']['shot'][ichild]:>7}{family['children']['run'][ichild]:>5}",f"{family['children']['status'][ichild]:<10}",f"{family['children']['comment'][ichild]}"
    )
    
console.print(table)
