#!/usr/bin/env python
import argparse
import json
import logging
import os
import sys


import imas
import numpy as np

from idstools.view.common import Canvas
from idstools.compute.common import getNearestTime
from idstools.compute.core_profiles import CoreProfilesCompute
from idstools.compute.summary import SummaryCompute
from idstools.utils.clihelper import getBackendID, getDatabasePath, imasParser
from idstools.utils.idslogger import setupLogger

# ----------------------------------------------------------------------

# Management of input arguments
parser = argparse.ArgumentParser(description=\
                                 '---- Display the plasma kinetic profiles and equilibrium from the core_profiles and equilibrium IDSs', parents=[imasParser])
parser.add_argument('-s','--shot',help='Shot number', required=True,type=int)
parser.add_argument('-r','--run',help='Run number',required=True,type=int)
group = parser.add_mutually_exclusive_group()
group.add_argument('-t','--time',help='Time for profiles',required=False,type=float,default=-99.0)
group.add_argument('-n','--noProfiles',action='store_true',help='Do not plot profiles or equilibrium')
parser.add_argument('-T', '--Title', action='store_true',
                    help='Add title with additional provenance information')
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
args = parser.parse_args()
logger = setupLogger("module", stdout_level=logging.INFO)
# For execution from python shell
#args = {'run': 6, 'database': None, 'user': None, 'time': None, 'shot': 4321}


# Open the database and read the necessary IDSs
connection = imas.DBEntry(getBackendID(args.backend), args.database, args.shot, args.run, user_name=args.user, data_version=args.version)
err,n = connection.open()
if err != 0:
    logger.critical(
        f"Shot {str(args.shot)}, run {str(args.run)} for user_or_path = {args.user} and database = {args.database} does not exist",
    )
    logger.critical(
        "----> Aborted.",
    )
    exit()

hostdir = getDatabasePath(args)
if hostdir is None:
    logger.critical(
        "Environment variable IMAS_HOME is not defined. Quitting.",
    )
    exit(1)
    
# if args.user == 'public':
#     publichome = os.getenv("IMAS_HOME")
#     if (publichome == None):
#         print("Environment variable IMAS_HOME is not defined. Quitting.", file=sys.stderr)
#         sys.exit(1)
#     DB_ABS_PATH = publichome+'/shared/imasdb/'+args.database+'/'+args.version+'/'+str(args.run//10000)
# else:
#     DB_ABS_PATH = os.path.expanduser("~{}".format(args.user))+"/public/imasdb/"+args.database+"/"+args.version+"/"+str(args.run//10000)



# ----------------------------------------------------------------------

# hostdir = os.environ["HOSTNAME"]+":"+DB_ABS_PATH
# hostdir = hostdir[:-2]



# ----------------------------------------------------------------------




if not args.noProfiles:
    try:
        #input.core_profiles.get()
        core_profiles = imas.core_profiles() # To initialise the empty IDS structure
        core_profiles.time = connection.partial_get('core_profiles','time')
        core_profiles.global_quantities = connection.partial_get('core_profiles','global_quantities')
        if core_profiles.time is None:
            logger.critical('No core_profiles IDS in the data-entry --> Abort.', file=sys.stderr)
            exit()
    except:
        logger.critical('The core_profiles IDS is absent from the input data-entry', file=sys.stderr)
        logger.critical('----> Aborted.', file=sys.stderr)
        exit()

    try:
        #input.equilibrium.get()
        equilibrium = imas.equilibrium() # To initialise the empty IDS structure
    except:
        logger.critical('The equilibrium IDS is absent from the input data-entry', file=sys.stderr)
        logger.critical('----> Aborted.', file=sys.stderr)
        exit()

    # Search for adequate time slice for display
    timevec = core_profiles.time
    ntime = len(core_profiles.time)
    it, tc = getNearestTime(timevec, args.time)

    # ntime = len(core_profiles.time)
    # timevec = core_profiles.time
    # if ntime > 1:
    #     if args.time >= 0:
    #         [tc,it] = find_nearest(timevec,args.time)
    #     else:
    #         it = int(ntime/2)
    #         tc = timevec[it]
    #     time = tc
    #     print('   Time  = '+'%.2f' % tc+' s in range ['+'%.2f' % timevec[0]+','+'%.2f' % timevec[ntime-1]+'] s', file=sys.stderr)
    #     print('   Index = ',str(it), file=sys.stderr)
    #     print('   Averaged resolution = ', (timevec[ntime-1]-timevec[0])/(ntime-1),' s', file=sys.stderr)
    # else:
    #     if len(timevec) > 0:
    #         tc = timevec[0]
    #     else:
    #         tc = 0
    #     it = 0

    # Read 1D-profiles for this time slice
    core_profiles.profiles_1d.resize(1)
    core_profiles.profiles_1d[0] = connection.partial_get('core_profiles','profiles_1d('+str(it)+')')

    # Below is less optimal than global partialGet on profiles_1d (keep it here for reference)
    #core_profiles.profiles_1d[0].grid.rho_tor_norm = input.core_profiles.partialGet('profiles_1d('+str(it)+')/grid/rho_tor_norm')
    #core_profiles.profiles_1d[0].grid.rho_tor      = input.core_profiles.partialGet('profiles_1d('+str(it)+')/grid/rho_tor')
    #core_profiles.profiles_1d[0].j_bootstrap       = input.core_profiles.partialGet('profiles_1d('+str(it)+')/j_bootstrap')
    #core_profiles.profiles_1d[0].j_non_inductive   = input.core_profiles.partialGet('profiles_1d('+str(it)+')/j_non_inductive')
    #core_profiles.profiles_1d[0].j_ohmic           = input.core_profiles.partialGet('profiles_1d('+str(it)+')/j_ohmic')
    #core_profiles.profiles_1d[0].j_total           = input.core_profiles.partialGet('profiles_1d('+str(it)+')/j_total')
    #core_profiles.profiles_1d[0].q                 = input.core_profiles.partialGet('profiles_1d('+str(it)+')/q')
    #core_profiles.profiles_1d[0].magnetic_shear    = input.core_profiles.partialGet('profiles_1d('+str(it)+')/magnetic_shear')

    equilibrium.time_slice.resize(1)
    equilibrium.time_slice[0].profiles_2d.resize(1)

    # Here individual partialGet seems more optimal than a global one on profiles_2d (not very clear)
    #equilibrium.time_slice[0].profiles_2d[0].r   = input.partial_get('equilibrium','time_slice('+str(it)+')/profiles_2d(0)/r')
    #equilibrium.time_slice[0].profiles_2d[0].z   = input.partial_get('equilibrium','time_slice('+str(it)+')/profiles_2d(0)/z')
    #equilibrium.time_slice[0].profiles_2d[0].psi = input.partial_get('equilibrium','time_slice('+str(it)+')/profiles_2d(0)/psi')
    equilibrium.time_slice[0].profiles_2d   = connection.partial_get('equilibrium','time_slice('+str(it)+')/profiles_2d')
    if len(equilibrium.time_slice[0].profiles_2d) == 0:
        plot_equi = 0
    else:
        if len(equilibrium.time_slice[0].profiles_2d[0].grid.dim1)>0:
            plot_equi = 1
        else:
            plot_equi = 0

    time = tc

    # psi(R,Z) (not mandatory)
    if plot_equi == 1:
        if equilibrium.time_slice[0].profiles_2d[0].psi is None or len(equilibrium.time_slice[0].profiles_2d[0].psi)==0:
            print('equilibrium.time_slice[:].profiles_2d[0].psi could not be read', file=sys.stderr)
            plot_equi = 0
        if equilibrium.time_slice[0].profiles_2d[0].r is None or len(equilibrium.time_slice[0].profiles_2d[0].r)==0:
            print('equilibrium.time_slice[:].profiles_2d[0].r could not be read', file=sys.stderr)
            plot_equi = 0
        if equilibrium.time_slice[0].profiles_2d[0].z is None or len(equilibrium.time_slice[0].profiles_2d[0].z)==0:
            print('equilibrium.time_slice[:].profiles_2d[0].z could not be read', file=sys.stderr)
            plot_equi = 0

    # Rho profile (mandatory)
    computeObj = CoreProfilesCompute(core_profiles)
    profiles = computeObj.getProfiles(0)
    if profiles is None:
        exit(0)
    
    # try:
    #     rho_tor_norm = 0
    #     if len(core_profiles.profiles_1d[0].grid.rho_tor_norm) > 0:
    #         nrho = len(core_profiles.profiles_1d[0].grid.rho_tor_norm)
    #         rho_tor_norm = core_profiles.profiles_1d[0].grid.rho_tor_norm
    #     elif len(core_profiles.profiles_1d[0].grid.rho_tor) > 0:
    #         nrho = len(core_profiles.profiles_1d[0].grid.rho_tor)
    #         rho_tor_norm = core_profiles.profiles_1d[0].grid.rho_tor/core_profiles.profiles_1d[0].grid.rho_tor[nrho-1]
    # except:
    #     print('core_profiles.profiles_1d[:].grid.rho_tor_norm and rho_tor could not be read', file=sys.stderr)
    #     print('----> Aborted.', file=sys.stderr)
    #     exit()


try:
    summary = connection.get('summary') 
except:
    logger.critical('The summary IDS is absent from the input data-entry', file=sys.stderr)
    logger.critical('----> Aborted.', file=sys.stderr)
    exit()


stime = len(summary.time)

if stime < 1:
    logger.critical('The summary IDS is absent from the input data-entry', file=sys.stderr)
    logger.critical('----> Aborted.', file=sys.stderr)
    sys.exit(1)

summaryComputeObj = SummaryCompute(summary)
waveform = summaryComputeObj.getSummary()



if np.size(waveform['h_mode'][2:]) > 2:
    def indices(a, func):
        return [i for (i, val) in enumerate(a) if func(val)]
    h_mode_indices  = indices(waveform['h_mode'][2:], lambda h_mode_flag: h_mode_flag>0)
    if len(h_mode_indices) > 0:
        HModePresent = True
        th_min = summary.time[h_mode_indices[0]]
        th_max = summary.time[h_mode_indices[-1]]
    else:
        HModePresent = False
else:
    HModePresent = False
# Starts plotting
import matplotlib

if 'DISPLAY' not in os.environ:
    matplotlib.use('agg')
else:
    matplotlib.use('TKagg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# Tick size and X and Y axes
ticksize = 12
fontsize = 12

# Font definition
font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}

# Frame configuration
nline = 4
if args.noProfiles:
    ncol = 2
else:
    ncol = 4
legx_pos = 1.28
legy_pos = 1.05

# Plot signature
def Signature(hostdir,shot,run,plt):
    ax = plt.gca()
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    #plt.text(xmax+0.01*abs(xmax),ymax,hostdir[:-2]+' - Shot '+str(shot)+' / '+' Run '+str(run),fontsize=6,rotation=90)
    plt.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(shot)+' / '+' Run '+str(run),fontsize=5,rotation=90)
    return

# Legend customization
def CustomLegend_wf(legend,fontsize):
    frame = legend.get_frame()
    frame.set_facecolor('0.95')
    for label in legend.get_texts():
        label.set_fontsize(fontsize)
    for label in legend.get_lines():
        label.set_linewidth(1.5)  # the legend line width
    return

def CustomLegend_pr(legend):
    frame = legend.get_frame()
    frame.set_facecolor('0.95')
    for label in legend.get_texts():
        label.set_fontsize(7)
    for label in legend.get_lines():
        label.set_linewidth(1.5)  # the legend line width
    return

# Plot customization
def nice(plt,x_label_string,y_label_string,fontsize):
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
    plt.xticks(fontsize = ticksize)
    plt.yticks(fontsize = ticksize)
    plt.xlabel(x_label_string, fontdict=font, labelpad = 5)
    plt.ylabel(y_label_string, fontdict=font, labelpad = 0)
    plt.grid()
    if len(x_label_string) < 1:
        plt.tick_params(axis='x',which='both',bottom=False,top=False,labelbottom=False)

def hmode_display(plot,thmin,thmax):
    ymin = plot.gca().get_ylim()[0]
    ymax = plot.gca().get_ylim()[1]
    fill([th_min,th_max,th_max,th_min],[ymin,ymin,ymax,ymax],\
         'lightyellow',  edgecolor='k',linewidth=0.08,label=r'$H_{mode}$')
    plt.gca().set_ylim(ymin,ymax)
    return

def time_display(plot,time):
    ymin = plot.gca().get_ylim()[0]
    ymax = plot.gca().get_ylim()[1]
    plot.plot([time,time],[ymin,ymax],color='gray',linestyle='--',linewidth=2,label=r'$t_{slice}$')
    plt.gca().set_ylim(ymin,ymax)
# Display the figure

single_style='o'
multi_style='-'
plotstyle = multi_style if len(waveform['time']) > 1 else single_style

title = "Profiles displayed for t = " + "%.1f" % it + " s"
canvas = Canvas(4, 2)
ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax2 = canvas.add_axes(title="", xlabel="", row=1, col=0, sharex=ax1)
ax3 = canvas.add_axes(title="", xlabel="", row=2, col=0, sharex=ax1)
ax4 = canvas.add_axes(title="", xlabel="", row=3, col=0, sharex=ax1)
ax5 = canvas.add_axes(title="", xlabel="", row=0, col=1, rowspan=2)
ax6 = canvas.add_axes(title="", xlabel="", row=2, col=1)
ax7 = canvas.add_axes(title="", xlabel="", row=3, col=1)

# H&CD waveforms
# ax1 = plt.subplot2grid((nline,ncol), (0,0), colspan=2)
def viewHCDWaveforms(ax):
    if max(waveform['p_hcd']) > 0:
        ax.plot(waveform['time'],waveform['p_hcd']*1.e-6,plotstyle,label=r'$P_{HCD}$')

    if max(waveform['p_ec']) > 0:
        ax.plot(waveform['time'],waveform['p_ec']*1.e-6,plotstyle,label=r'$P_{EC}$')

    if max(waveform['p_ic']) > 0:
        ax.plot(waveform['time'],waveform['p_ic']*1.e-6,plotstyle,label=r'$P_{IC}$')

    if max(waveform['p_nbi']) > 0:
        ax.plot(waveform['time'],waveform['p_nbi']*1.e-6,plotstyle,label=r'$P_{NBI}$')

    if max(waveform['p_lh']) > 0:
        ax.plot(waveform['time'],waveform['p_lh']*1.e-6,plotstyle,label=r'$P_{LH}$')

    # Fusion waveforms
    if max(waveform['p_fusion']) > 0:
        ax.plot(waveform['time'],waveform['p_fusion']*1.e-6,plotstyle,label=r'$P_{FUS}$')

    if max(waveform['p_neutron']) > 0:
        ax.plot(waveform['time'],waveform['p_neutron']*1.e-6,plotstyle,label=r'$P_{NEUT}$')

    if max(waveform['p_ohmic']) > 0:
        ax.plot(waveform['time'],waveform['p_ohmic']*1.e-6,plotstyle,label=r'$P_{OHM}$')

    if max(waveform['p_steady']) > 0:
        ax.plot(waveform['time'],waveform['p_steady']*1.e-6,plotstyle,label=r'$P_{STEADY}$')

    ax.set_xlim(summary.time[0],summary.time[-1])

    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim() 
    if not args.noProfiles: 
        ax.plot([time,time],[ymin,ymax],color='gray',linestyle='--',linewidth=2,label=r'$t_{slice}$')
        
    if HModePresent == True: 
        ax.fill([th_min,th_max,th_max,th_min],[ymin,ymin,ymax,ymax],\
            'lightyellow',  edgecolor='k',linewidth=0.08,label=r'$H_{mode}$')
    
    ax.set_ylim(ymin,ymax)
    ticksize = 12
    fontsize = 12
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
    ax.tick_params(
            which="both",
            labelsize=ticksize,
        )
    ax.set_xlabel('', fontdict=font, labelpad = 5)
    ax.set_ylabel('$P\/[\mathrm{MW}]$', fontdict=font, labelpad = 0)
    ax.grid(True)
    
    ax.tick_params(axis='x',which='both',bottom=False,top=False,labelbottom=False)
    
    ax.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=5,rotation=90)
    
    legend = ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    frame = legend.get_frame()
    frame.set_facecolor("0.95")
    for label in legend.get_texts():
        label.set_fontsize(7)
    for label in legend.get_lines():
        label.set_linewidth(1.5)

    if not args.noProfiles:
        ax.set_title('Profiles displayed for t = '+'%.1f' % time+' s', fontdict=font)

def viewIpB0Waveforms(ax):
    # Ip, B0 waveforms
    # ax2 = plt.subplot2grid((nline,ncol), (1,0), sharex=ax1, colspan=2)
    ax.plot(waveform['time'],abs(waveform['ip'])*1.e-6,plotstyle,label=r'$|I_p|$')
    #plt.plot(waveform['time'],waveform['current_non_inductive']*1.e-6,label=r'$J_{NI}$')
    #plt.plot(waveform['time'],waveform['current_bootstrap']*1.e-6,label=r'$J_{BOOT}$')
    #plt.plot(waveform['time'],waveform['current_ohm']*1.e-6,label=r'$J_{OHM}$')
    ax.plot(waveform['time'],abs(waveform['b0']),plotstyle,label=r'$|B_0|$')
    
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim() 
    
    ax.set_xlim(summary.time[0],summary.time[-1])
    if not args.noProfiles: 
        ax.plot([time,time],[ymin,ymax],color='gray',linestyle='--',linewidth=2,label=r'$t_{slice}$')
    if HModePresent == 1: 
        ax.fill([th_min,th_max,th_max,th_min],[ymin,ymin,ymax,ymax],\
            'lightyellow',  edgecolor='k',linewidth=0.08,label=r'$H_{mode}$')

    ax.set_ylim(ymin,ymax)
    ticksize = 12
    fontsize = 12
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
    ax.tick_params(
            which="both",
            labelsize=ticksize,
        )
    ax.set_xlabel('', fontdict=font, labelpad = 5)
    ax.set_ylabel(r'$I_p\/[\mathrm{MA}], B_0\/[\mathrm{T}]$', fontdict=font, labelpad = 0)
    ax.grid(True)
    
    legend = ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    frame = legend.get_frame()
    frame.set_facecolor("0.95")
    for label in legend.get_texts():
        label.set_fontsize(7)
    for label in legend.get_lines():
        label.set_linewidth(1.5)
    
    ax.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=5,rotation=90)
    # Signature(hostdir,args.shot,args.run,plt)

def viewEnergyContentWaveforms(ax):
    ax.plot(waveform['time'],waveform['energy_total']*1.e-6,plotstyle,label=r'$W_{TOT}$')
    ax.plot(waveform['time'],waveform['energy_diamagnetic']*1.e-6,plotstyle,label=r'$W_{DIA}$')
    ax.plot(waveform['time'],waveform['energy_thermal']*1.e-6,plotstyle,label=r'$W_{TH}$')
    ax.plot(waveform['time'],waveform['energy_mhd']*1.e-6,plotstyle,label=r'$W_{MHD}$')
    
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim() 
    
    ax.set_xlim(summary.time[0],summary.time[-1])
    if not args.noProfiles: 
        ax.plot([time,time],[ymin,ymax],color='gray',linestyle='--',linewidth=2,label=r'$t_{slice}$')
    if HModePresent == 1: 
        ax.fill([th_min,th_max,th_max,th_min],[ymin,ymin,ymax,ymax],\
            'lightyellow',  edgecolor='k',linewidth=0.08,label=r'$H_{mode}$')

    ax.set_ylim(ymin,ymax)
    ticksize = 12
    fontsize = 12
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
    ax.tick_params(
            which="both",
            labelsize=ticksize,
        )
    ax.set_xlabel('', fontdict=font, labelpad = 5)
    
    ax.set_ylabel(r'$W\/[\mathrm{MJ}]}$', fontdict=font, labelpad = 0)
    ax.grid(True)
    
    legend = ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    frame = legend.get_frame()
    frame.set_facecolor("0.95")
    for label in legend.get_texts():
        label.set_fontsize(7)
    for label in legend.get_lines():
        label.set_linewidth(1.5)
        
    ax.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=5,rotation=90)

def viewVloopWaveforms(ax):
    ax.plot(waveform['time'],waveform['v_loop'],plotstyle,label=r'$V_{LOOP}$')
    ax.plot(waveform['time'],waveform['h_98'],plotstyle,label=r'$H_{98}$')
    ax.plot(waveform['time'],waveform['tau_energy'],plotstyle,label=r'$\tau_{E}$')
    ax.set_xlim(summary.time[0],summary.time[-1])
    
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim() 
    
    ax.set_xlim(summary.time[0],summary.time[-1])
    if not args.noProfiles: 
        ax.plot([time,time],[ymin,ymax],color='gray',linestyle='--',linewidth=2,label=r'$t_{slice}$')
    if HModePresent == 1: 
        ax.fill([th_min,th_max,th_max,th_min],[ymin,ymin,ymax,ymax],\
            'lightyellow',  edgecolor='k',linewidth=0.08,label=r'$H_{mode}$')

    ax.set_ylim(ymin,ymax)
    ticksize = 12
    fontsize = 12
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
    ax.tick_params(
            which="both",
            labelsize=ticksize,
        )
    ax.set_xlabel('$Time\/[\mathrm{s}]$', fontdict=font, labelpad = 5)
    ax.tick_params(axis='x',which='both',bottom=False,top=False,labelbottom=False)
    ax.set_ylabel(r'$V\/[\mathrm{V}],\/H,\/\tau\/[\mathrm{s}]$', fontdict=font, labelpad = 0)
    ax.grid(True)
    
    legend = ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    frame = legend.get_frame()
    frame.set_facecolor("0.95")
    for label in legend.get_texts():
        label.set_fontsize(7)
    for label in legend.get_lines():
        label.set_linewidth(1.5)
        
    ax.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=5,rotation=90)

def viewEquilibrium(ax):
    # Equilibrium
    # ax5 = plt.subplot2grid((nline,ncol), (0,3), rowspan=2)
    ticksize = 12
    fontsize = 12
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
        
    ax.xaxis.tick_top()
    ax.xaxis.set_label_position('top')
    if plot_equi == 1:
        r2d   = equilibrium.time_slice[0].profiles_2d[0].r
        z2d   = equilibrium.time_slice[0].profiles_2d[0].z
        psi2d = equilibrium.time_slice[0].profiles_2d[0].psi
        ax.contour(r2d,z2d,psi2d,50) #,label=r'$\Psi_{pol}$')
        ax.set_xlim(r2d.min(),r2d.max())
        ax.set_aspect('equal', adjustable='box')
        ax.set_xlabel('R (m)', fontdict=font)
        ax.set_ylabel('Z (m)', fontdict=font)
        
        ax.tick_params(
                which="both",
                labelsize=ticksize,
            )
        ax.set_xlabel('$R\/\mathrm{[m]}$', fontdict=font, labelpad = 5)
        ax.tick_params(axis='both',which='major',labelsize=ticksize)
        ax.set_ylabel(r'$Z\/\mathrm{[m]}$', fontdict=font, labelpad = 0)
        ax.tick_params(axis='x',which='both',bottom=False,top=False,labelbottom=False)
        ax.grid(True)

        xmin, xmax = ax.get_xlim()
        ymin, ymax = ax.get_ylim() 
        ax.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=5,rotation=90)
        #plt.title('Time = '+'%.1f' % time+' s', fontdict=font)
        #plt.title('2D equilibrium', fontdict=font)
    else:
        ax.text(0.2, 0.5, '2D equilibrium', fontsize=10)
        ax.text(0.2, 0.45, 'not available', fontsize=10)



# if not args.noProfiles:
def viewQProfileAndMagneticShearProfile(ax):
    # q-profile and magnetic shear profile
    ax.plot(profiles['rhonorm'],profiles['q'],label=r'$q$')
    ax.plot(profiles['rhonorm'],profiles['magnetic_shear'],label=r'$s=\frac{1}{q}\frac{dq}{d\rho}$')
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim() 
    
    #nice(plt,r'$\rho/\rho_0$','q, shear',fontsize)
    ticksize = 12
    fontsize = 12
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
    ax.tick_params(
            which="both",
            labelsize=ticksize,
        )
    ax.set_ylabel(r'$q,\/s$', fontdict=font, labelpad = 0)
    ax.grid(True)
    
    ax.set_xlim(0,1)
    legend = ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    frame = legend.get_frame()
    frame.set_facecolor("0.95")
    for label in legend.get_texts():
        label.set_fontsize(7)
    for label in legend.get_lines():
        label.set_linewidth(1.5)
        
    ax.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=5,rotation=90)
    

    # Current density profiles
def viewCurrentDesnityProfiles(ax):
    ax.plot(profiles['rhonorm'],profiles['j_total']*1.e-3,label=r'$j_{TOT}$')
    ax.plot(profiles['rhonorm'],profiles['j_non_inductive']*1.e-3,label=r'$j_{NI}$')
    ax.plot(profiles['rhonorm'],profiles['j_bootstrap']*1.e-3,label=r'$j_{BOOT}$')
    ax.plot(profiles['rhonorm'],profiles['j_ohmic']*1.e-3,label=r'$j_{OHM}$')
    
    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim() 
    
    ticksize = 12
    fontsize = 12
    font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
    ax.tick_params(
            which="both",
            labelsize=ticksize,
        )
    ax.set_xlabel(r'$\rho/\rho_0$', fontdict=font, labelpad = 5)
    ax.set_ylabel(r'$j\/[\mathrm{kA/m^2}]$', fontdict=font, labelpad = 0)
    ax.grid(True)
    
    ax.set_xlim(0,1)
    legend = ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    frame = legend.get_frame()
    frame.set_facecolor("0.95")
    for label in legend.get_texts():
        label.set_fontsize(7)
    for label in legend.get_lines():
        label.set_linewidth(1.5)
        
    ax.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=5,rotation=90)
    
    # legend = plt.legend(loc='upper right',bbox_to_anchor=(1.57,1.05),handlelength=1)
    # CustomLegend_wf(legend,legfsize)
    # Signature(hostdir,args.shot,args.run,plt)
    # ax = plt.gca()
    # xmin, xmax = ax.get_xlim()
    # ymin, ymax = ax.get_ylim()
    # plt.text(xmax,ymin-0.5*(ymax-ymin),hostdir+' - Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=6,color='black',ha='right')


        
viewHCDWaveforms(ax1)
viewIpB0Waveforms(ax2)
viewEnergyContentWaveforms(ax3)
viewVloopWaveforms(ax4)
viewEquilibrium(ax5)
viewQProfileAndMagneticShearProfile(ax6)
viewCurrentDesnityProfiles(ax7)


canvas.fig.tight_layout()
if args.save:
    if args.noProfiles:
        fname = 'summary_%s_%s_%s_%s_%s.png' % (args.user, args.database, args.version, args.shot, args.run)
    else:
        fname = 'Scenario'+'_shot_'+str(args.shot)+'_run_'+str(args.run)+'_time_'+'%.1f' % time+'.png'
        
    canvas.save(fname)
else:
    canvas.show()





# if args.noProfiles:
#     ax = plt.gca()
#     xmin, xmax = ax.get_xlim()
#     ymin, ymax = ax.get_ylim()
#     plt.text(xmax,ymin-0.5*(ymax-ymin),hostdir+' - Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=6,color='black',ha='right')

# if args.Title:
#     try:
#         dataset_description = connection.get('dataset_description')
#         if dataset_description.ids_properties.homogeneous_time==imas.imasdef.EMPTY_INT:
#             got_dataset_description = False
#         else:
#             got_dataset_description = True
#     except:
#         print('Warning: The dataset_description IDS is absent from the input data-entry', file=sys.stderr)
#         got_dataset_description = False
#     # F4F specific?
#     if got_dataset_description:
#         plt.suptitle('%s / %s / %s ; %s / %s\nprovider=%s, shot_date_time=%s\ndata_dictionary=%s, access_layer-%s' % (args.user, args.database, args.version, args.shot, args.run, summary.ids_properties.provider, dataset_description.pulse_time_begin, summary.ids_properties.version_put.data_dictionary, summary.ids_properties.version_put.access_layer))
#     else:
#         additional_data = ''
#         if summary.tag.name != '':
#             try:
#                 additional_data = json.loads(summary.tag.name)
#             except:
#                 additional_data = ''
#         if 'date' in additional_data:
#             plt.suptitle('%s / %s / %s ; %s / %s\nprovider=%s, shot_date=%s, shot_time=%s\ndata_dictionary=%s, access_layer=%s' % (args.user, args.database, args.version, args.shot, args.run, summary.ids_properties.provider, additional_data['date'], additional_data['time'], summary.ids_properties.version_put.data_dictionary, summary.ids_properties.version_put.access_layer))
#         else:
#             plt.suptitle('%s / %s / %s ; %s / %s\nprovider=%s, creation_date=%s\ndata_dictionary=%s, access_layer=%s' % (args.user, args.database, args.version, args.shot, args.run, summary.ids_properties.provider, summary.ids_properties.creation_date, summary.ids_properties.version_put.data_dictionary, summary.ids_properties.version_put.access_layer))

# # extra plots



# plt.subplots_adjust(left=0.1, bottom=None, right=0.85, top=None, wspace=0.1, hspace=0.1)
# #for ax in [ax1, ax2, ax3]:
# #    plt.setp(ax.get_xticklabels(), visible=False)
#     # The y-ticks will overlap with "hspace=0", so we'll hide the bottom tick
# #    ax.set_yticks(ax.get_yticks()[1:])
# Signature(hostdir,args.shot,args.run,plt)

# fig = plt.gcf()
# fig.set_size_inches(10,8)


# try:
#     if args.noProfiles:
#         fname = 'summary_%s_%s_%s_%s_%s.png' % (args.user, args.database, args.version, args.shot, args.run)
#     else:
#         fname = 'Scenario'+'_shot_'+str(args.shot)+'_run_'+str(args.run)+'_time_'+'%.1f' % time+'.png'
#     fig.savefig(fname, dpi=100)
#     print('----> Figure saved to '+fname, file=sys.stderr)
# except:
#     print('The figure could not be saved (check local permissions).', file=sys.stderr)

# plt.show()

