#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import os
import re
import textwrap
import time
import traceback

import imas
from rich.markdown import Markdown
from rich_argparse import RichHelpFormatter

from idstools import idschk
from idstools.db_validator import db_validator
from idstools.set_logger import set_logger
from idstools.utils.clihelper import get_backend_id, imas_parser

# ----------------------------------------------------------------------


def main():
    """
    Validation of IDSs
    """

    # Set validator for given (shot, run), otherwise whole shots found
    if args.shot:
        shot = [(args.shot, args.run)]
    else:
        shot = []

    logger.info(f"-----------------------------------------------------------")
    logger.info(f"START: {__file__}")
    logger.info(f"-----------------------------------------------------------")
    st = time.time()

    # Validation in IMASDB
    res = db_validator(
        args.user,
        args.database,
        args.version,
        args.backend,
        args.path,
        shot,
    )

    et = time.time()
    logger.info(f"-----------------------------------------------------------")
    logger.info(f"END: {__file__} [total elapsed time(s): {et-st:.2f}]")
    logger.info(f"-----------------------------------------------------------")


# ----------------------------------------------------------------------

description = f"""
Validation Tool for ITER Scenario DB
-------------------------------------

Usage:
~~~~~~

0) Load IMAS

.. code-block:: bash

    $ module load IMAS

1) Validate all shots in IMAS database against default schemas with output file

.. code-block:: bash

    $ {os.path.basename(__file__)} -o output.log

2) Check the validity of all shots in IMAS database against schemas

.. code-block:: bash

    $ {os.path.basename(__file__)} -s /path/to/schema1.yaml /path/to/schema2.yaml

3) Validate all shots in local database to default schemas

.. code-block:: bash

    $ {os.path.basename(__file__)} -u username -d database 

4) Validate one shot in IMAS database to schemas in the directory

.. code-block:: bash

    $ {os.path.basename(__file__)} -s 131024 -r 40 -s /path/to/schema/dir

5) Validate all shots having the shot number specified

.. code-block:: bash

    $ {os.path.basename(__file__)} -s 131024 -s /path/to/schema/dir
"""
if __name__ == "__main__":

    # Parse for command line options
    prog = os.path.basename(__file__)
    parser = argparse.ArgumentParser(
        prog=prog,
        formatter_class=RichHelpFormatter,
        parents=[imas_parser],
        description=Markdown(description, style="argparse.text"),
    )
    parser.add_argument("--shot", "-s", dest="shot", help="Shot number", required=False, type=int)
    parser.add_argument("--run", "-r", dest="run", help="Run number", required=False, type=int, default=-1)
    parser.add_argument(
        "--log",
        dest="log",
        help="Logging level, default=%(default)s",
        required=False,
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
    )
    parser.add_argument(
        "--output",
        "-o",
        dest="output",
        help="file name of IDS validation, no file output unless given",
        required=False,
        default=None,
    )
    parser.add_argument(
        "--path",
        dest="path",
        help="list of schema file and/or directory paths from which schema files are recursively loaded",
        required=False,
        nargs="+",
        default=[],
    )
    args = parser.parse_args()

    # Initialize logger
    logger = set_logger(__name__, logfile=args.output, level=args.log)

    try:
        main()
    except Exception as e:
        logger.error(traceback.format_exc())
