#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import os
from rich_argparse import RichHelpFormatter
from idstools.database import DBMaster
from idstools.idslist import available_in_dbentry
from idstools.machinedescription import MachineDescription
from idstools.utils.clihelper import (
    getDatabasePath,
    getDetailsfromURI,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.pf_active import PFActiveView
from idstools.view.wall import WallView

# ----------------------------------------------------------------------


logger = setupLogger("module", stdout_level=logging.INFO)
IDSES = "wall,pf_active"


def plotMachineDescription(idsData, showLabels=False):
    """
    The `plotMachineDescription` method is responsible for plotting the machine description based on the provided pulse list.
    """

    # Initialization
    canvas = Canvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="R (m)", ylabel="Z (m)", row=0, col=0)

    ax.set_aspect("equal", adjustable="box")

    databasePath = ""
    # Plot Overlay
    for idsName, idsDataAndConfig in idsData.items():
        # if idsDataAndConfig["yamlConfig"] is None:
        #     logger.error(f"Could not retrieve machine description for {idsName}")
        #     databasePath += f"{idsName} = not found"
        #     continue
        idsURI, idsName = idsName.split("#")
        if idsName == "pf_active":
            pfcoilsview = PFActiveView(idsDataAndConfig["idsData"])
            pfcoilsview.viewActivePfCoils(ax, showLabels=showLabels)
            databasePath += (
                "pf_active = "
                + getDatabasePath(idsDataAndConfig["connectionArgs"])
                + "\n"
            )

        elif idsName == "wall":
            wallview = WallView(idsDataAndConfig["idsData"])
            wallview.view_wall(ax, showLabels=showLabels)
            databasePath += (
                "wall = " + getDatabasePath(idsDataAndConfig["connectionArgs"]) + "\n"
            )
        else:
            databasePath += (
                f"{idsName} = "
                + getDatabasePath(idsDataAndConfig["connectionArgs"])
                + "No visualization yet\n"
            )
            logger.info(
                f"Visualization is not implemented yet for machine description {idsName}"
            )

    # wallview.view_DIR(ax)
    # wallview.view_TS(ax)
    # wallview.view_Cryostat(ax)

    ax.plot()

    xmin, xmax = ax.get_xlim()
    ymin, ymax = ax.get_ylim()
    ax.text(
        xmax + 0.01 * abs(xmax),
        ymin + 0.5 * abs(ymax - ymin),
        f"{databasePath}",
        horizontalalignment="left",
        verticalalignment="center",
        rotation="vertical",
        fontsize=7,
    )
    canvas.fig.subplots_adjust(
        top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2
    )
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    canvas.fig.suptitle("Machine Description", size=12)
    if args.save:
        fname = os.path.basename(__file__) + "_machine_description.png"
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname = os.path.join(args.directory, fname)
        canvas.save(fname)
    else:
        canvas.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="---- View and plot machine description with one or more URIs as data entries",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument(
        "-u",
        "--uri",
        nargs="*",
        default=[],
        help="""Provide machine descriptions that you need to plot\n
    with uris for example\n
    "imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3#wall"\n
    "imas:mdsplus?user=public;shot=116000;run=4;database=ITER_MD;version=3"\n
    """,
    )
    parser.add_argument(
        "--show-labels",
        help="Show labels",
        action="store_true",
    )
    parser.add_argument(
        "--save",
        help="Save figure at default location",
        action="store_true",
    )
    parser.add_argument(
        "--directory",
        help="Directory to save the figure",
        default=None,
    )
    args = parser.parse_args()
    machineDescription = MachineDescription()
    idsData = {}
    for mdidsInfo in args.uri:
        mdargs = argparse.Namespace()
        splittedmsIdsInfo = mdidsInfo.split("#")
        _idsNames = ""
        _mdUri = None
        if len(splittedmsIdsInfo) == 2:
            _mdUri, _idsNames = splittedmsIdsInfo
        if len(splittedmsIdsInfo) == 1:
            _mdUri = splittedmsIdsInfo[0]
        param = getDetailsfromURI(_mdUri)
        mdargs.backend = param["backend"]
        mdargs.database = param["database"]
        mdargs.pulse = param["pulse"]
        mdargs.run = param["run"]
        mdargs.user = param["user"]
        mdargs.version = param["version"]
        mdargs.uri = _mdUri
        connection = DBMaster.getConnection(mdargs)
        if connection:
            allIDSesList = [item for item, _ in available_in_dbentry(connection)]
            if _idsNames == "":
                _idsNames = IDSES
            for _idsName in _idsNames.split(","):
                if _idsName not in IDSES:
                    continue
                idsFound = False
                if connection is not None:
                    if _idsName in allIDSesList:
                        _idsData = connection.get(_idsName)

                        data = {}
                        if _idsData is not None:
                            idsFound = True
                            (
                                data["idsData"],
                                data["yamlConfig"],
                                data["connectionArgs"],
                            ) = (
                                _idsData,
                                None,
                                mdargs,
                            )
                            idsData[f"{_mdUri}#{_idsName}"] = data
                if not idsFound:
                    logger.info(
                        f"Data entry for {_idsName} is not given, retrieving from ITER machine description"
                    )
                    _mdData = machineDescription.getMDDataByIds(_idsName)
                    idsData[f"{_mdData['connectionArgs'].uri}#{_idsName}"] = _mdData
            connection.close()

    plotMachineDescription(idsData, args.show_labels)
