#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# migrated from print_fluxes by David.Coster@ipp.mpg.de

import argparse
import logging
import sys

from rich_argparse import RichHelpFormatter
from idstools.database import DBMaster

from imas import imasdef

from idstools.utils.clihelper import dbentryParser, getDatabasePath
from idstools.utils.idslogger import setupLogger
from idstools.view.core_transport import CoreTransportView

logger = setupLogger("module", stdout_level=logging.INFO)

slicingMethods = {
    "CLOSEST": imasdef.CLOSEST_INTERP,
    "PREVIOUS": imasdef.PREVIOUS_INTERP,
    "LINEAR": imasdef.LINEAR_INTERP,
}
# Management of input arguments
parser = argparse.ArgumentParser(
    description="View information about fluxes [Previously known as print_fluxes]",
    epilog="""
""",
    formatter_class=RichHelpFormatter,
    parents=[dbentryParser],
)

parser.add_argument(
    "-m",
    "--slicingmethod",
    type=str,
    default="CLOSEST",
    choices=["CLOSEST", "PREVIOUS", "LINEAR"],
    help="Slicing method \t(default=%(default)s)",
)

parser.add_argument("-o", "--occurrence", type=int, default=0, help="occurrence")
parser.add_argument("-t", "--time", type=float, help="Time", default=-99)
args = parser.parse_args()

connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

idsSliceCoreTransport = connection.get_slice(
    "core_transport",
    args.time,
    slicingMethods[args.slicingmethod],
    occurrence=args.occurrence,
)
if len(idsSliceCoreTransport.time) == 0:
    logger.critical("Time vector is empty! aborting")
    sys.exit(1)

print(f"Showing details for {getDatabasePath(args, idsSliceCoreTransport.time[0])}")

coreTransportView = CoreTransportView(idsSliceCoreTransport)
coreTransportView.viewFluxes()
