#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter
from idstools.machinedescription import MachineDescription
from idstools.set_logger import set_logger
from idstools.utils.clihelper import dbentryParser, getDatabasePath
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.pf_active import PFActiveView
from idstools.view.wall import WallView

# ----------------------------------------------------------------------


logger = setupLogger("module", stdout_level=logging.INFO)


def plotMachineDescription(idsData):
    """
    The `plotMachineDescription` method is responsible for plotting the machine description based on the provided pulse list.
    """

    # Initialization
    canvas = Canvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="R (m)", ylabel="Z (m)", row=0, col=0)

    ax.set_aspect("equal", adjustable="box")

    databasePath = ""
    # Plot Overlay
    for idsName, idsDataAndConfig in idsData.items():
        if idsDataAndConfig["yamlConfig"] is None:
            logger.error(f"Could not retrieve machine description for {idsName}")
            databasePath += f"{idsName} = not found"
            continue
        if idsName == "pf_active":
            pfcoilsview = PFActiveView(idsDataAndConfig["idsData"])
            pfcoilsview.viewActivePfCoils(ax)
            databasePath += (
                "pf_active = "
                + getDatabasePath(idsDataAndConfig["connectionArgs"])
                + "\n"
            )

        elif idsName == "wall":
            wallview = WallView(idsDataAndConfig["idsData"])
            wallview.view_wall(ax)
            databasePath += (
                "wall = " + getDatabasePath(idsDataAndConfig["connectionArgs"]) + "\n"
            )
        else:
            databasePath += (
                f"{idsName} = "
                + getDatabasePath(idsDataAndConfig["connectionArgs"])
                + "No visualization yet\n"
            )
            logger.info(
                f"Visualization is not implemented yet for machine description {idsName}"
            )

    # wallview.view_DIR(ax)
    # wallview.view_TS(ax)
    # wallview.view_Cryostat(ax)

    ax.plot()

    canvas.setText(text=databasePath, y=0.95)

    canvas.fig.subplots_adjust(
        top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2
    )
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    canvas.fig.suptitle("ITER Machine Description", size=12)
    if args.save:
        fname = os.path.basename(__file__) + "_iter_machine_description.png"
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname=os.path.join(args.directory,fname)
        canvas.save(fname)
    else:
        canvas.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="---- View machine description by getting information of data from md_summary file",formatter_class=RichHelpFormatter,
    )
    subparsers = parser.add_subparsers(help="sub-commands help")

    subparserList = subparsers.add_parser(
        "list", help="list machine description databases", parents=[dbentryParser]
    )
    subparserList.set_defaults(cmd="list")
    subparserList.add_argument(
        "ids",
        nargs="*",
        type=str,
        help="IDS names",
    )
    subparserList.add_argument(
        "--obsolete",
        help="Shows obsolete files",
        action="store_true",
    )
    subparserList.add_argument(
        "--checkValidity",
        help="Checks if database exists and also tries to retrive ids",
        action="store_true",
    )
    subparserPlot = subparsers.add_parser(
        "plot", help="Plot Machine description databases", parents=[dbentryParser]
    )
    subparserPlot.set_defaults(cmd="plot")
    subparserPlot.add_argument(
        "idslist",
        nargs="*",
        help="Provide ids list here.. Space separated values for example :  pf_active wall",
    )
    subparserPlot.add_argument(
        "--save",
        help="Save figure at default location",
        action="store_true",
    )
    subparserPlot.add_argument(
        "--directory",
        help="Directory to save the figure",
        default=None, 
    )
    args = parser.parse_args()
    # Default command if not provided
    if "cmd" not in args.__dict__:
        args.cmd = "list"
        args.obsolete = False
        args.checkValidity = False
        args.ids = []

    machineDescription = MachineDescription(args)
    if args.cmd == "list":
        data = machineDescription.getMDSummary(
            args.ids, args.obsolete, args.checkValidity
        )
        print(
            f"{'Pulse': >11} | {'IDS Name' : >28} | {'Status': >10} | {'description'}"
        )
        print(
            f"--------------------------------------------------------------------------"
        )
        for pulse, pulseData in data.items():
            idsname = pulseData["config"]["ids"]
            status = pulseData["config"]["status"]
            description = pulseData["config"]["description"]
            print(f"{pulse : >11} | {idsname : >28} | {status: >10} | {description}")

    if args.cmd == "plot":
        if args.idslist:
            idsData = machineDescription.getMDDataByIdsList(args.idslist)
            plotMachineDescription(idsData)
        else:
            logger.info(
                "Provde machine description idses that you want to plot e.g pf_active, wall etc "
            )
