#! /usr/bin/env python3
# migrated from print_sources by David.Coster@ipp.mpg.de

import argparse
import logging
import os
import sys

import imas
from imas import imasdef

root_path = os.path.dirname(os.path.dirname(__file__))
sys.path.append(root_path)

from idstools.utils.clihelper import getBackendID, imasParser
from idstools.utils.idslogger import setupLogger
from idstools.view.core_sources.basic import CoreSourcesView

logger = setupLogger("module", stdout_level=logging.INFO)

slicingMethods = {
    "CLOSEST": imasdef.CLOSEST_INTERP,
    "PREVIOUS": imasdef.PREVIOUS_INTERP,
    "LINEAR": imasdef.LINEAR_INTERP,
}
# Management of input arguments
parser = argparse.ArgumentParser(
    description="View information about sources",
    epilog="""
""",
    formatter_class=argparse.RawTextHelpFormatter,
    parents=[imasParser],
)

parser.add_argument(
    "-m",
    "--slicingmethod",
    type=str,
    default="CLOSEST",
    choices=["CLOSEST", "PREVIOUS", "LINEAR"],
    help="Slicing method \t(default=%(default)s)",
)

parser.add_argument("-o", "--occurrence", type=int, default=0, help="occurrence")
parser.add_argument("shot", type=int, help="Shot number")
parser.add_argument("run", type=int, help="Run number")
parser.add_argument("-t", "--time", type=float, help="Time", default=-99)
args = parser.parse_args()

connection = imas.DBEntry(
    getBackendID(args.backend),
    args.database,
    args.shot,
    args.run,
    user_name=args.user,
)
status, idx = connection.open()

if status != 0:
    logger.critical("Error opening pulse! Please check existence.")
    sys.exit(status)

idsSliceCoreSources = connection.get_slice(
    "core_sources",
    args.time,
    slicingMethods[args.slicingmethod],
    occurrence=args.occurrence,
)
if len(idsSliceCoreSources.time) == 0:
    logger.critical("Time vector is empty! aborting")
    sys.exit(status)

print(
    "\nTime = %0.3f for %s/%s/%s/%s/%s\n"
    % (
        idsSliceCoreSources.time,
        args.user,
        args.database,
        args.version,
        args.shot,
        args.run,
    ),
    end="",
)
coreSourcesView = CoreSourcesView(idsSliceCoreSources)
coreSourcesView.viewSources()
