#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# migrated from neutronplot
import argparse
import logging
import sys

import imas

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.distribution_sources import DistributionSourcesView

# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Display the neutron profiles from the distribution_sources IDSs [previously known as neutronplot]",
    parents=[dbentryParser],
)

parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=-99.0
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)

args = parser.parse_args()
logger = setupLogger("module", stdout_level=logging.INFO)


# Open the database and read the necessary IDSs
connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

hostdir = getDatabasePath(args)
if hostdir is None:
    logger.critical(
        "Environment variable IMAS_HOME is not defined. Quitting.",
    )
    exit(1)

try:
    # connection.distribution_sources.get()
    idsDistributionSources = imas.distribution_sources()
    idsDistributionSources.time = connection.partial_get("distribution_sources", "time")
    if idsDistributionSources.time is None:
        logger.critical(
            "No distribution_sources IDS in the data-entry --> Abort.",
        )
        exit()

except Exception:
    logger.critical(
        "The distribution_sources IDS is absent from the input data-entry",
    )
    logger.critical(
        "----> Aborted.",
    )
    exit()

timeArray = idsDistributionSources.time
timeIndex, timeValue = getNearestTime(timeArray, args.time)

idsSliceDistributionSources = connection.get_slice("distribution_sources", timeValue, 1)

nsources = len(idsSliceDistributionSources.source)
if nsources > 1:
    logger.info(
        f"Distribution_sources contains {nsources} sources",
    )
else:
    logger.info(
        f"Distribution_sources contains {nsources} source",
    )


active = [1] * nsources  # A priori all sources are active
idsDistributionSources.source.resize(nsources)
for isource in range(nsources):
    idsDistributionSources.source[isource].profiles_1d.resize(1)
    idsDistributionSources.source[isource].global_quantities.resize(1)
    idsDistributionSources.source[isource].process.resize(1)
    try:
        idsDistributionSources.source[isource].profiles_1d[
            0
        ] = idsSliceDistributionSources.source[isource].profiles_1d[0]
    except Exception:
        logger.warning(
            f"Source {str(isource)} has no profiles_1d -> considered as inactive",
        )
        active[isource] = 0
    try:
        idsDistributionSources.source[isource].global_quantities[
            0
        ] = idsSliceDistributionSources.source[isource].global_quantities[0]
    except Exception:
        if active[isource] == 1:
            logger.warning(
                f"Source {str(isource)} has no global_quantities -> considered as inactive",
            )
            active[isource] = 0
    try:
        idsDistributionSources.source[isource].process[
            0
        ] = idsSliceDistributionSources.source[isource].process[0]
    except Exception:
        if active[isource] == 1:
            logger.warning(
                f"Source {str(isource)} has no process -> considered as inactive",
            )
            active[isource] = 0

if sum(active) == 0:
    logger.critical("No active neutron sources --> Leave.")
    exit()

canvas = Canvas(1, 1)
ax = canvas.add_axes(title="", xlabel="", row=0, col=0)
distributionSourcesView = DistributionSourcesView(idsDistributionSources)
distributionSourcesView.viewNeutrons(ax)
distributionSourcesView.viewTime(ax, timeValue)

canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")

canvas.fig.subplots_adjust(
    top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2
)
canvas.get_current_fig_manager().set_window_title(sys.argv[0])
canvas.fig.suptitle(getTitle(args, "Neutrons profiles", timeValue), size=12)
if args.save:
    fname = getFileName(args, "Neutrons", timeValue)
    canvas.save(fname)
else:
    canvas.show()
