#!/usr/bin/env python
import argparse
import json
import logging
import sys

import imas

from idstools.compute.common import getNearestTime
from idstools.utils.clihelper import getBackendID, getDatabasePath, imasParser
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.core_profiles import CoreProfilesView
from idstools.view.equilibrium import EquilibriumView
from idstools.view.summary import SummaryView

# ----------------------------------------------------------------------

# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Display the plasma kinetic profiles and equilibrium from the core_profiles and equilibrium IDSs",
    parents=[imasParser],
)
parser.add_argument("-s", "--shot", help="Shot number", required=True, type=int)
parser.add_argument("-r", "--run", help="Run number", required=True, type=int)
group = parser.add_mutually_exclusive_group()
group.add_argument(
    "-t", "--time", help="Time for profiles", required=False, type=float, default=-99.0
)
group.add_argument(
    "-n",
    "--noProfiles",
    action="store_true",
    help="Do not plot profiles or equilibrium",
)
parser.add_argument(
    "-i",
    "--info",
    action="store_true",
    help="Add title with additional provenance information",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
args = parser.parse_args()
logger = setupLogger("module", stdout_level=logging.INFO)

# Open the database and read the necessary IDSs
connection = imas.DBEntry(
    getBackendID(args.backend),
    args.database,
    args.shot,
    args.run,
    user_name=args.user,
    data_version=args.version,
)
err, n = connection.open()
if err != 0:
    logger.critical(
        f"Shot {str(args.shot)}, run {str(args.run)} for user_or_path = {args.user} and database = {args.database} does not exist",
    )
    logger.critical(
        "----> Aborted.",
    )
    exit(0)

hostdir = getDatabasePath(args)
if hostdir is None:
    logger.critical(
        "Environment variable IMAS_HOME is not defined. Quitting.",
    )
    exit(1)


if not args.noProfiles:
    try:
        idsCoreProfiles = imas.core_profiles()  # To initialise the empty IDS structure
        idsCoreProfiles.time = connection.partial_get("core_profiles", "time")
        idsCoreProfiles.global_quantities = connection.partial_get(
            "core_profiles", "global_quantities"
        )
        if idsCoreProfiles.time is None:
            logger.critical(
                "No core_profiles IDS in the data-entry --> Abort.", file=sys.stderr
            )
            exit()
    except:
        logger.critical(
            "The core_profiles IDS is absent from the input data-entry", file=sys.stderr
        )
        logger.critical("----> Aborted.", file=sys.stderr)
        exit()

    try:
        idsEquilibrium = imas.equilibrium()  # To initialise the empty IDS structure
    except:
        logger.critical(
            "The equilibrium IDS is absent from the input data-entry", file=sys.stderr
        )
        logger.critical("----> Aborted.", file=sys.stderr)
        exit()

    # Search for adequate time slice for display
    timeArray = idsCoreProfiles.time
    ntime = len(idsCoreProfiles.time)
    timeIndex, timeValue = getNearestTime(timeArray, args.time)

    # Read 1D-profiles for this time slice
    idsCoreProfiles.profiles_1d.resize(1)
    idsCoreProfiles.profiles_1d[0] = connection.partial_get(
        "core_profiles", "profiles_1d(" + str(timeIndex) + ")"
    )

    idsEquilibrium.time_slice.resize(1)
    idsEquilibrium.time_slice[0].profiles_2d.resize(1)
    idsEquilibrium.time_slice[0].profiles_2d = connection.partial_get(
        "equilibrium", "time_slice(" + str(timeIndex) + ")/profiles_2d"
    )

try:
    idsSummary = connection.get("summary")
except:
    logger.critical(
        "The summary IDS is absent from the input data-entry", file=sys.stderr
    )
    logger.critical("----> Aborted.", file=sys.stderr)
    exit(1)


summaryTime = len(idsSummary.time)

if summaryTime < 1:
    logger.critical(
        "The summary IDS is absent from the input data-entry", file=sys.stderr
    )
    logger.critical("----> Aborted.", file=sys.stderr)
    exit(1)


if not args.noProfiles:
    canvas = Canvas(4, 2)
else:
    canvas = Canvas(4, 1)
ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax2 = canvas.add_axes(title="", xlabel="", row=1, col=0, sharex=ax1)
ax3 = canvas.add_axes(title="", xlabel="", row=2, col=0, sharex=ax1)
ax4 = canvas.add_axes(title="", xlabel="", row=3, col=0, sharex=ax1)
if not args.noProfiles:
    ax5 = canvas.add_axes(title="", xlabel="", row=0, col=1, rowspan=2)
    ax6 = canvas.add_axes(title="", xlabel="", row=2, col=1)
    ax7 = canvas.add_axes(title="", xlabel="", row=3, col=1)

# H&CD waveforms
objeSummaryView = SummaryView(idsSummary)
objeSummaryView.viewHCDWaveforms(ax1)

objeSummaryView.viewHmode(ax1)
ax1.tick_params(
    axis="x", which="both", bottom=False, top=False, right=False, labelbottom=False
)

if not args.noProfiles:
    ax1.set_title("Profiles displayed for t = " + "%.1f" % timeValue + " s")
    objeSummaryView.viewTimeLine(ax1, timeValue)

objeSummaryView.viewIpB0Waveforms(ax2)

objeSummaryView.viewHmode(ax2)
ax2.tick_params(
    axis="x", which="both", bottom=False, top=False, right=False, labelbottom=False
)
if not args.noProfiles:
    objeSummaryView.viewTimeLine(ax2, timeValue)


objeSummaryView.viewEnergyContentWaveforms(ax3)

objeSummaryView.viewHmode(ax3)
ax3.tick_params(
    axis="x", which="both", bottom=False, top=False, right=False, labelbottom=False
)
if not args.noProfiles:
    objeSummaryView.viewTimeLine(ax3, timeValue)

objeSummaryView.viewVloopWaveforms(ax4)

objeSummaryView.viewHmode(ax4)

if not args.noProfiles:
    objeSummaryView.viewTimeLine(ax4, timeValue)


if not args.noProfiles:
    coreCoreProfilesView = CoreProfilesView(idsCoreProfiles)
    coreCoreProfilesView.viewQProfileAndMagneticShearProfile(ax6)

    coreCoreProfilesView.viewCurrentDesnityProfiles(ax7)

    ViewEquilibrium = EquilibriumView(idsEquilibrium)
    ViewEquilibrium.viewEquilibrium(ax5)

if args.info:
    try:
        dataset_description = connection.get("dataset_description")
        if (
            dataset_description.ids_properties.homogeneous_time
            == imas.imasdef.EMPTY_INT
        ):
            got_dataset_description = False
        else:
            got_dataset_description = True
    except:
        logger.warning(
            "Warning: The dataset_description IDS is absent from the input data-entry"
        )
        got_dataset_description = False
    # F4F specific?
    if got_dataset_description:
        canvas.setSupTitle(
            f"{args.user} / {args.database} / {args.version} ; {args.shot} / {args.run}\nprovider={idsSummary.ids_properties.provider}, shot_date_time={dataset_description.pulse_time_begin}\ndata_dictionary={idsSummary.ids_properties.version_put.data_dictionary}, access_layer-{idsSummary.ids_properties.version_put.access_layer}"
        )
    else:
        additional_data = ""
        if idsSummary.tag.name != "":
            try:
                additional_data = json.loads(idsSummary.tag.name)
            except:
                additional_data = ""
        if "date" in additional_data:
            txtdate = additional_data["date"]
            txttime = additional_data["time"]
            canvas.setSupTitle(
                f"{args.user} / {args.database} / {args.version} ; {args.shot} / {args.run}\nprovider={idsSummary.ids_properties.provider}, shot_date={txtdate}, shot_time={txttime}\ndata_dictionary={idsSummary.ids_properties.version_put.data_dictionary}, access_layer={idsSummary.ids_properties.version_put.access_layer}"
            )
        else:
            canvas.setSupTitle(
                f"{args.user} / {args.database} / {args.version} ; {args.shot} / {args.run}\nprovider={idsSummary.ids_properties.provider}, creation_date={idsSummary.ids_properties.creation_date}\ndata_dictionary={idsSummary.ids_properties.version_put.data_dictionary}, access_layer={idsSummary.ids_properties.version_put.access_layer}"
            )

if not args.noProfiles:
    canvas.setText(
        text=f"{hostdir} Shot {args.shot} / Run {args.run} - Time {timeValue:.1f}"
    )
if args.save:
    if args.noProfiles:
        fname = f"summary_{args.user}_{args.database}_{args.version}_{args.shot}_{args.run}.png"
    else:
        fname = f"Scenario_shot_{args.shot}_run_{args.run}_time_{timeValue:.1f}.png"

    canvas.save(fname)
else:
    canvas.show()


# if args.noProfiles:
#     ax = plt.gca()
#     xmin, xmax = ax.get_xlim()
#     ymin, ymax = ax.get_ylim()
#     plt.text(xmax,ymin-0.5*(ymax-ymin),hostdir+' - Shot '+str(args.shot)+' / '+' Run '+str(args.run),fontsize=6,color='black',ha='right')

# if args.Title:
#     try:
#         dataset_description = connection.get('dataset_description')
#         if dataset_description.ids_properties.homogeneous_time==imas.imasdef.EMPTY_INT:
#             got_dataset_description = False
#         else:
#             got_dataset_description = True
#     except:
#         print('Warning: The dataset_description IDS is absent from the input data-entry', file=sys.stderr)
#         got_dataset_description = False
#     # F4F specific?
#     if got_dataset_description:
#         plt.suptitle('%s / %s / %s ; %s / %s\nprovider=%s, shot_date_time=%s\ndata_dictionary=%s, access_layer-%s' % (args.user, args.database, args.version, args.shot, args.run, summary.ids_properties.provider, dataset_description.pulse_time_begin, summary.ids_properties.version_put.data_dictionary, summary.ids_properties.version_put.access_layer))
#     else:
#         additional_data = ''
#         if summary.tag.name != '':
#             try:
#                 additional_data = json.loads(summary.tag.name)
#             except:
#                 additional_data = ''
#         if 'date' in additional_data:
#             plt.suptitle('%s / %s / %s ; %s / %s\nprovider=%s, shot_date=%s, shot_time=%s\ndata_dictionary=%s, access_layer=%s' % (args.user, args.database, args.version, args.shot, args.run, summary.ids_properties.provider, additional_data['date'], additional_data['time'], summary.ids_properties.version_put.data_dictionary, summary.ids_properties.version_put.access_layer))
#         else:
#             plt.suptitle('%s / %s / %s ; %s / %s\nprovider=%s, creation_date=%s\ndata_dictionary=%s, access_layer=%s' % (args.user, args.database, args.version, args.shot, args.run, summary.ids_properties.provider, summary.ids_properties.creation_date, summary.ids_properties.version_put.data_dictionary, summary.ids_properties.version_put.access_layer))

# # extra plots


# plt.subplots_adjust(left=0.1, bottom=None, right=0.85, top=None, wspace=0.1, hspace=0.1)
# #for ax in [ax1, ax2, ax3]:
# #    plt.setp(ax.get_xticklabels(), visible=False)
#     # The y-ticks will overlap with "hspace=0", so we'll hide the bottom tick
# #    ax.set_yticks(ax.get_yticks()[1:])
# Signature(hostdir,args.shot,args.run,plt)

# fig = plt.gcf()
# fig.set_size_inches(10,8)


# try:
#     if args.noProfiles:
#         fname = 'summary_%s_%s_%s_%s_%s.png' % (args.user, args.database, args.version, args.shot, args.run)
#     else:
#         fname = 'Scenario'+'_shot_'+str(args.shot)+'_run_'+str(args.run)+'_time_'+'%.1f' % time+'.png'
#     fig.savefig(fname, dpi=100)
#     print('----> Figure saved to '+fname, file=sys.stderr)
# except:
#     print('The figure could not be saved (check local permissions).', file=sys.stderr)

# plt.show()

# Starts plotting
# import matplotlib

# if 'DISPLAY' not in os.environ:
#     matplotlib.use('agg')
# else:
#     matplotlib.use('TKagg')
# import matplotlib.pyplot as plt
# import matplotlib.ticker as mtick

# # Tick size and X and Y axes
# ticksize = 12
# fontsize = 12

# # Font definition
# font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}

# # Frame configuration
# nline = 4
# if args.noProfiles:
#     ncol = 2
# else:
#     ncol = 4
# legx_pos = 1.28
# legy_pos = 1.05

# # Plot signature
# def Signature(hostdir,shot,run,plt):
#     ax = plt.gca()
#     xmin, xmax = ax.get_xlim()
#     ymin, ymax = ax.get_ylim()
#     #plt.text(xmax+0.01*abs(xmax),ymax,hostdir[:-2]+' - Shot '+str(shot)+' / '+' Run '+str(run),fontsize=6,rotation=90)
#     plt.text(xmax+0.01*abs(xmax-xmin)+0.01,ymax-0.97*abs(ymax-ymin),'Shot '+str(shot)+' / '+' Run '+str(run),fontsize=5,rotation=90)
#     return

# # Legend customization
# def CustomLegend_wf(legend,fontsize):
#     frame = legend.get_frame()
#     frame.set_facecolor('0.95')
#     for label in legend.get_texts():
#         label.set_fontsize(fontsize)
#     for label in legend.get_lines():
#         label.set_linewidth(1.5)  # the legend line width
#     return

# def CustomLegend_pr(legend):
#     frame = legend.get_frame()
#     frame.set_facecolor('0.95')
#     for label in legend.get_texts():
#         label.set_fontsize(7)
#     for label in legend.get_lines():
#         label.set_linewidth(1.5)  # the legend line width
#     return

# # Plot customization
# def nice(plt,x_label_string,y_label_string,fontsize):
#     font = {'family': 'serif','color':  'darkred','weight': 'normal','size': fontsize}
#     plt.xticks(fontsize = ticksize)
#     plt.yticks(fontsize = ticksize)
#     plt.xlabel(x_label_string, fontdict=font, labelpad = 5)
#     plt.ylabel(y_label_string, fontdict=font, labelpad = 0)
#     plt.grid()
#     if len(x_label_string) < 1:
#         plt.tick_params(axis='x',which='both',bottom=False,top=False,labelbottom=False)

# def hmode_display(plot,thmin,thmax):
#     ymin = plot.gca().get_ylim()[0]
#     ymax = plot.gca().get_ylim()[1]
#     fill([th_min,th_max,th_max,th_min],[ymin,ymin,ymax,ymax],\
#          'lightyellow',  edgecolor='k',linewidth=0.08,label=r'$H_{mode}$')
#     plt.gca().set_ylim(ymin,ymax)
#     return

# def time_display(plot,time):
#     ymin = plot.gca().get_ylim()[0]
#     ymax = plot.gca().get_ylim()[1]
#     plot.plot([time,time],[ymin,ymax],color='gray',linestyle='--',linewidth=2,label=r'$t_{slice}$')
#     plt.gca().set_ylim(ymin,ymax)
# # Display the figure
