#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# migrated from pressureplot

import argparse
import logging
import sys

import imas

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.core_profiles import CoreProfilesView

logger = setupLogger("module", stdout_level=logging.INFO)

# Management of input arguments
parser = argparse.ArgumentParser(
    description="Display the plasma pressure properties from the core_profiles IDS [previsouly known as pressureplot]",
    epilog="""
""",
    formatter_class=argparse.RawTextHelpFormatter,
    parents=[dbentryParser],
)

parser.add_argument("-t", "--time", type=float, help="Time", default=-99)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)

args = parser.parse_args()

connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)


try:
    idsCoreProfiles = imas.core_profiles()
    idsCoreProfiles.time = connection.partial_get("core_profiles", "time")
    if idsCoreProfiles.time is None:
        logger.critical("No core_profiles IDS in the data-entry --> Abort.")
        exit()
except Exception:
    logger.critical("The core_profiles IDS is absent from the input data-entry")
    logger.critical("----> Aborted.")
    exit(1)

timeArray = idsCoreProfiles.time
timeIndex, timeValue = getNearestTime(timeArray, args.time)

idsCoreProfiles.profiles_1d.resize(1)  # Read 1D-profiles for this time slice
idsCoreProfiles.profiles_1d[0] = connection.partial_get(
    "core_profiles", f"profiles_1d({timeIndex})"
)
title = "Profiles displayed for t = " + "%.1f" % timeValue + " s"
canvas = Canvas(3, 1)
canvas.fig.suptitle(title, size=12)

ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0, colspan=1)
ax2 = canvas.add_axes(title="", xlabel="", row=1, col=0, colspan=1)
ax3 = canvas.add_axes(title="", xlabel="", row=2, col=0, colspan=1)

coreprofilesView = CoreProfilesView(idsCoreProfiles)

coreprofilesView.plotTotalPressureProperties(ax1)
coreprofilesView.plotIonPressureProperties(ax2)
coreprofilesView.plotElectronPressureProperties(ax3)

canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")

canvas.fig.subplots_adjust(
    top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2
)
canvas.get_current_fig_manager().set_window_title(sys.argv[0])
canvas.fig.suptitle(getTitle(args, "Pressure", timeValue), size=12)
if args.save:
    fname = getFileName(args, "Pressure", timeValue)
    canvas.save(fname)
else:
    canvas.show()
