#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging

import imas

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.equilibrium import EquilibriumView
from idstools.view.pf_active import PFActiveView

parser = argparse.ArgumentParser(
    description="---- Display the plasma equilibrium from the equilibrium IDS. It also shows pf coils position overlay if exists [Previously known as equiplot]",
    parents=[dbentryParser],
)

parser.add_argument(
    "-t", "--time", help="Time (default=middle)", type=float, default=-99.0
)
parser.add_argument(
    "-o",
    "--occurrence",
    help="Occurrence number (default=%(default)s)",
    type=int,
    default=0,
)
parser.add_argument(
    "--rho",
    help="Show rho overlay on the plot",
    action="store_true",
)
parser.add_argument(
    "--pfcoils",
    help="Show pf coils overlay on the plot",
    action="store_true",
)

parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)

args = parser.parse_args()

logger = setupLogger("module", stdout_level=logging.INFO)
connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(0)

idsObjEquilibrium = imas.equilibrium()
idsObjEquilibrium.time = connection.partial_get("equilibrium", "time", args.occurrence)
if idsObjEquilibrium.time is not None:
    timeIndex, timeValue = getNearestTime(idsObjEquilibrium.time, args.time)
    idsObjEquilibrium.time_slice.resize(1)
    idsObjEquilibrium.time_slice[0] = connection.partial_get(
        "equilibrium", f"time_slice({str(timeIndex)})", args.occurrence
    )
    ViewEquilibrium = EquilibriumView(idsObjEquilibrium)

    if args.pfcoils is True:
        idsObjPfActive = imas.pf_active()
        idsObjPfActive.coil = connection.partial_get("pf_active", "coil")
        ViewPfCoils = PFActiveView(idsObjPfActive)

    title = f"2D Equilibrium at time {timeValue:.1f}"
    canvas = Canvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="", row=0, col=0)

    if args.pfcoils is True:
        ViewPfCoils.viewActivePfCoils(ax)
        title += " Active PF Coils"

    ViewEquilibrium.viewMagneticPoloidalFlux(ax, plotRho=args.rho)

    ax.set_title(title)

    canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")
    canvas.fig.suptitle(getTitle(args, "Equilibrium", timeValue), size=12)
    if args.save:
        fname = getFileName(args, "Equilibrium", timeValue)
        canvas.save(fname)
    else:
        canvas.show()
else:
    logger.warning("Can not produce plot, equilibrium/time is None")
