#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Plot wall dimension using description
`refer data dictionary <https://sharepoint.iter.org/departments/POP/CM/IMDesign/Data%20Model/sphinx/latest.html>`_.
Example:

$ python scripts/viewwall -u public --database ITER_MD -p 116000 -r 2
$ python scripts/viewwall -u fleuryl --database west -p 54178 -r 0
$ python scripts/viewwall -u fleuryl --database tcv -p 64770 -r 1
$ python scripts/viewwall -u costerd --database aug -p 40866 -r 1
$ python scripts/viewwall -u schneim --database jet -p 92436 -r 271
$ python scripts/viewwall -u schneim --database JT-60U -p 33654 -r 1
$ python scripts/viewwall -u smiths --database D3D -p 133221 -r 0
"""
import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter

from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.wall import WallView

WallDetails = {
    "iter": ("ITER_MD", 116000, 4, "public", 3),
    "west": ("west", 54178, 0, "fleuryl", 3),
    "tcv": ("tcv", 64770, 1, "fleuryl", 3),
    "aug": ("aug", 40866, 1, "costerd", 3),
    "jet": ("jet", 92436, 271, "schneim", 3),
    "jt60": ("JT-60U", 33654, 1, "schneim", 3),
    "d3d": ("D3D", 133221, 0, "smiths", 3),
}
logger = setupLogger("module", stdout_level=logging.INFO)
parser = argparse.ArgumentParser(
    description="This script allows you to plot wall from different tokamaks",
    formatter_class=RichHelpFormatter,
)
subparsers = parser.add_subparsers(help="Commands")
predefined_wall_parser = subparsers.add_parser(
    "wall",
    help="Predefined wall information of different tokamaks : iter, tcs, west, aug, jet, jt60, d3d",
)
predefined_wall_parser.set_defaults(cmd="wall")
predefined_wall_parser.add_argument("-m", "--machine", help="Machine name", type=str)
predefined_wall_parser.add_argument(
    "--show-labels",
    help="Show labels",
    action="store_true",
)
database_command_parser = subparsers.add_parser(
    "database", help="Get wall information from given database", parents=[dbentryParser]
)
database_command_parser.set_defaults(cmd="database")

parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()
if "cmd" not in args.__dict__:
    parser.print_help()
    exit(0)
if args.cmd == "wall":
    args.machine = args.machine.lower()
    if args.machine not in WallDetails:
        logger.error(
            f"Wall details are not present of machine {args.machine}, Present predefined wall information of different tokamaks : iter, tcs, west, aug, jet, jt60, d3d"
        )
        exit(1)
    wallDetails = WallDetails[args.machine]

    args.database = wallDetails[0]
    args.pulse = wallDetails[1]
    args.run = wallDetails[2]
    args.user = wallDetails[3]
    args.version = wallDetails[4]
    args.backend = "MDSPLUS"
    args.uri = f"imas:{args.backend.lower()}?user={args.user};shot={args.pulse};run={args.run};database={args.database};version={args.version}"

connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

wallIds = connection.get("wall")

# Initialization
canvas = Canvas(1, 1)
ax = canvas.add_axes(title="", xlabel="R (m)", ylabel="Z (m)", row=0, col=0)

# Custom settings
ax.set_aspect("equal", adjustable="box")

wallview = WallView(wallIds)
wallview.view_wall(ax, showLabels=args.show_labels)
ax.plot()
canvas.setText(text=f"{getDatabasePath(args)}")

canvas.fig.subplots_adjust(
    top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2
)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
canvas.fig.suptitle(getTitle(args, "Machine description"), size=12)

if args.save:
    fname = getFileName(args, os.path.basename(__file__) + "_MachineDescription")
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname = os.path.join(args.directory, fname)
    canvas.save(fname, width=7.5, height=10)
else:
    canvas.show()
