#! /usr/bin/env python
# migrated from print_sources by David.Coster@ipp.mpg.de

import argparse
import logging
import os
import sys

import imas
from imas import imasdef

root_path = os.path.dirname(os.path.dirname(__file__))
sys.path.append(root_path)

from idstools.utils.clihelper import getBackendID, imasParser
from idstools.utils.idslogger import setupLogger
from idstools.view.core_sources.basic import CoreSourcesView

logger = setupLogger("module", stdout_level=logging.INFO)

slicingMethods = {
    "CLOSEST": imasdef.CLOSEST_INTERP,
    "PREVIOUS": imasdef.PREVIOUS_INTERP,
    "LINEAR": imasdef.LINEAR_INTERP,
}
# Management of input arguments
parser = argparse.ArgumentParser(
    description="View information about sources",
    epilog="""
""",
    formatter_class=argparse.RawTextHelpFormatter,
    parents=[imasParser],
)

parser.add_argument(
    "-m",
    "--slicingmethod",
    type=str,
    default="CLOSEST",
    choices=["CLOSEST", "PREVIOUS", "LINEAR"],
    help="Slicing method \t(default=%(default)s)",
)

parser.add_argument("-o", "--occurrence", type=int, default=0, help="occurrence")
parser.add_argument("shot", type=int, help="Shot number")
parser.add_argument("run", type=int, help="Run number")
parser.add_argument("-t", "--time", type=float, help="Time", default=-99)
args = parser.parse_args()

connection = imas.DBEntry(
    getBackendID(args.backend),
    args.database,
    args.shot,
    args.run,
    user_name=args.user,
)
status, idx = connection.open()

if status != 0:
    logger.critical("Error opening pulse! Please check existence.")
    sys.exit(status)

idsSliceCoreSources = connection.get_slice(
    "core_sources",
    args.time,
    slicingMethods[args.slicingmethod],
    occurrence=args.occurrence,
)

print(
    "\nTime = %0.3f for %s/%s/%s/%s/%s\n"
    % (
        idsSliceCoreSources.time,
        args.user,
        args.database,
        args.version,
        args.shot,
        args.run,
    ),
    end="",
)
coreSourcesView = CoreSourcesView(idsSliceCoreSources)
coreSourcesView.viewSources()


# for s in S.source:
#     print(s.identifier.name)
#     print("       electrons", end="")
#     # electrons
#     i = s.profiles_1d[0].electrons
#     if len(i.particles) == 0:
#         print("     particles     --       ", end="")
#     else:
#         print(
#             "     particles %13.6e"
#             % (np.trapz(i.particles, s.profiles_1d[0].grid.volume)),
#             end="",
#         )
#     if len(i.energy) == 0:
#         print("     energy     --       ")
#     else:
#         print("     energy %13.6e" % (np.trapz(i.energy, s.profiles_1d[0].grid.volume)))
#     # ions
#     for i in s.profiles_1d[0].ion:
#         if len(i.element) > 0:
#             print("    ", i.element[0].a, i.element[0].z_n, i.z_ion, end="")
#             if len(i.particles) == 0:
#                 print("     particles     --       ", end="")
#             else:
#                 print(
#                     "     particles %13.6e"
#                     % (np.trapz(i.particles, s.profiles_1d[0].grid.volume)),
#                     end="",
#                 )
#             if len(i.energy) == 0:
#                 print("     energy     --     ")
#             else:
#                 print(
#                     "     energy %13.6e"
#                     % (np.trapz(i.energy, s.profiles_1d[0].grid.volume))
#                 )
