#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# migrated from rotationplot

import argparse
import logging

import imas

from idstools.compute.common import getNearestTime
from idstools.utils.clihelper import getBackendID, getDatabasePath, imasParser
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.core_profiles import CoreProfilesView

parser = argparse.ArgumentParser(
    description="---- Display the plasma kinetic profiles from the core_profiles IDSs",
    parents=[imasParser],
)
parser.add_argument("-s", "--shot", help="Shot number", required=True, type=int)
parser.add_argument("-r", "--run", help="Run number", required=True, type=int)
parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=99.0
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "-i",
    "--info",
    help="Adds all extra provenance info to the plot",
    action="store_true",
)
args = parser.parse_args()
logger = setupLogger("module", stdout_level=logging.INFO)

connection = imas.DBEntry(
    getBackendID(args.backend),
    args.database,
    args.shot,
    args.run,
    user_name=args.user,
    data_version=args.version,
)
err, n = connection.open()
if err != 0:
    logger.critical(
        f"Shot {str(args.shot)}, run {str(args.run)} for user_or_path = {args.user} and database = {args.database} does not exist",
    )
    logger.critical(
        "----> Aborted.",
    )
    exit()

try:
    idsCoreProfiles = imas.core_profiles()
    idsCoreProfiles.time = connection.partial_get("core_profiles", "time")
    if idsCoreProfiles.time is None:
        logger.critical("No core_profiles IDS in the data-entry --> Abort.")
        exit()
except:
    logger.critical("The core_profiles IDS is absent from the input data-entry")
    logger.critical("----> Aborted.")
    exit()

hostdir = getDatabasePath(args)

# Search for adequate time slice for display
timeArray = idsCoreProfiles.time
timeIndex, timeValue = getNearestTime(timeArray, args.time)
ntime = len(idsCoreProfiles.time)

# Read 1D-profiles for this time slice
idsCoreProfiles.profiles_1d.resize(1)
idsCoreProfiles.profiles_1d[0] = connection.partial_get(
    "core_profiles", f"profiles_1d({timeIndex})"
)

title = f"Kinetic profiles, t={timeValue:.1f}s, shot={args.shot}/run={args.run}"
canvas = Canvas(2, 2)
canvas.fig.subplots_adjust(wspace=0.5, top=0.8)
canvas.fig.suptitle(title, size=12)

ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax2 = canvas.add_axes(title="", xlabel="", row=0, col=1)
ax3 = canvas.add_axes(title="", xlabel="", row=1, col=0)
ax4 = canvas.add_axes(title="", xlabel="", row=1, col=1)


coreprofilesView = CoreProfilesView(idsCoreProfiles)

coreprofilesView.plotEfieldProfile(ax1)
if args.info:
    coreprofilesView.showInfoOnPlot(ax1, f"Shot {args.shot} /  Run {args.run}")

coreprofilesView.plotToroidalVelocityProfile(ax2)
if args.info:
    coreprofilesView.showInfoOnPlot(ax2, f"Shot {args.shot} /  Run {args.run}")
    ax2.yaxis.tick_right()
    ax2.yaxis.set_label_position("right")

coreprofilesView.plotPoloidalVelocityProfile(ax3)
if args.info:
    coreprofilesView.showInfoOnPlot(ax3, f"Shot {args.shot} /  Run {args.run}")

coreprofilesView.plotDiamagneticVelocityProfile(ax4)
if args.info:
    coreprofilesView.showInfoOnPlot(ax4, f"Shot {args.shot} /  Run {args.run}")
    ax4.yaxis.tick_right()
    ax4.yaxis.set_label_position("right")

ax3.get_shared_x_axes().join(ax1, ax3)
ax1.set_xticklabels([])
ax1.set_xlabel(None)
ax4.get_shared_x_axes().join(ax2, ax4)
ax2.set_xticklabels([])
ax2.set_xlabel(None)
canvas.fig.tight_layout()
if args.save:
    fname = (
        "Kinetic_profiles"
        + "_shot_"
        + str(args.shot)
        + "_run_"
        + str(args.run)
        + "_time_"
        + "%.1f" % timeValue
        + ".png"
    )
    canvas.save(fname)
else:
    canvas.show()
