#!/usr/bin/env python3
"""Show size and time of IDSs.
Author : David.Coster@ipp.mpg.de

The module retrieves the size of IDS objects from a database entry and shows IDS size in bytes and the time taken to read each object. 
It also shows total size of all IDS objects in the data entry. It shows total time taken to read all objects from the data entry

Example:
    Following is the example how to use dbsize module
    literal blocks::

        $ python scripts/idssize -s 122525 -r 1
        # python scripts/viewwall -u public --database ITER_MD -s 116000 -r 2
        # python scripts/viewwall -u fleuryl --database west -s 54178 -r 0
        # python scripts/viewwall -u fleuryl --database tcv -s 64770 -r 1
        # python scripts/viewwall -u costerd --database aug -s 40866 -r 1
        # python scripts/viewwall -u schneim --database jet -s 92436 -r 271
        # python scripts/viewwall -u schneim --database JT-60U -s 33654 -r 1
        # python scripts/viewwall -u smiths --database D3D -s 133221 -r 0
        # https://sharepoint.iter.org/departments/POP/CM/IMDesign/Data%20Model/CI/imas-3.37.2/wall.html


Attributes:
    shot (int): shot number
    run (int): run number

Todo:
    * TODOs

"""
import argparse

import imas

from idstools.utils.clihelper import getBackendID, imasParser
from idstools.utils.idslogger import setupLogger
from idstools.view.common.basic import Canvas
from idstools.view.wall.basic import WallView

WallDetails = {
    "iter": ("ITER_MD", 116000, 2, "public"),
    "west": ("west", 54178, 0, "fleuryl"),
    "tcv": ("tcv", 64770, 1, "fleuryl"),
    "aug": ("aug", 40866, 1, "costerd"),
    "jet": ("jet", 92436, 271, "schneim"),
    "jt60": ("JT-60U", 33654, 1, "schneim"),
    "d3d": ("D3D", 133221, 0, "smiths"),
}

parser = argparse.ArgumentParser(
    description="Wall plot",
)
subparsers = parser.add_subparsers(help="Commands")
predefined_wall_parser = subparsers.add_parser(
    "wall",
    help="Predefined wall information of different tokamaks : iter, tcs, west, aug, jet, jt60, d3d",
)
predefined_wall_parser.set_defaults(cmd="wall")
predefined_wall_parser.add_argument("machine", help="Shot number", type=str)
database_command_parser = subparsers.add_parser(
    "database", help="Get wall information from given database", parents=[imasParser]
)
database_command_parser.set_defaults(cmd="database")

database_command_parser.add_argument(
    "-s", "--shot", help="Shot number", required=True, type=int
)
database_command_parser.add_argument(
    "-r", "--run", help="Run number", required=True, type=int
)

args = parser.parse_args()
if args.cmd == "wall":
    if args.machine not in WallDetails:
        print(
            f"Wall details are not present of machine {args.machine}, Present predefined wall information of different tokamaks : ITER, TCS, WEST, AUG, JET, JT60, D3D"
        )
        exit(0)
    wallDetails = WallDetails[args.machine]
    args.database = wallDetails[0]
    args.shot = wallDetails[1]
    args.run = wallDetails[2]
    args.user = wallDetails[3]
    args.backend = "MDSPLUS"

try:
    if args.cmd is None:
        parser.print_help()
        exit(0)
except AttributeError:
    parser.print_help()
    exit(0)
logger = setupLogger("module")

connection = imas.DBEntry(
    getBackendID(args.backend), args.database, args.shot, args.run, args.user
)
err, n = connection.open()
if err != 0:
    logger.error(
        f"Shot {args.shot}, run {args.run} for user={args.user} and database={args.database} does not exists"
    )
    raise FileNotFoundError(
        f"Shot {args.shot}, run {args.run} for user={args.user} and database={args.database} does not exists"
    )

wallIds = connection.get("wall")

# Initialization
canvas = Canvas(1, 1)
ax = canvas.add_axes(
    title="Machine Description", xlabel="R (m)", ylabel="Z (m)", row=0, col=0
)

# Custom settings
canvas.fig.set_size_inches(7.5, 10.0)
ax.set_aspect("equal", adjustable="box")

wallview = WallView(wallIds)
wallview.view_wall(ax, linewidth=2, edgecolor="green")
ax.plot()

canvas.show()
