#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import os
from rich_argparse import RichHelpFormatter
import copy
from idstools.view.wall import WallView
import imas

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getConnectionArgsFromString,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.equilibrium import EquilibriumView
from idstools.view.pf_active import PFActiveView

parser = argparse.ArgumentParser(
    description="---- Display the plasma equilibrium from the equilibrium IDS. It also shows pf coils position overlay if exists [Previously known as equiplot]",
    parents=[dbentryParser],
    formatter_class=RichHelpFormatter,
)

parser.add_argument(
    "-t", "--time", help="Time (default=middle)", type=float, default=-99.0
)
parser.add_argument(
    "-o",
    "--occurrence",
    help="Occurrence number (default=%(default)s)",
    type=int,
    default=0,
)
parser.add_argument(
    "--rho",
    help="Show rho overlay on the plot",
    action="store_true",
)
parser.add_argument(
        "mdidslist",
        nargs="*",
        help="Provide machine descriptions that you need to plot (/pulse/run/user/backend/database/version is optional):  pf_active/pulse/run/user/backend/database/version wall/pulse/run/user/backend/database/version",
    )

parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None, 
)
args = parser.parse_args()

logger = setupLogger("module", stdout_level=logging.INFO)
connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

idsObjEquilibrium = imas.equilibrium()
idsObjEquilibrium.time = connection.partial_get("equilibrium", "time", args.occurrence)
if idsObjEquilibrium.time is not None:
    timeIndex, timeValue = getNearestTime(idsObjEquilibrium.time, args.time)
    idsObjEquilibrium.time_slice.resize(1)
    idsObjEquilibrium.time_slice[0] = connection.partial_get(
        "equilibrium", f"time_slice({str(timeIndex)})", args.occurrence
    )
    ViewEquilibrium = EquilibriumView(idsObjEquilibrium)


    title = f"2D Equilibrium at time {timeValue:.1f}"
    databaseText = ""
    canvas = Canvas(1, 1)
    ax = canvas.add_axes(title="", xlabel="", row=0, col=0)

    for mdidsInfo in args.mdidslist:
        inputargs = copy.deepcopy(args)
        _idsName, inputargs = getConnectionArgsFromString(mdidsInfo, inputargs)
        if _idsName == "pf_active":
            connection = DBMaster.getConnection(inputargs)
            if connection is not None:
                data = {}
                _idsData = connection.get(_idsName)
                connection.close()
                ViewPfCoils = PFActiveView(_idsData)
                ViewPfCoils.viewActivePfCoils(ax)
                title += "with Active PF Coils"
                databaseText += f"{_idsName}={getDatabasePath(inputargs)}\n"
            else:
                logger.warning("f{_idsName} ids is not present")

        if _idsName == "wall":
            connection = DBMaster.getConnection(inputargs)
            if connection is not None:
                data = {}
                _idsData = connection.get(_idsName)
                connection.close()
                wallview = WallView(_idsData)
                if foundData := wallview.view_wall(ax):
                    title += ", with Wall"
                    databaseText += f"{_idsName}={getDatabasePath(inputargs)}\n"
            else:
                logger.warning(f"{_idsName} ids is not present")

    ViewEquilibrium.viewMagneticPoloidalFlux(ax, plotRho=args.rho)
    ax.set_title(title)

    canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}\n{databaseText}", y =0.900)
    canvas.fig.suptitle(getTitle(args, "Equilibrium", timeValue), size=12)
    canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
    if args.save:
        fname = getFileName(
            args, f"{os.path.basename(__file__)}_Equilibrium", timeValue
        )
        if args.directory:
            if not os.path.exists(args.directory):
                os.makedirs(args.directory)
            fname=os.path.join(args.directory,fname)
        canvas.save(fname)
    else:
        canvas.show()
else:
    logger.warning("Can not produce plot, equilibrium/time is None")