#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import sys
import os
from rich_argparse import RichHelpFormatter

import imas

from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (dbentryParser, getDatabasePath,
                                      getFileName, getTitle)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.core_sources import CoreSourcesView

logger = setupLogger("module", stdout_level=logging.INFO)

parser = argparse.ArgumentParser(
    description="---- Display core_sources results [Previously known as csplot]", parents=[dbentryParser],formatter_class=RichHelpFormatter
)

parser.add_argument(
    "-t", "--time", help="time", required=False, type=float, default=-99.0
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None, 
)

args = parser.parse_args()
connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

core_sources = imas.core_sources()
core_sources.time = connection.partial_get("core_sources", "time")
if core_sources.time is None:
    logger.critical("No core_sources IDS in the data-entry --> Abort.")
    exit()

timeArray = core_sources.time
timeIndex, timeValue = getNearestTime(timeArray, args.time)
ntime = len(timeArray)

# Read quantities for this time slice
cs_slice = connection.get_slice("core_sources", timeValue, 1)
nsources = len(cs_slice.source)

if nsources > 1:
    logger.info(f"Core_sources contains {nsources} sources")
else:
    logger.info(f"Core_sources contains {nsources} source")

core_sources.source.resize(nsources)
for isource in range(nsources):
    # core_sources.source[isource].global_quantities.resize(1)
    if len(cs_slice.source[isource].profiles_1d) > 0:
        core_sources.source[isource].profiles_1d.resize(1)
        core_sources.source[isource].profiles_1d[0] = cs_slice.source[
            isource
        ].profiles_1d[0]
        try:
            core_sources.source[isource].global_quantities = connection.partial_get(
                "core_sources", f"source({isource})/global_quantities"
            )
        except Exception:
            logger.critical(
                f"source({str(isource)}) does not have global_quantities",
            )
            core_sources.source[isource].global_quantities.resize(0)
        core_sources.source[isource].identifier.name = cs_slice.source[
            isource
        ].identifier.name

nsources = len(core_sources.source)

coreSourceView = CoreSourcesView(core_sources)

canvas = Canvas(2, 4)
ret = axPowerProfiles = canvas.add_axes(title=r"Power Profiles [MW/M3]", row=0, col=0)
coreSourceView.viewPowerProfiles(axPowerProfiles)

axParticlesProfiles = canvas.add_axes(title=r"PARTICLES PROFILES [/M3/S]", row=0, col=1)
ret = coreSourceView.viewParticlesProfiles(axParticlesProfiles)

axCurrentProfiles = canvas.add_axes(title=r"CURRENT PROFILES [KA/M2]", row=0, col=2)
ret = coreSourceView.viewCurrentProfiles(axCurrentProfiles)

axPowerAndParticleWaveforms = canvas.add_axes(
    title="POWER AND PARTICLE WAVEFORMS", row=1, col=0
)
ret = coreSourceView.viewPowerAndParticleWaveforms(axPowerAndParticleWaveforms)

axParticlesWaveform = canvas.add_axes(title="PARTICLES WAVEFORM", row=1, col=1)
ret = coreSourceView.viewParticlesWaveform(axParticlesWaveform)

axCurrentWaveform = canvas.add_axes(title=r"CURRENT WAVEFORM", row=1, col=2)
ret = coreSourceView.viewCurrentWaveform(axCurrentWaveform)

axTorqueWaveform = canvas.add_axes(row=1, col=3)
ret = coreSourceView.viewTorqueWaveform(axTorqueWaveform)

canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")

canvas.fig.subplots_adjust(
    top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.287, wspace=0.2
)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
canvas.fig.suptitle(getTitle(args, "Core sources", timeValue), size=12)
if args.save:
    fname = getFileName(args, os.path.basename(__file__)+"_core_sources", timeValue)
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname=os.path.join(args.directory,fname)
    canvas.save(fname)
else:
    canvas.show()
