#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Edgeplot is added in develop2.0 developed by Anna https://confluence.iter.org/display/IMP/How+to+plot+data+from+edge_profiles
import argparse
import copy

from imas import imasdef

from idstools.compute.common import getNearestTime
from idstools.compute.wall import WallCompute
from idstools.database import DBMaster
from idstools.machinedescription import MachineDescription
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.edge_profiles import EdgeProfilesView

parser = argparse.ArgumentParser(
    description="---- Edge Profile plot",
    parents=[dbentryParser],
)

parser.add_argument("-t", "--time", type=float, help="Time", default=-99)
parser.add_argument(
    "--separatix",
    help="Show separtix",
    action="store_true",
)
parser.add_argument(
    "--wall",
    help="Show wall",
    action="store_true",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
args = parser.parse_args()

logger = setupLogger("module")

args = parser.parse_args()
connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

if args.wall:
    machineDescription = MachineDescription(copy.deepcopy(args))
    wallMDDict = machineDescription.getLatestIdsData("wall")
    wallIds = wallMDDict["idsData"]

    if wallIds is None:
        logger.error("wall ids is not present")
    else:
        wallCompute = WallCompute(wallIds)
        wallDict = wallCompute.getWall()
        r = None
        z = None
        h = None
        if wallDict is not None:
            r, z, h = wallDict["r"], wallDict["z"], wallDict["h"]

timeArray = None
try:
    timeArray = connection.partial_get("edge_profiles", "time")
except:
    logger.error("edge_profiles ids is not present")
    exit(1)
if timeArray is None:
    logger.error("edge_profiles ids : time is not present")
    exit(1)

timeIndex, timeValue = getNearestTime(timeArray, args.time)

edgeProfileIds = connection.get_slice(
    "edge_profiles", timeValue, imasdef.CLOSEST_INTERP
)

if len(edgeProfileIds.grid_ggd) == 0:
    logger.error(
        f"No values in grid_ggd  at time {timeValue}, Can not plot! Choose different time with option --time, timerange [{timeArray.min()}-{timeArray.max()}]"
    )
    exit(1)

if len(edgeProfileIds.grid_ggd[0].space) == 0:
    logger.error(
        f"No values in grid_ggd[0].space at time {timeValue}, Can not plot! Choose different time with option --time, timerange [{timeArray.min()}-{timeArray.max()}]"
    )
    exit(1)


edgeProfilesView = EdgeProfilesView(edgeProfileIds)
canvas = Canvas(2, 4)


ax4 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax1 = canvas.add_axes(title="", xlabel="", row=0, col=1, rowspan=2)
ax2 = canvas.add_axes(title="", xlabel="", row=0, col=2, rowspan=2)
ax3 = canvas.add_axes(title="", xlabel="", row=0, col=3, rowspan=2)

c1 = edgeProfilesView.viewElectronsDensity(
    ax1, timeSlice=0, showSeparatix=args.separatix
)
if c1 is not None:
    canvas.fig.colorbar(c1, ax=ax1)
    if args.wall:
        if r is not None and z is not None:
            ax1.plot(r, z, "silver")

c2 = edgeProfilesView.viewIonDensity(ax2, timeSlice=0, showSeparatix=args.separatix)
if c2 is not None:
    canvas.fig.colorbar(c2, ax=ax2)
    if args.wall:
        if r is not None and z is not None:
            ax2.plot(r, z, "silver")

c3 = edgeProfilesView.viewNeutralDensity(ax3, timeSlice=0, showSeparatix=args.separatix)
if c3 is not None:
    canvas.fig.colorbar(c3, ax=ax3)
    if args.wall:
        if r is not None and z is not None:
            ax3.plot(r, z, "silver")

edgeProfilesView.viewEquatorialPlaneAndDiverterDensity(ax4, timeSlice=0)

canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")

canvas.fig.subplots_adjust(
    top=0.93, bottom=0.067, left=0.026, right=0.953, hspace=0.287, wspace=0.12
)

canvas.fig.suptitle(getTitle(args, "Edge Profiles", timeValue), size=12)

if args.save:
    fname = getFileName(args, "edge_profiles", timeValue)
    canvas.save(fname)
else:
    canvas.show()
