#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import os

from idstools.compute.common import getNearestTime


from rich_argparse import RichHelpFormatter

from idstools.database import readScenario, readScenarioWithArgs
from idstools.input_processing import (
    beam_wall_crossing,
    check_rays_into_divertor,
    read_launching_parameters,
    read_torbeam_output,
    read_wall,
)
from idstools.utils.clihelper import getDatabasePath, getFileName, getTitle
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.core_profiles import CoreProfilesView
from idstools.view.domain.ecstray import EcStrayView
from idstools.view.equilibrium import EquilibriumView
from idstools.view.tbd import TbdView
from idstools.view.waves import WavesView

logger = setupLogger("module", stdout_level=logging.INFO)

parser = argparse.ArgumentParser(
    description="---- Shows electron cyclotron stray radiation information by showing different plots",
    formatter_class=RichHelpFormatter,
)
parser.add_argument(
    "-u",
    "--uri",
    type=str,
    help="uri",
)
parser.add_argument(
    "-t", "--time", help="Time (default=middle)", type=float, default=-99.0
)
parser.add_argument(
    "--logscale",
    help="Shows y axis with logarithmic scale wherever appropriate",
    action="store_true",
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None,
)
args = parser.parse_args()

timeIndexEquilibrium = 0
timeIndexCoreProfiles = 0
timeIndexWaves = 0

current_file_path = os.path.dirname(os.path.abspath(__file__))

scenario_file = os.path.join(current_file_path, "../resources/input/scenario.yaml")
wallfile = os.path.join(current_file_path, "../resources/input/wall2d.txt")
filelaunchers = os.path.join(current_file_path, "../resources/input/ec_waveforms.yaml")
path_result = os.path.join(current_file_path, "../resources/results/")

if not os.path.exists(scenario_file):
    scenario_file = os.path.join(current_file_path, "input/scenario.yaml")
if not os.path.exists(wallfile):
    wallfile = os.path.join(current_file_path, "input/wall2d.txt")
if not os.path.exists(filelaunchers):
    filelaunchers = os.path.join(current_file_path, "input/ec_waveforms.yaml")
if not os.path.exists(path_result):
    path_result = os.path.join(current_file_path, "results/")

wall2d = read_wall(wallfile)

# # Read launching parameters from EC waveform file
launching_parameters = read_launching_parameters(filelaunchers)
# # Read beam extra variables from Torbeam output ascii files
beam_output, timeArrayWaves = read_torbeam_output(launching_parameters, path_result)
# # Check if rays go into the divertor
check_rays_into_divertor(wall2d, beam_output)
# # Calculates where the beams cross the wall
beam_wall = beam_wall_crossing(wall2d, launching_parameters, beam_output)

if args.uri is None:
    inIDSList, outIDSDict, inputargs = readScenario(
        scenarioFilePath=scenario_file,
        inIDSList=["equilibrium", "core_profiles"],
        outIDSList=["waves"],
    )
    args.uri = f"imas:mdsplus?user={inputargs.user};pulse={inputargs.pulse};run={inputargs.run};database={inputargs.database};version={inputargs.version}"
else:
    data = readScenarioWithArgs(
        imasargs=args,
        inIDSList=["equilibrium", "core_profiles"],
        outIDSList=["waves"],
    )
    if data is not None:
        inIDSList, outIDSDict = data

equilibriumIds = inIDSList["equilibrium"]
coreProfilesIds = inIDSList["core_profiles"]
wavesIds = outIDSDict["waves"]


timeArrayEquilibrium = equilibriumIds.time  # Plot Ip
timeArrayCoreProfiles = coreProfilesIds.time
timeArrayWaves = wavesIds.time

timeSlice = args.time

# # Indices for time arrays in equilibrium, core_profiles, waves IDSs
timeIndexEquilibrium, timeValueEquilibrium = getNearestTime(
    timeArrayEquilibrium, timeSlice
)
timeIndexCoreProfiles, timeValueCoreProfiles = getNearestTime(
    timeArrayCoreProfiles, timeSlice
)
timeIndexWaves, timeValueWaves = getNearestTime(timeArrayWaves, timeSlice)
# Subplot waveforms versus time
equilibriumView = EquilibriumView(equilibriumIds)
coreProfilesView = CoreProfilesView(coreProfilesIds)
wavesView = WavesView(wavesIds)
ecstrayView = EcStrayView(equilibriumIds, coreProfilesIds, wavesIds)

canvas = Canvas(3, 3)
ax_top_view = canvas.add_axes(
    title="Top View (X,Y)", xlabel="X [m]", ylabel="Y [m]", row=0, col=0, rowspan=2
)
ax_pol_view = canvas.add_axes(
    title="Poloidal view (R,Z)", xlabel="R [m]", ylabel="Z [m]", row=0, col=1, rowspan=2
)

ax_polygon = canvas.add_axes(
    title="Beam footprints on the wall",
    xlabel=r"$\phi \times R_{max}$ [Rad.m]",
    ylabel="Length along polygon [m]",
    row=2,
    col=0,
)
ax_waveform = canvas.add_axes(
    title="Current and Electrons density waveforms", xlabel="Time [s]", row=0, col=2
)
ax_density = canvas.add_axes(
    xlabel=r"Normalised $\rho_{tor}$ [-]",
    ylabel="Density [m-3]",
    row=1,
    col=2,
)
ax_beam_index = canvas.add_axes(
    title="Beam index", xlabel="Beam index", row=2, col=1, colspan=2
)

equilibriumView.plotIP(ax_waveform)  # Plot Ip
coreProfilesView.plotElectronDensityNe0(ax_waveform)
wavesView.plotBeamIndex(ax_beam_index)
equilibriumView.plotPoloidalEquilibrium(ax_pol_view, timeIndexEquilibrium)
beamIndex = 0
wavesView.plotPoloidalTracesUpdate(ax_pol_view, timeIndexWaves, beamIndex, verbose=True)
ecstrayView.plotResonanceLayer(
    ax_pol_view, timeIndexWaves, timeIndexEquilibrium, verbose=True
)
ecstrayView.plotCutOffLayer(
    ax_pol_view, timeIndexWaves, timeIndexCoreProfiles, timeIndexEquilibrium
)
ax_topview_plot_eq = equilibriumView.plotTopviewEquilibrium(
    ax_top_view, timeIndexEquilibrium
)
ax_topview_plot_traces = wavesView.plotTopviewTracesUpdate(
    ax_top_view, timeIndexWaves, beamIndex
)
ax_density_plot_dens, nmax = coreProfilesView.plotDensityProfile(
    ax_density, timeIndexCoreProfiles, logscale=args.logscale
)

tbdView = TbdView()
ax_polygon_plot_pol = tbdView.plot_polygon(
    ax_polygon, wall2d, beam_wall, beamIndex, timeIndexWaves, timeIndexWaves
)

canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValueEquilibrium)}")
canvas.fig.subplots_adjust(
    top=0.88,
    bottom=0.11,
    left=0.035,
    right=0.902,
    hspace=0.458,
    wspace=0.234,
)
canvas.fig.suptitle(getTitle(args, "EC Stray Radiation", timeValueEquilibrium), size=12)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
if args.save:
    fname = getFileName(
        args, f"{os.path.basename(__file__)}_Equilibrium", timeValueEquilibrium
    )
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname = os.path.join(args.directory, fname)
    canvas.save(fname)
else:
    canvas.show()
