#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# migrated from svplot

import argparse
import logging
import os
import sys

import imas

from idstools.compute.common import getNearestTime
from idstools.compute.spectrometer_visible import SpectrometerVisibleCompute
from idstools.utils.clihelper import getBackendID, imasParser
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.spectrometer_visible import SpectrometerVisibleView

logger = setupLogger("module", stdout_level=logging.INFO)

parser = argparse.ArgumentParser(
    description="---- Display spectrum from spectrometer_visible", parents=[imasParser]
)
parser.add_argument("-s", "--shot", help="Shot number", required=True, type=int)
parser.add_argument("-r", "--run", help="Run number", required=True, type=int)
parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=-99.0
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
args = parser.parse_args()

connection = imas.DBEntry(
    getBackendID(args.backend),
    args.database,
    args.shot,
    args.run,
    user_name=args.user,
    data_version=args.version,
)
status, _ = connection.open()
if status != 0:
    logger.critical(
        f"Shot {args.shot}, run {args.run} for user {args.user} and database {args.database} is not reachable ----> abort."
    )
    sys.exit(status)

idsSpectrometerVisible = connection.get("spectrometer_visible")
connection.close()

timeArray = idsSpectrometerVisible.time
timeIndex, timeValue = getNearestTime(timeArray, args.time)

svCompute = SpectrometerVisibleCompute(idsSpectrometerVisible)
spectrometersList = svCompute.getValidSpectrometers()
totalSpectrometers = len(spectrometersList)

svView = SpectrometerVisibleView(idsSpectrometerVisible)
columns = 3
if totalSpectrometers / 3 == totalSpectrometers // 3:
    rows = int(totalSpectrometers / 3)
else:
    rows = int(totalSpectrometers / 3) + 1
canvasRadiance = Canvas(rows, columns)
rowCounter = 0
columnCounter = 0
scenario = f"{args.shot}/{args.run}/{timeValue:.2f}"

for spectroIndex in spectrometersList:
    toptitle = f"Spectrum (Radiance) from spectrometer_visible"

    if not args.save:
        canvasRadiance.fig.suptitle(toptitle, size=12)

    ax = canvasRadiance.add_axes(
        title="", xlabel="", row=rowCounter, col=columnCounter, colspan=1
    )
    columnCounter = columnCounter + 1
    if columnCounter == 3:
        columnCounter = 0
        rowCounter = rowCounter + 1
    radianceFileName = svView.viewRadiance(ax, spectroIndex, scenario)

if args.save:
    wm = canvasRadiance.get_current_fig_manager()
    wm.resize(1024, 768)
    canvasRadiance.save(os.path.join("", f"{radianceFileName}_radiance.png"))
else:
    canvasRadiance.show(block=False)

canvasIntensity = Canvas(rows, columns)

rowCounter = 0
columnCounter = 0
for spectroIndex in spectrometersList:
    toptitle = f"Spectrum (Intensity) from spectrometer_visible "

    if not args.save:
        canvasIntensity.fig.suptitle(toptitle, size=12)

    ax = canvasIntensity.add_axes(
        title="", xlabel="", row=rowCounter, col=columnCounter, colspan=1
    )
    columnCounter = columnCounter + 1
    if columnCounter == 3:
        columnCounter = 0
        rowCounter = rowCounter + 1
    intensityFileName = svView.viewIntensity(ax, spectroIndex, scenario)

if args.save:
    wm = canvasIntensity.get_current_fig_manager()
    wm.resize(1024, 768)
    canvasIntensity.save(os.path.join("", f"{intensityFileName}_intensity.png"))
else:
    canvasIntensity.show(block=True)
