#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Example of call:
# ecray -s [130012,130012] -r [24,23] -u schneim -d iter

import argparse
import copy
import logging
import sys
from idstools.database import DBMaster


from idstools.compute.common import getNearestTime
from idstools.compute.waves import WavesCompute
from idstools.machinedescription import MachineDescription
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.domain.ecstray import EcStrayView
from idstools.view.equilibrium import EquilibriumView
from idstools.view.wall import WallView
from idstools.view.waves import WavesView


parser = argparse.ArgumentParser(
    description="---- Display EC wave ray-tracing results [Previously known as ecray]", parents=[dbentryParser]
)

parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=-99.0
)
parser.add_argument(
    "--wall",
    help="Wall display flag",
    action="store_true",
)

parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
args = parser.parse_args()

logger = setupLogger("module", stdout_level=logging.INFO)


wallIds = None
if args.wall:
    machineDescription = MachineDescription()
    wallMDDict = machineDescription.getMDSummary("wall")

    wallIds = None
    mdargs = copy.deepcopy(args)
    # Get wall of the tokamak
    for pulse, config in wallMDDict.items():
        if "wall and divertor" in config["config"]["description"]:
            mdargs.pulse, mdargs.run = pulse.split("/")
            mdargs.pulse, mdargs.run = int(mdargs.pulse), int(mdargs.run)
            mdargs.database = "ITER_MD"
            mdargs.uri = f"imas:mdsplus?user=public;shot={mdargs.pulse};run={mdargs.run};database={mdargs.database};version={mdargs.version}"
            mdConnection = DBMaster.getConnection(mdargs)
            # print(mdConnection)
            if mdConnection is not None:
                wallIds = mdConnection.get("wall")
                mdConnection.close()
                if wallIds is None:
                    continue
                else:
                    break

    if wallIds is None:
        logger.error("wall ids is not present")


# Font/Colour definition
fontsize = 9
bndcolor = "chocolate"
shotcolors = ["b", "r", "c", "y", "m", "b"]
shotstyle = ["-", "--", "-.", ":", ".", ","]
colorcounter = 0
lpad = -1

canvas = Canvas(2, 3)
ax_polview = canvas.add_axes(title="", xlabel="", row=0, col=0, rowspan=2)
ax_topview = canvas.add_axes(title="", xlabel="", row=0, col=1, rowspan=2)
ax_powview = canvas.add_axes(title="", xlabel="", row=0, col=2)
ax_powparview = canvas.add_axes(title="", xlabel="", row=1, col=2)


# Looping over shots and runs
global_label = ""
# Color management
color = shotcolors[colorcounter % len(shotcolors)]
style = shotstyle[colorcounter % len(shotcolors)]
colorcounter += 1


conn = DBMaster.getConnection(args)
if conn is None:
    logger.critical("----> Aborted.")
    exit(1)
idsWaves = conn.get("waves")
# Search for adequate time slice for display
timeArray = idsWaves.time
ntime = len(idsWaves.time)
timeIndex, timeValue = getNearestTime(timeArray, args.time)
# Reading in waves ids and equilibrium ids
idsWaves = conn.get_slice("waves", timeValue, 1)
idsCoreProfiles = conn.get_slice("core_profiles", timeValue, 1)
idsEquilibrium = conn.get_slice("equilibrium", timeValue, 1)

if len(idsWaves.code.name) > 0:
    logger.info(f"Code name = {idsWaves.code.name.upper()}")
    labelCode = idsWaves.code.name.upper()
else:
    labelCode = getTitle(args)
ecstraView = EcStrayView(
    equilibriumIds=idsEquilibrium,
    coreProfilesIds=idsCoreProfiles,
    wavesIds=idsWaves,
)
equiView = EquilibriumView(ids=idsEquilibrium)
waveView = WavesView(idsWaves)
waveCompute = WavesCompute(idsWaves)

beamTracingDict = waveCompute.getBeamTracing(timeIndex)
logger.info(
    f"There are {beamTracingDict['activeBeamsCount']} active beam(s) and each beam has {beamTracingDict['maxTotalBeams']} ray(s)"
)

ecstraView.plotPoloidalView(ax_polview)
if args.wall:
    wallview = WallView(wallIds)
    wallview.view_wall(ax_polview, linewidth=2, edgecolor="grey")
waveView.plotPolViewTraces(
    ax_polview,
    timeIndex=0,
    color=color,
    style=style,
    fontsize=fontsize,
    labelpad=lpad,
)

equiView.plotTopviewEquilibrium(ax=ax_topview, timeIndex=0)
waveView.plotTopViewTraces(
    ax_topview, timeIndex=0, color=color, style=style, label=labelCode
)

waveView.plotElectronPower(ax_powview, timeIndex=0, color=color, style=style)
waveView.plotPowerFlowNormal(ax_powparview, timeIndex=0, color=color, style=style)


canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")

canvas.fig.subplots_adjust(
    top=0.95, bottom=0.097, left=0, right=0.948, hspace=0.2, wspace=0.108
)
canvas.get_current_fig_manager().set_window_title(sys.argv[0])
canvas.fig.suptitle(getTitle(args, "EC rays", timeValue), size=12)
if args.save:
    fname = getFileName(args, "EC_rays", timeValue)
    canvas.save(fname)
else:
    canvas.show()


# def StrToList(string):
#     if string[0] == "[":
#         slist = string.split(",")
#         slist[0] = slist[0][1:]
#         slist[-1] = slist[-1][:-1]
#         slist = [int(slist[i]) for i in range(len(slist))]
#         return slist
#     else:
#         return [int(string)]

# shotString, runString = args.shot, args.run
# shotList, runList = StrToList(shotString), StrToList(runString)
# assert len(shotList) <= len(
#     runList
# ), "There must be a run number corresponding to each shot"
# if len(runList) > len(shotList):
#     assert (
#         len(shotList) == 1
#     ), "Either give a shot for each run or give a single shot for every run"
#     shot = len(runList) * shotList

# for i in range(len(shotList)):
#     ishot = shotList[i]
#     irun = runList[i]
