#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# migrated from rotationplot

import argparse
import logging
import os
from rich_argparse import RichHelpFormatter

import imas
import sys
from idstools.compute.common import getNearestTime
from idstools.database import DBMaster
from idstools.utils.clihelper import (
    dbentryParser,
    getDatabasePath,
    getFileName,
    getTitle,
)
from idstools.utils.idslogger import setupLogger
from idstools.view.common import Canvas
from idstools.view.core_profiles import CoreProfilesView

parser = argparse.ArgumentParser(
    description="---- Display the efield, toroidal, polidal velocities from the core_profiles IDSs [previously known as rotationplot]",
    parents=[dbentryParser],
    formatter_class=RichHelpFormatter,
)

parser.add_argument(
    "-t", "--time", help="Time", required=False, type=float, default=99.0
)
parser.add_argument(
    "--save",
    help="Save figure at default location",
    action="store_true",
)
parser.add_argument(
    "--directory",
    help="Directory to save the figure",
    default=None, 
)
args = parser.parse_args()
logger = setupLogger("module", stdout_level=logging.INFO)

connection = DBMaster.getConnection(args)
if connection is None:
    logger.critical("----> Aborted.")
    exit(1)

try:
    idsCoreProfiles = imas.core_profiles()
    idsCoreProfiles.time = connection.partial_get("core_profiles", "time")
    if idsCoreProfiles.time is None:
        logger.critical("No core_profiles IDS in the data-entry --> Abort.")
        exit()
except:
    logger.critical("The core_profiles IDS is absent from the input data-entry")
    logger.critical("----> Aborted.")
    exit()

# Search for adequate time slice for display
timeArray = idsCoreProfiles.time
timeIndex, timeValue = getNearestTime(timeArray, args.time)
ntime = len(idsCoreProfiles.time)

# Read 1D-profiles for this time slice
idsCoreProfiles.profiles_1d.resize(1)
idsCoreProfiles.profiles_1d[0] = connection.partial_get(
    "core_profiles", f"profiles_1d({timeIndex})"
)

canvas = Canvas(2, 2)

ax1 = canvas.add_axes(title="", xlabel="", row=0, col=0)
ax2 = canvas.add_axes(title="", xlabel="", row=0, col=1)
ax3 = canvas.add_axes(title="", xlabel="", row=1, col=0)
ax4 = canvas.add_axes(title="", xlabel="", row=1, col=1)


coreprofilesView = CoreProfilesView(idsCoreProfiles)

coreprofilesView.plotEfieldProfile(ax1)
coreprofilesView.plotToroidalVelocityProfile(ax2)
coreprofilesView.plotPoloidalVelocityProfile(ax3)
coreprofilesView.plotDiamagneticVelocityProfile(ax4)

ax1.sharex(ax3)
ax2.sharex(ax4)

canvas.setText(text=f"{getDatabasePath(args, timeValue=timeValue)}")

canvas.fig.subplots_adjust(
    top=0.916, bottom=0.09, left=0.044, right=0.953, hspace=0.174, wspace=0.117
)
canvas.get_current_fig_manager().set_window_title(os.path.basename(__file__))
canvas.fig.suptitle(getTitle(args, "Kinetic profiles", timeValue), size=12)

if args.save:
    fname = getFileName(args, os.path.basename(__file__) + "_Kinetic_profiles", timeValue)
    if args.directory:
        if not os.path.exists(args.directory):
            os.makedirs(args.directory)
        fname=os.path.join(args.directory,fname)
    canvas.save(fname)
else:
    canvas.show()
